from django.apps import AppConfig


class OperationsConfig(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "operations"
    verbose_name = "Операционная работа"

    def ready(self) -> None:
        from auditlog.registry import auditlog

        from .models import (
            Appointment,
            AppointmentConfirmation,
            AppointmentParticipant,
            AppointmentRescheduleChain,
            AppointmentReschedulePlan,
            AppointmentRescheduleStep,
            AppointmentRescheduleStepDependency,
            AppointmentRoomOverride,
            AppointmentStaffAssignment,
            BalanceAccount,
            CenterExpense,
            CenterExpenseCategory,
            CenterLegalProfile,
            Child,
            Consent,
            ContractLegalSnapshot,
            ContractSignedFile,
            ContractTemplate,
            Counterparty,
            Document,
            DonationContract,
            EquipmentAsset,
            ExpenseFundingSplit,
            FinancialIntegrityCheckRun,
            FinancialIntegrityFinding,
            FinancialIntegrityFindingEvent,
            FundingServiceQuota,
            FundingSource,
            FundingStaffAllocation,
            GrantRecipientAllocation,
            LedgerEntry,
            OrganizationServiceContract,
            OrganizationServiceContractLine,
            ParentGuardian,
            Payment,
            PayrollAccrual,
            PayrollSheet,
            PayrollSheetLine,
            ProgramBlock,
            Recommendation,
            Room,
            Service,
            ServiceContract,
            ServiceContractLine,
            StaffAvailability,
            StaffCompensationRule,
            StaffMember,
            TimeOffRequest,
            TreatmentProgram,
        )

        tracked = [
            Child,
            ParentGuardian,
            StaffMember,
            Service,
            Room,
            FundingSource,
            Counterparty,
            CenterLegalProfile,
            CenterExpenseCategory,
            CenterExpense,
            ExpenseFundingSplit,
            EquipmentAsset,
            ContractTemplate,
            DonationContract,
            ServiceContract,
            ServiceContractLine,
            OrganizationServiceContract,
            OrganizationServiceContractLine,
            ContractLegalSnapshot,
            ContractSignedFile,
            BalanceAccount,
            Appointment,
            AppointmentParticipant,
            AppointmentStaffAssignment,
            AppointmentRoomOverride,
            AppointmentRescheduleChain,
            AppointmentReschedulePlan,
            AppointmentRescheduleStep,
            AppointmentRescheduleStepDependency,
            AppointmentConfirmation,
            LedgerEntry,
            TreatmentProgram,
            ProgramBlock,
            FundingServiceQuota,
            FundingStaffAllocation,
            GrantRecipientAllocation,
            StaffAvailability,
            StaffCompensationRule,
            FinancialIntegrityCheckRun,
            FinancialIntegrityFinding,
            FinancialIntegrityFindingEvent,
            PayrollAccrual,
            PayrollSheet,
            PayrollSheetLine,
            Recommendation,
            Document,
            Consent,
            Payment,
            TimeOffRequest,
        ]
        for model in tracked:
            auditlog.register(
                model,
                exclude_fields=["updated_at", "created_at"],
            )
