from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("schedule/", views.schedule, name="schedule"),
    path("services/", views.service_list, name="service_list"),
    path("services/new/", views.service_create, name="service_create"),
    path("services/<int:pk>/edit/", views.service_edit, name="service_edit"),
    path("services/<int:pk>/archive/", views.service_archive, name="service_archive"),
    path("services/<int:pk>/restore/", views.service_restore, name="service_restore"),
    path("rooms/", views.room_list, name="room_list"),
    path("rooms/new/", views.room_create, name="room_create"),
    path("rooms/<int:pk>/edit/", views.room_edit, name="room_edit"),
    path("staff/", views.staff_member_list, name="staff_member_list"),
    path("staff/new/", views.staff_member_create, name="staff_member_create"),
    path("staff/<int:pk>/edit/", views.staff_member_edit, name="staff_member_edit"),
    path("staff/<int:pk>/archive/", views.staff_member_archive, name="staff_member_archive"),
    path("staff/<int:pk>/restore/", views.staff_member_restore, name="staff_member_restore"),
    path("funding-sources/", views.funding_source_list, name="funding_source_list"),
    path("funding-sources/new/", views.funding_source_create, name="funding_source_create"),
    path(
        "funding-sources/<int:pk>/edit/",
        views.funding_source_edit,
        name="funding_source_edit",
    ),
    path(
        "funding-sources/<int:pk>/archive/",
        views.funding_source_archive,
        name="funding_source_archive",
    ),
    path(
        "funding-sources/<int:pk>/restore/",
        views.funding_source_restore,
        name="funding_source_restore",
    ),
    path(
        "compensation-rules/",
        views.staff_compensation_rule_list,
        name="staff_compensation_rule_list",
    ),
    path(
        "compensation-rules/new/",
        views.staff_compensation_rule_create,
        name="staff_compensation_rule_create",
    ),
    path(
        "compensation-rules/<int:pk>/edit/",
        views.staff_compensation_rule_edit,
        name="staff_compensation_rule_edit",
    ),
    path(
        "compensation-rules/<int:pk>/toggle/",
        views.staff_compensation_rule_toggle,
        name="staff_compensation_rule_toggle",
    ),
    path("work-queue/", views.work_queue, name="work_queue"),
    path(
        "financial-integrity/report/",
        views.financial_integrity_report,
        name="financial_integrity_report",
    ),
    path(
        "financial-integrity/findings/<int:pk>/",
        views.financial_integrity_finding_detail,
        name="financial_integrity_finding_detail",
    ),
    path(
        "financial-integrity/findings/<int:pk>/triage/",
        views.financial_integrity_finding_triage,
        name="financial_integrity_finding_triage",
    ),
    path(
        "financial-integrity/findings/<int:pk>/recheck/",
        views.financial_integrity_finding_recheck,
        name="financial_integrity_finding_recheck",
    ),
    path("balances/", views.balances, name="balances"),
    path("expenses/", views.center_expense_list, name="center_expense_list"),
    path("expenses/report/", views.center_expense_report, name="center_expense_report"),
    path("expenses/new/", views.center_expense_create, name="center_expense_create"),
    path(
        "expenses/<int:pk>/edit/",
        views.center_expense_edit,
        name="center_expense_edit",
    ),
    path("directories/expenses/", views.expense_directory_list, name="expense_directory_list"),
    path(
        "directories/expense-categories/new/",
        views.expense_category_create,
        name="expense_category_create",
    ),
    path(
        "directories/expense-categories/<int:pk>/edit/",
        views.expense_category_edit,
        name="expense_category_edit",
    ),
    path(
        "directories/expense-categories/<int:pk>/deactivate/",
        views.expense_category_deactivate,
        name="expense_category_deactivate",
    ),
    path(
        "directories/expense-categories/<int:pk>/activate/",
        views.expense_category_activate,
        name="expense_category_activate",
    ),
    path(
        "directories/counterparties/new/",
        views.counterparty_create,
        name="counterparty_create",
    ),
    path(
        "directories/counterparties/<int:pk>/edit/",
        views.counterparty_edit,
        name="counterparty_edit",
    ),
    path(
        "directories/counterparties/<int:pk>/archive/",
        views.counterparty_archive,
        name="counterparty_archive",
    ),
    path(
        "directories/counterparties/<int:pk>/restore/",
        views.counterparty_restore,
        name="counterparty_restore",
    ),
    path("assets/", views.equipment_asset_list, name="equipment_asset_list"),
    path("assets/new/", views.equipment_asset_create, name="equipment_asset_create"),
    path(
        "assets/<int:pk>/edit/",
        views.equipment_asset_edit,
        name="equipment_asset_edit",
    ),
    path("contracts/", views.contract_list, name="contract_list"),
    path(
        "center/legal-profile/",
        views.center_legal_profile_edit,
        name="center_legal_profile",
    ),
    path(
        "contracts/templates/new/",
        views.contract_template_create,
        name="contract_template_create",
    ),
    path(
        "contracts/templates/<int:pk>/edit/",
        views.contract_template_edit,
        name="contract_template_edit",
    ),
    path(
        "contracts/donations/new/",
        views.donation_contract_create,
        name="donation_contract_create",
    ),
    path(
        "contracts/donations/<int:pk>/edit/",
        views.donation_contract_edit,
        name="donation_contract_edit",
    ),
    path(
        "contracts/donations/<int:pk>/pdf/",
        views.donation_contract_pdf,
        name="donation_contract_pdf",
    ),
    path(
        "contracts/donations/<int:pk>/word/",
        views.donation_contract_word,
        name="donation_contract_word",
    ),
    path(
        "contracts/donations/<int:pk>/archive-signed/",
        views.donation_contract_archive_signed,
        name="donation_contract_archive_signed",
    ),
    path(
        "contracts/services/new/",
        views.service_contract_create,
        name="service_contract_create",
    ),
    path(
        "contracts/services/<int:pk>/edit/",
        views.service_contract_edit,
        name="service_contract_edit",
    ),
    path(
        "contracts/services/<int:pk>/pdf/",
        views.service_contract_pdf,
        name="service_contract_pdf",
    ),
    path(
        "contracts/services/<int:pk>/word/",
        views.service_contract_word,
        name="service_contract_word",
    ),
    path(
        "contracts/services/<int:pk>/archive-signed/",
        views.service_contract_archive_signed,
        name="service_contract_archive_signed",
    ),
    path(
        "contracts/organizations/new/",
        views.organization_service_contract_create,
        name="organization_service_contract_create",
    ),
    path(
        "contracts/organizations/<int:pk>/edit/",
        views.organization_service_contract_edit,
        name="organization_service_contract_edit",
    ),
    path(
        "contracts/organizations/<int:pk>/pdf/",
        views.organization_service_contract_pdf,
        name="organization_service_contract_pdf",
    ),
    path(
        "contracts/organizations/<int:pk>/word/",
        views.organization_service_contract_word,
        name="organization_service_contract_word",
    ),
    path(
        "contracts/organizations/<int:pk>/archive-signed/",
        views.organization_service_contract_archive_signed,
        name="organization_service_contract_archive_signed",
    ),
    path("contracts/acts/new/", views.contract_act_create, name="contract_act_create"),
    path("contracts/acts/<int:pk>/edit/", views.contract_act_edit, name="contract_act_edit"),
    path("contracts/acts/<int:pk>/word/", views.contract_act_word, name="contract_act_word"),
    path(
        "contracts/acts/<int:pk>/archive-signed/",
        views.contract_act_archive_signed,
        name="contract_act_archive_signed",
    ),
    path(
        "contracts/acts/signed-files/<int:pk>/download/",
        views.contract_act_signed_file_download,
        name="contract_act_signed_file_download",
    ),
    path(
        "contracts/signed-files/<int:pk>/download/",
        views.contract_signed_file_download,
        name="contract_signed_file_download",
    ),
    path(
        "contracts/import-preview/",
        views.contract_import_preview,
        name="contract_import_preview",
    ),
    path(
        "imports/batches/<int:pk>/",
        views.import_batch_detail,
        name="import_batch_detail",
    ),
    path(
        "imports/batches/<int:pk>/apply/",
        views.import_batch_apply,
        name="import_batch_apply",
    ),
    path("recipients/", views.recipient_list, name="recipient_list"),
    path("imports/recipients/", views.recipient_import_preview, name="recipient_import_preview"),
    path("recipients/new/", views.recipient_create, name="recipient_create"),
    path("recipients/<int:pk>/", views.recipient_detail, name="recipient_detail"),
    path("recipients/<int:pk>/edit/", views.recipient_edit, name="recipient_edit"),
    path(
        "recipients/<int:pk>/contract/", views.recipient_contract_pdf, name="recipient_contract_pdf"
    ),
    path(
        "recipients/<int:child_id>/representatives/new/",
        views.recipient_representative_create,
        name="recipient_representative_create",
    ),
    path(
        "recipient-representatives/<int:pk>/edit/",
        views.recipient_representative_edit,
        name="recipient_representative_edit",
    ),
    path(
        "recipients/<int:child_id>/certificates/new/",
        views.recipient_certificate_create,
        name="recipient_certificate_create",
    ),
    path(
        "certificates/<int:pk>/edit/",
        views.recipient_certificate_edit,
        name="recipient_certificate_edit",
    ),
    path(
        "recipients/<int:child_id>/programs/new/",
        views.program_create,
        name="program_create_for_child",
    ),
    path(
        "programs/<int:program_id>/blocks/new/",
        views.program_block_create,
        name="program_block_create",
    ),
    path(
        "program-blocks/<int:block_id>/schedule-wizard/",
        views.program_block_schedule_wizard,
        name="program_block_schedule_wizard",
    ),
    path(
        "program-blocks/<int:block_id>/transfer-funds/",
        views.program_block_transfer_funds,
        name="program_block_transfer_funds",
    ),
    path("representatives/new/", views.representative_create, name="representative_create"),
    path("representatives/<int:pk>/edit/", views.representative_edit, name="representative_edit"),
    path("balance-accounts/new/", views.balance_account_create, name="balance_account_create"),
    path(
        "balance-accounts/<int:pk>/edit/", views.balance_account_edit, name="balance_account_edit"
    ),
    path(
        "balance-accounts/<int:pk>/delete/",
        views.balance_account_delete,
        name="balance_account_delete",
    ),
    path("children/", views.recipient_list, name="child_list"),
    path("children/<int:pk>/", views.recipient_detail, name="child_detail"),
    path("appointments/new/", views.appointment_create, name="appointment_create"),
    path("appointments/<int:pk>/", views.appointment_detail, name="appointment_detail"),
    path("appointments/<int:pk>/edit/", views.appointment_edit, name="appointment_edit"),
    path("appointments/<int:pk>/move/", views.appointment_move, name="appointment_move"),
    path(
        "appointments/<int:pk>/reschedule-plans/create/",
        views.appointment_reschedule_plan_create,
        name="appointment_reschedule_plan_create",
    ),
    path("reschedule-plans/", views.reschedule_plan_list, name="reschedule_plan_list"),
    path(
        "reschedule-plans/<int:pk>/",
        views.appointment_reschedule_plan_detail,
        name="appointment_reschedule_plan_detail",
    ),
    path("appointments/<int:pk>/cancel/", views.appointment_cancel, name="appointment_cancel"),
    path("appointments/<int:pk>/billing/", views.appointment_billing, name="appointment_billing"),
    path(
        "appointments/<int:pk>/participant-program/",
        views.appointment_participant_program,
        name="appointment_participant_program",
    ),
    path(
        "appointments/<int:pk>/confirmations/send/",
        views.appointment_send_confirmation,
        name="appointment_send_confirmation",
    ),
    path(
        "confirmations/<uuid:token>/",
        views.appointment_confirmation_public,
        name="appointment_confirmation_public",
    ),
    path("specialist/", views.specialist_home, name="specialist_home"),
    path("specialist/appointments/<int:pk>/mark/", views.mark_appointment, name="mark_appointment"),
    path(
        "specialist/availability/add/",
        views.staff_availability_create,
        name="staff_availability_create",
    ),
    path(
        "specialist/availability/<int:pk>/toggle/",
        views.staff_availability_toggle,
        name="staff_availability_toggle",
    ),
    path("specialist/time-off/add/", views.time_off_request_create, name="time_off_request_create"),
    path(
        "staff/time-off/<int:pk>/decide/",
        views.time_off_request_decide,
        name="time_off_request_decide",
    ),
    path("tomorrow/", views.tomorrow, name="tomorrow"),
    path("staff/<int:pk>/timesheet/", views.staff_timesheet, name="staff_timesheet"),
    path("payroll-sheets/<int:pk>/", views.payroll_sheet_detail, name="payroll_sheet_detail"),
    path(
        "staff/<int:pk>/mass-reschedule/", views.staff_mass_reschedule, name="staff_mass_reschedule"
    ),
    path("grants/", views.grant_report, name="grant_report"),
    path("grants/<int:pk>/", views.grant_report, name="grant_report_funding"),
    path(
        "grants/quotas/new/",
        views.funding_service_quota_create,
        name="funding_service_quota_create",
    ),
    path(
        "grants/quotas/<int:pk>/edit/",
        views.funding_service_quota_edit,
        name="funding_service_quota_edit",
    ),
    path(
        "grants/quotas/<int:pk>/delete/",
        views.funding_service_quota_delete,
        name="funding_service_quota_delete",
    ),
    path(
        "grants/allocations/new/",
        views.funding_staff_allocation_create,
        name="funding_staff_allocation_create",
    ),
    path(
        "grants/allocations/<int:pk>/edit/",
        views.funding_staff_allocation_edit,
        name="funding_staff_allocation_edit",
    ),
    path(
        "grants/allocations/<int:pk>/delete/",
        views.funding_staff_allocation_delete,
        name="funding_staff_allocation_delete",
    ),
    path(
        "grants/recipient-allocations/new/",
        views.grant_recipient_allocation_create,
        name="grant_recipient_allocation_create",
    ),
    path(
        "grants/recipient-allocations/<int:pk>/edit/",
        views.grant_recipient_allocation_edit,
        name="grant_recipient_allocation_edit",
    ),
    path(
        "grants/recipient-allocations/<int:pk>/delete/",
        views.grant_recipient_allocation_delete,
        name="grant_recipient_allocation_delete",
    ),
    path("recommendations/", views.recommendation_list, name="recommendation_list"),
    path("recommendations/new/", views.recommendation_create, name="recommendation_create"),
    path(
        "recommendations/new/<int:child_id>/",
        views.recommendation_create,
        name="recommendation_create_for_child",
    ),
    path(
        "recommendations/<int:pk>/acknowledge/",
        views.recommendation_acknowledge,
        name="recommendation_acknowledge",
    ),
    path("documents/", views.document_list, name="document_list"),
    path("documents/new/", views.document_create, name="document_create"),
    path("documents/new/<int:child_id>/", views.document_create, name="document_create_for_child"),
    path("consents/", views.consent_list, name="consent_list"),
    path("consents/new/", views.consent_create, name="consent_create"),
    path("consents/new/<int:child_id>/", views.consent_create, name="consent_create_for_child"),
    path("consents/<int:pk>/word/", views.consent_word, name="consent_word"),
    path(
        "consents/<int:pk>/archive-signed/",
        views.consent_archive_signed,
        name="consent_archive_signed",
    ),
    path(
        "consents/signed-files/<int:pk>/download/",
        views.consent_signed_file_download,
        name="consent_signed_file_download",
    ),
    path("payments/new/", views.payment_create, name="payment_create"),
    path("payments/new/<int:account_id>/", views.payment_create, name="payment_create_for_account"),
]
