from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("schedule/", views.schedule, name="schedule"),
    path("work-queue/", views.work_queue, name="work_queue"),
    path("balances/", views.balances, name="balances"),
    path("recipients/", views.recipient_list, name="recipient_list"),
    path("recipients/new/", views.recipient_create, name="recipient_create"),
    path("recipients/<int:pk>/", views.recipient_detail, name="recipient_detail"),
    path("recipients/<int:pk>/edit/", views.recipient_edit, name="recipient_edit"),
    path("recipients/<int:pk>/contract/", views.recipient_contract_pdf, name="recipient_contract_pdf"),
    path("recipients/<int:child_id>/programs/new/", views.program_create, name="program_create_for_child"),
    path("programs/<int:program_id>/blocks/new/", views.program_block_create, name="program_block_create"),
    path("representatives/new/", views.representative_create, name="representative_create"),
    path("representatives/<int:pk>/edit/", views.representative_edit, name="representative_edit"),
    path("balance-accounts/new/", views.balance_account_create, name="balance_account_create"),
    path("balance-accounts/<int:pk>/edit/", views.balance_account_edit, name="balance_account_edit"),
    path("balance-accounts/<int:pk>/delete/", views.balance_account_delete, name="balance_account_delete"),
    path("children/", views.recipient_list, name="child_list"),
    path("children/<int:pk>/", views.recipient_detail, name="child_detail"),
    path("appointments/new/", views.appointment_create, name="appointment_create"),
    path("appointments/<int:pk>/", views.appointment_detail, name="appointment_detail"),
    path("appointments/<int:pk>/edit/", views.appointment_edit, name="appointment_edit"),
    path("appointments/<int:pk>/move/", views.appointment_move, name="appointment_move"),
    path("appointments/<int:pk>/cancel/", views.appointment_cancel, name="appointment_cancel"),
    path("appointments/<int:pk>/billing/", views.appointment_billing, name="appointment_billing"),
    path("appointments/<int:pk>/confirmations/send/", views.appointment_send_confirmation, name="appointment_send_confirmation"),
    path("confirmations/<uuid:token>/", views.appointment_confirmation_public, name="appointment_confirmation_public"),
    path("specialist/", views.specialist_home, name="specialist_home"),
    path("specialist/appointments/<int:pk>/mark/", views.mark_appointment, name="mark_appointment"),
    path("specialist/availability/add/", views.staff_availability_create, name="staff_availability_create"),
    path("specialist/availability/<int:pk>/toggle/", views.staff_availability_toggle, name="staff_availability_toggle"),
    path("specialist/time-off/add/", views.time_off_request_create, name="time_off_request_create"),
    path("staff/time-off/<int:pk>/decide/", views.time_off_request_decide, name="time_off_request_decide"),
    path("tomorrow/", views.tomorrow, name="tomorrow"),
    path("staff/<int:pk>/timesheet/", views.staff_timesheet, name="staff_timesheet"),
    path("staff/<int:pk>/mass-reschedule/", views.staff_mass_reschedule, name="staff_mass_reschedule"),
    path("grants/", views.grant_report, name="grant_report"),
    path("grants/<int:pk>/", views.grant_report, name="grant_report_funding"),
    path("recommendations/", views.recommendation_list, name="recommendation_list"),
    path("recommendations/new/", views.recommendation_create, name="recommendation_create"),
    path("recommendations/new/<int:child_id>/", views.recommendation_create, name="recommendation_create_for_child"),
    path("recommendations/<int:pk>/acknowledge/", views.recommendation_acknowledge, name="recommendation_acknowledge"),
    path("documents/", views.document_list, name="document_list"),
    path("documents/new/", views.document_create, name="document_create"),
    path("documents/new/<int:child_id>/", views.document_create, name="document_create_for_child"),
    path("consents/", views.consent_list, name="consent_list"),
    path("consents/new/", views.consent_create, name="consent_create"),
    path("consents/new/<int:child_id>/", views.consent_create, name="consent_create_for_child"),
    path("payments/new/", views.payment_create, name="payment_create"),
    path("payments/new/<int:account_id>/", views.payment_create, name="payment_create_for_account"),
]
