# Generated by Django 5.2.14 on 2026-05-14 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('last_name', models.CharField(max_length=120, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=120, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Приостановлен'), ('completed', 'Завершил курс'), ('waiting', 'Ожидает')], default='active', max_length=30, verbose_name='статус')),
                ('diagnosis', models.TextField(blank=True, verbose_name='диагноз/особенности')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'ребенок',
                'verbose_name_plural': 'дети',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('source_type', models.CharField(choices=[('personal', 'Личные средства'), ('grant', 'Грант'), ('sponsor', 'Спонсор'), ('charity_fund', 'Благотворительный фонд'), ('test', 'Тестовый источник')], max_length=40, verbose_name='тип')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('transfer_policy', models.CharField(choices=[('not_transferable', 'Нельзя передавать'), ('within_child', 'Можно менять услугу внутри ребенка'), ('between_children', 'Можно передавать между детьми')], default='not_transferable', max_length=40, verbose_name='правило передачи')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'источник финансирования',
                'verbose_name_plural': 'источники финансирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('last_name', models.CharField(max_length=120, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=120, verbose_name='имя')),
                ('middle_name', models.CharField(blank=True, max_length=120, verbose_name='отчество')),
                ('phone', models.CharField(max_length=40, verbose_name='телефон')),
                ('phone_alt', models.CharField(blank=True, max_length=40, verbose_name='дополнительный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('relationship_type', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('grandmother', 'Бабушка'), ('grandfather', 'Дедушка'), ('other', 'Другое')], default='mother', max_length=30, verbose_name='тип связи')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'родитель/опекун',
                'verbose_name_plural': 'родители/опекуны',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('room_type', models.CharField(choices=[('gym_big', 'АФК большой'), ('gym_small', 'АФК маленький'), ('cabinet', 'Кабинет'), ('saling', 'Система Салинг'), ('group', 'Группа'), ('other', 'Другое')], default='cabinet', max_length=40, verbose_name='тип')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='вместимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('color', models.CharField(default='#f97316', max_length=20, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'помещение',
                'verbose_name_plural': 'помещения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('category', models.CharField(choices=[('consultation', 'Диагностика/консультация'), ('speech', 'Логопед'), ('defectology', 'Дефектолог'), ('physical', 'АФК'), ('massage', 'Массаж'), ('group', 'Группа/присмотр'), ('other', 'Другое')], default='other', max_length=40, verbose_name='категория')),
                ('default_duration_minutes', models.PositiveIntegerField(default=30, verbose_name='длительность по умолчанию, мин')),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='цена по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('color', models.CharField(default='#16a34a', max_length=20, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('unit', models.CharField(choices=[('sessions', 'Занятия'), ('money', 'Рубли')], max_length=20, verbose_name='единица учета')),
                ('service_scope', models.CharField(choices=[('any', 'Любые услуги'), ('specific_service', 'Конкретная услуга')], default='any', max_length=30, verbose_name='область применения')),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='начальный остаток')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Заморожен'), ('exhausted', 'Исчерпан'), ('expired', 'Истек')], default='active', max_length=30, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_accounts', to='operations.child', verbose_name='ребенок')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_accounts', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_accounts', to='operations.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'счет баланса',
                'verbose_name_plural': 'счета баланса',
                'ordering': ['child__last_name', 'child__first_name', 'funding_source__name'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='название серии')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('days_of_week', models.CharField(help_text='Например: ПН,СР,ПТ', max_length=80, verbose_name='дни недели')),
                ('time', models.TimeField(verbose_name='время')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='длительность, мин')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=30, verbose_name='статус')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_series', to='operations.child', verbose_name='ребенок')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.room', verbose_name='помещение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'серия занятий',
                'verbose_name_plural': 'серии занятий',
                'ordering': ['start_date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('starts_at', models.DateTimeField(verbose_name='начало')),
                ('ends_at', models.DateTimeField(verbose_name='окончание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Неявка'), ('rescheduled', 'Перенесено'), ('reserved', 'Бронь')], default='confirmed', max_length=30, verbose_name='статус')),
                ('attendance_status', models.CharField(choices=[('unknown', 'Не отмечено'), ('attended', 'Пришел'), ('missed', 'Не пришел'), ('excused', 'Уважительная причина')], default='unknown', max_length=30, verbose_name='посещение')),
                ('billing_decision', models.CharField(choices=[('undecided', 'Не решено'), ('charge', 'Списать'), ('do_not_charge', 'Не списывать')], default='undecided', max_length=30, verbose_name='решение по списанию')),
                ('admin_note', models.TextField(blank=True, verbose_name='заметка администратора')),
                ('specialist_note', models.TextField(blank=True, verbose_name='заметка специалиста')),
                ('specialist_marked_at', models.DateTimeField(blank=True, null=True, verbose_name='специалист отметил')),
                ('source_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='operations.appointment', verbose_name='исходное занятие')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='operations.appointmentseries', verbose_name='серия')),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='operations.balanceaccount', verbose_name='счет списания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='operations.child', verbose_name='ребенок')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='operations.room', verbose_name='помещение')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='operations.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('entry_type', models.CharField(choices=[('credit', 'Пополнение'), ('debit', 'Списание'), ('correction', 'Корректировка')], max_length=30, verbose_name='тип операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма операции')),
                ('reason', models.TextField(blank=True, verbose_name='основание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='operations.balanceaccount', verbose_name='счет')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='operations.appointment', verbose_name='занятие')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'операция по балансу',
                'verbose_name_plural': 'операции по балансам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='child',
            name='primary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='operations.parentguardian', verbose_name='основной родитель/опекун'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('specializations', models.CharField(blank=True, max_length=255, verbose_name='специализации')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('vacation', 'Отпуск'), ('sick', 'Больничный'), ('inactive', 'Неактивен')], default='active', max_length=30, verbose_name='статус')),
                ('color', models.CharField(default='#2563eb', max_length=20, verbose_name='цвет')),
                ('can_use_mobile', models.BooleanField(default=True, verbose_name='доступ к мобильному экрану')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'специалист',
                'verbose_name_plural': 'специалисты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=20, verbose_name='приоритет')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.appointment', verbose_name='занятие')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_notes', to='operations.child', verbose_name='ребенок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_notes', to='operations.parentguardian', verbose_name='родитель')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'заметка',
                'verbose_name_plural': 'заметки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.staffmember', verbose_name='специалист'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='operations.staffmember', verbose_name='специалист'),
        ),
    ]
