# Generated by Django 5.2.14 on 2026-05-14 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'получатель', 'verbose_name_plural': 'получатели'},
        ),
        migrations.AlterModelOptions(
            name='parentguardian',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'представитель', 'verbose_name_plural': 'представители'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='operations.child', verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='appointmentseries',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_series', to='operations.child', verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='balanceaccount',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_accounts', to='operations.child', verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='child',
            name='primary_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='operations.parentguardian', verbose_name='основной представитель'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='transfer_policy',
            field=models.CharField(choices=[('not_transferable', 'Нельзя передавать'), ('within_child', 'Можно менять услугу внутри получателя'), ('between_children', 'Можно передавать между получателями')], default='not_transferable', max_length=40, verbose_name='правило передачи'),
        ),
        migrations.AlterField(
            model_name='note',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_notes', to='operations.child', verbose_name='получатель'),
        ),
        migrations.AlterField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_notes', to='operations.parentguardian', verbose_name='представитель'),
        ),
    ]
