# Generated by Django 5.2.14 on 2026-05-15 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_child_options_alter_parentguardian_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email получателя'),
        ),
        migrations.AddField(
            model_name='child',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='телефон получателя'),
        ),
        migrations.CreateModel(
            name='AppointmentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('target_type', models.CharField(choices=[('specialist', 'Специалист'), ('representative', 'Представитель'), ('recipient', 'Получатель')], max_length=30, verbose_name='кому отправлено')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='токен подтверждения')),
                ('subject', models.CharField(max_length=200, verbose_name='тема письма')),
                ('message', models.TextField(verbose_name='текст письма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('confirmed', 'Подтверждено'), ('declined', 'Отклонено')], default='pending', max_length=30, verbose_name='статус ответа')),
                ('delivery_status', models.CharField(choices=[('pending', 'Готово к отправке'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=30, verbose_name='статус отправки')),
                ('delivery_error', models.TextField(blank=True, verbose_name='ошибка отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='ответ получен')),
                ('response_note', models.TextField(blank=True, verbose_name='комментарий к ответу')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='operations.appointment', verbose_name='занятие')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_confirmations', to='operations.parentguardian', verbose_name='представитель')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_appointment_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='отправил')),
            ],
            options={
                'verbose_name': 'подтверждение занятия',
                'verbose_name_plural': 'подтверждения занятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='день недели')),
                ('starts_at', models.TimeField(verbose_name='начало')),
                ('ends_at', models.TimeField(verbose_name='окончание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='комментарий')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'рабочее окно специалиста',
                'verbose_name_plural': 'рабочие окна специалистов',
                'ordering': ['staff_member__full_name', 'weekday', 'starts_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('request_type', models.CharField(choices=[('vacation', 'Отпуск'), ('day_off', 'Отгул'), ('sick', 'Больничный'), ('schedule_change', 'Изменение графика'), ('other', 'Другое')], max_length=30, verbose_name='тип заявки')),
                ('starts_on', models.DateField(verbose_name='дата начала')),
                ('ends_on', models.DateField(verbose_name='дата окончания')),
                ('reason', models.TextField(blank=True, verbose_name='причина/комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('cancelled', 'Отменено')], default='pending', max_length=30, verbose_name='статус')),
                ('admin_note', models.TextField(blank=True, verbose_name='комментарий администратора')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='решение принято')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_time_off_requests', to=settings.AUTH_USER_MODEL, verbose_name='решение принял')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'заявка специалиста',
                'verbose_name_plural': 'заявки специалистов',
                'ordering': ['status', 'starts_on', 'staff_member__full_name'],
            },
        ),
    ]
