# Generated by Django 5.2.14 on 2026-06-02 15:29

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_pg_only_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceaccount',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.AddField(
            model_name='child',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.AddField(
            model_name='room',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.AddField(
            model_name='service',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('category', models.CharField(choices=[('medical_report', 'Медицинское заключение'), ('consent', 'Согласие'), ('ipr', 'ИПР / ИПРА'), ('contract', 'Договор'), ('other', 'Прочее')], default='other', max_length=30, verbose_name='категория')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('file', models.FileField(upload_to=operations.models.document_upload_path, verbose_name='файл')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='выдан')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='operations.child', verbose_name='получатель')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('consent_type', models.CharField(choices=[('personal_data', 'Обработка персональных данных'), ('photo_video', 'Фото- и видеосъёмка'), ('external_specialist', 'Внешний специалист'), ('other', 'Иное')], max_length=30, verbose_name='тип согласия')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='подписано')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='operations.child', verbose_name='получатель')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='operations.document', verbose_name='документ')),
            ],
            options={
                'verbose_name': 'согласие',
                'verbose_name_plural': 'согласия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма пополнения')),
                ('method', models.CharField(choices=[('bank_transfer', 'Банковский перевод'), ('cash', 'Наличные'), ('grant_transfer', 'Перевод гранта'), ('sponsor_transfer', 'Перевод спонсора'), ('other', 'Другое')], max_length=30, verbose_name='способ')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата оплаты')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='номер платёжки / комментарий')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('balance_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.balanceaccount', verbose_name='счёт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'платёж',
                'verbose_name_plural': 'платежи',
                'ordering': ['-paid_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('category', models.CharField(choices=[('treatment_method', 'Методика работы'), ('home_task', 'Домашнее задание'), ('equipment', 'Оснащение / материалы'), ('observation', 'Наблюдение'), ('other', 'Другое')], default='other', max_length=30, verbose_name='категория')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='содержание')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='выполнить до')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='принято к сведению')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='когда отмечено')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='отметил')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='operations.appointment', verbose_name='занятие')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='operations.child', verbose_name='получатель')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['child', 'category'], name='operations__child_i_b41719_idx'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['child', 'consent_type'], name='operations__child_i_4d7066_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['balance_account', '-paid_at'], name='operations__balance_3e82a0_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['child', '-created_at'], name='operations__child_i_c89d0c_idx'),
        ),
    ]
