# Generated by Django 5.2.14 on 2026-06-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_recommendation_document_consent_payment_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'Пополнение'), ('debit', 'Списание'), ('correction', 'Корректировка'), ('transfer', 'Перенос')], max_length=30, verbose_name='тип операции'),
        ),
    ]
