# Generated by Django 5.2.14 on 2026-06-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_alter_ledgerentry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='primary_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='operations.parentguardian', verbose_name='основной представитель'),
        ),
    ]
