# Generated by Django 5.2.14 on 2026-06-10 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_make_child_primary_parent_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='source_type',
            field=models.CharField(choices=[('personal', 'Личные средства'), ('grant', 'Грант'), ('sponsor', 'Спонсор'), ('charity_fund', 'Благотворительный фонд'), ('maternity_capital', 'Материнский капитал'), ('certificate', 'Сертификат'), ('test', 'Тестовый источник')], max_length=40, verbose_name='тип'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('certificate_type', models.CharField(choices=[('maternity_capital', 'Материнский капитал'), ('regional', 'Региональный сертификат'), ('sponsor', 'Спонсорский сертификат'), ('other', 'Прочее')], max_length=30, verbose_name='тип')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='номер')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='полная сумма')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='остаток')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='operations.child', verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'сертификат',
                'verbose_name_plural': 'сертификаты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='процент скидки')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='operations.child', verbose_name='получатель')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='operations.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
                'ordering': ['child__last_name', 'child__first_name'],
            },
        ),
    ]
