# Generated by Django 5.2.14 on 2026-06-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_fundingsource_source_type_certificate_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='номер в блоке'),
        ),
        migrations.AddField(
            model_name='balanceaccount',
            name='color',
            field=models.CharField(default='#f59e0b', max_length=20, verbose_name='цветовая метка'),
        ),
        migrations.AddField(
            model_name='child',
            name='color',
            field=models.CharField(default='#00a443', max_length=20, verbose_name='цветовая метка'),
        ),
        migrations.CreateModel(
            name='ProgramBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('number', models.PositiveIntegerField(default=1, verbose_name='номер блока')),
                ('title', models.CharField(max_length=200, verbose_name='название блока')),
                ('planned_sessions', models.PositiveIntegerField(default=1, verbose_name='план занятий')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('scheduled', 'Расписан'), ('in_progress', 'Идёт'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='planned', max_length=30, verbose_name='статус')),
                ('color', models.CharField(default='#b71b55', max_length=20, verbose_name='цвет')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('balance_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_blocks', to='operations.balanceaccount', verbose_name='счёт оплаты')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.service', verbose_name='услуга')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'блок программы',
                'verbose_name_plural': 'блоки программ',
                'ordering': ['program', 'number'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='program_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='operations.programblock', verbose_name='блок программы'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='program_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='operations.programblock', verbose_name='блок программы'),
        ),
        migrations.CreateModel(
            name='TreatmentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=30, verbose_name='статус')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('color', models.CharField(default='#1267f2', max_length=20, verbose_name='цвет')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_programs', to='operations.child', verbose_name='получатель')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to='operations.appointment', verbose_name='первичная консультация')),
            ],
            options={
                'verbose_name': 'программа занятий',
                'verbose_name_plural': 'программы занятий',
                'ordering': ['child__last_name', 'starts_on', 'title'],
            },
        ),
        migrations.AddField(
            model_name='programblock',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='operations.treatmentprogram', verbose_name='программа'),
        ),
        migrations.AddConstraint(
            model_name='programblock',
            constraint=models.UniqueConstraint(fields=('program', 'number'), name='unique_program_block_number'),
        ),
    ]
