# Generated by Django 5.2.14 on 2026-06-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_appointment_sequence_number_balanceaccount_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff_availability_override',
            field=models.BooleanField(default=False, verbose_name='назначено вне графика специалиста'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_availability_override_reason',
            field=models.TextField(blank=True, verbose_name='причина назначения вне графика'),
        ),
    ]
