# Generated by Django 5.2.14 on 2026-06-23 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


ACTIVE_STATUSES = ("proposed", "confirmed", "completed", "reserved")


def backfill_room_limits(apps, schema_editor):
    Room = apps.get_model("operations", "Room")
    for room in Room.objects.all():
        capacity = max(room.capacity or 1, 1)
        room.max_staff_count = capacity
        room.max_recipient_count = capacity
        room.allow_group_sessions = capacity > 1
        room.save(update_fields=["max_staff_count", "max_recipient_count", "allow_group_sessions"])


def backfill_representatives_and_appointments(apps, schema_editor):
    Child = apps.get_model("operations", "Child")
    RecipientRepresentative = apps.get_model("operations", "RecipientRepresentative")
    Appointment = apps.get_model("operations", "Appointment")
    AppointmentParticipant = apps.get_model("operations", "AppointmentParticipant")
    AppointmentStaffAssignment = apps.get_model("operations", "AppointmentStaffAssignment")
    LedgerEntry = apps.get_model("operations", "LedgerEntry")

    now = timezone.now()

    representative_links = []
    for child in Child.objects.exclude(primary_parent_id__isnull=True).iterator():
        representative = child.primary_parent
        representative_links.append(
            RecipientRepresentative(
                child_id=child.pk,
                representative_id=child.primary_parent_id,
                relationship_type=representative.relationship_type,
                is_primary=True,
                signs_contract=True,
                receives_schedule=True,
                is_payer=False,
                notes="Создано автоматически из основного представителя.",
                created_at=now,
                updated_at=now,
            )
        )
    RecipientRepresentative.objects.bulk_create(representative_links, ignore_conflicts=True)

    participants = []
    assignments = []
    for appointment in Appointment.objects.select_related("service").iterator():
        participants.append(
            AppointmentParticipant(
                appointment_id=appointment.pk,
                child_id=appointment.child_id,
                attendance_status=appointment.attendance_status,
                billing_decision=appointment.billing_decision,
                billing_account_id=appointment.billing_account_id,
                price_snapshot=appointment.service.default_price if appointment.service_id else None,
                program_block_id=appointment.program_block_id,
                sequence_number=appointment.sequence_number,
                admin_note=appointment.admin_note,
                specialist_note=appointment.specialist_note,
                marked_by_staff_at=appointment.specialist_marked_at,
                starts_at_snapshot=appointment.starts_at,
                ends_at_snapshot=appointment.ends_at,
                appointment_status=appointment.status,
                created_at=now,
                updated_at=now,
            )
        )
        assignments.append(
            AppointmentStaffAssignment(
                appointment_id=appointment.pk,
                staff_member_id=appointment.staff_member_id,
                role="primary",
                starts_at_snapshot=appointment.starts_at,
                ends_at_snapshot=appointment.ends_at,
                appointment_status=appointment.status,
                override_availability=appointment.staff_availability_override,
                override_reason=appointment.staff_availability_override_reason,
                created_at=now,
                updated_at=now,
            )
        )
    AppointmentParticipant.objects.bulk_create(participants, ignore_conflicts=True)
    AppointmentStaffAssignment.objects.bulk_create(assignments, ignore_conflicts=True)

    participant_by_appointment = dict(
        AppointmentParticipant.objects.values_list("appointment_id", "id")
    )
    for entry in LedgerEntry.objects.exclude(appointment_id__isnull=True).iterator():
        participant_id = participant_by_appointment.get(entry.appointment_id)
        if participant_id:
            entry.appointment_participant_id = participant_id
            entry.save(update_fields=["appointment_participant"])


def unbackfill_representatives_and_appointments(apps, schema_editor):
    RecipientRepresentative = apps.get_model("operations", "RecipientRepresentative")
    AppointmentParticipant = apps.get_model("operations", "AppointmentParticipant")
    AppointmentStaffAssignment = apps.get_model("operations", "AppointmentStaffAssignment")
    LedgerEntry = apps.get_model("operations", "LedgerEntry")

    LedgerEntry.objects.update(appointment_participant=None)
    AppointmentStaffAssignment.objects.all().delete()
    AppointmentParticipant.objects.all().delete()
    RecipientRepresentative.objects.filter(notes="Создано автоматически из основного представителя.").delete()


def update_pg_constraints_forward(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
        cursor.execute(
            "ALTER TABLE operations_appointment DROP CONSTRAINT IF EXISTS no_room_overlap_active_appointments"
        )
        for name in (
            "no_child_overlap_active_participants",
            "no_staff_overlap_active_assignments",
        ):
            cursor.execute(f"ALTER TABLE operations_appointmentparticipant DROP CONSTRAINT IF EXISTS {name}")
            cursor.execute(f"ALTER TABLE operations_appointmentstaffassignment DROP CONSTRAINT IF EXISTS {name}")
        cursor.execute(
            """
            ALTER TABLE operations_appointmentparticipant
            ADD CONSTRAINT no_child_overlap_active_participants
            EXCLUDE USING gist (
                child_id WITH =,
                tstzrange(starts_at_snapshot, ends_at_snapshot, '[)') WITH &&
            )
            WHERE (appointment_status IN ('proposed', 'confirmed', 'completed', 'reserved'))
            """
        )
        cursor.execute(
            """
            ALTER TABLE operations_appointmentstaffassignment
            ADD CONSTRAINT no_staff_overlap_active_assignments
            EXCLUDE USING gist (
                staff_member_id WITH =,
                tstzrange(starts_at_snapshot, ends_at_snapshot, '[)') WITH &&
            )
            WHERE (appointment_status IN ('proposed', 'confirmed', 'completed', 'reserved'))
            """
        )


def update_pg_constraints_reverse(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE operations_appointmentparticipant DROP CONSTRAINT IF EXISTS no_child_overlap_active_participants"
        )
        cursor.execute(
            "ALTER TABLE operations_appointmentstaffassignment DROP CONSTRAINT IF EXISTS no_staff_overlap_active_assignments"
        )
        cursor.execute(
            """
            ALTER TABLE operations_appointment
            ADD CONSTRAINT no_room_overlap_active_appointments
            EXCLUDE USING gist (
                room_id WITH =,
                tstzrange(starts_at, ends_at, '[)') WITH &&
            )
            WHERE (room_id IS NOT NULL AND status IN ('proposed', 'confirmed', 'completed', 'reserved'))
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_appointment_staff_availability_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('individual', 'Индивидуальное'), ('group', 'Групповое')], default='individual', max_length=20, verbose_name='тип занятия'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='название группового занятия'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена на момент списания'),
        ),
        migrations.AddField(
            model_name='room',
            name='allow_group_sessions',
            field=models.BooleanField(default=False, verbose_name='разрешены групповые занятия'),
        ),
        migrations.AddField(
            model_name='room',
            name='limit_recipient_count',
            field=models.BooleanField(default=True, verbose_name='ограничивать число получателей'),
        ),
        migrations.AddField(
            model_name='room',
            name='limit_staff_count',
            field=models.BooleanField(default=True, verbose_name='ограничивать число специалистов'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_recipient_count',
            field=models.PositiveIntegerField(default=1, verbose_name='максимум получателей одновременно'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_staff_count',
            field=models.PositiveIntegerField(default=1, verbose_name='максимум специалистов одновременно'),
        ),
        migrations.RunPython(backfill_room_limits, migrations.RunPython.noop),
        migrations.CreateModel(
            name='AppointmentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('attendance_status', models.CharField(choices=[('unknown', 'Не отмечено'), ('attended', 'Пришел'), ('missed', 'Не пришел'), ('excused', 'Уважительная причина')], default='unknown', max_length=30, verbose_name='посещение')),
                ('billing_decision', models.CharField(choices=[('undecided', 'Не решено'), ('charge', 'Списать'), ('do_not_charge', 'Не списывать')], default='undecided', max_length=30, verbose_name='решение по списанию')),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='цена на момент занятия')),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='номер в блоке')),
                ('admin_note', models.TextField(blank=True, verbose_name='заметка администратора')),
                ('specialist_note', models.TextField(blank=True, verbose_name='заметка специалиста')),
                ('marked_by_staff_at', models.DateTimeField(blank=True, null=True, verbose_name='специалист отметил')),
                ('starts_at_snapshot', models.DateTimeField(verbose_name='начало')),
                ('ends_at_snapshot', models.DateTimeField(verbose_name='окончание')),
                ('appointment_status', models.CharField(choices=[('draft', 'Черновик'), ('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Неявка'), ('rescheduled', 'Перенесено'), ('reserved', 'Бронь')], default='confirmed', max_length=30, verbose_name='статус занятия')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='operations.appointment', verbose_name='занятие')),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_participants', to='operations.balanceaccount', verbose_name='счет списания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_participations', to='operations.child', verbose_name='получатель')),
                ('program_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_participants', to='operations.programblock', verbose_name='блок программы')),
                ('source_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='operations.appointmentparticipant', verbose_name='исходный участник')),
            ],
            options={
                'verbose_name': 'участник занятия',
                'verbose_name_plural': 'участники занятий',
                'ordering': ['starts_at_snapshot', 'child__last_name', 'child__first_name'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='appointment_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='operations.appointmentparticipant', verbose_name='участник занятия'),
        ),
        migrations.CreateModel(
            name='AppointmentRoomOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('override_type', models.CharField(choices=[('staff_limit', 'Лимит специалистов'), ('recipient_limit', 'Лимит получателей'), ('exclusive_room', 'Эксклюзивный кабинет'), ('room_inactive', 'Неактивный кабинет'), ('other', 'Другое')], max_length=30, verbose_name='тип разрешения')),
                ('reason', models.TextField(verbose_name='причина')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_overrides', to='operations.appointment', verbose_name='занятие')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_room_overrides', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'разрешение кабинета',
                'verbose_name_plural': 'разрешения кабинетов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('role', models.CharField(choices=[('primary', 'Основной'), ('assistant', 'Ассистент'), ('substitute', 'Замена'), ('observer', 'Наблюдатель')], default='primary', max_length=30, verbose_name='роль')),
                ('starts_at_snapshot', models.DateTimeField(verbose_name='начало')),
                ('ends_at_snapshot', models.DateTimeField(verbose_name='окончание')),
                ('appointment_status', models.CharField(choices=[('draft', 'Черновик'), ('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Неявка'), ('rescheduled', 'Перенесено'), ('reserved', 'Бронь')], default='confirmed', max_length=30, verbose_name='статус занятия')),
                ('override_availability', models.BooleanField(default=False, verbose_name='назначено вне графика')),
                ('override_reason', models.TextField(blank=True, verbose_name='причина назначения вне графика')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='operations.appointment', verbose_name='занятие')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_assignments', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'назначение специалиста',
                'verbose_name_plural': 'назначения специалистов',
                'ordering': ['starts_at_snapshot', 'staff_member__full_name'],
            },
        ),
        migrations.CreateModel(
            name='RecipientRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('relationship_type', models.CharField(choices=[('mother', 'Мать'), ('father', 'Отец'), ('guardian', 'Опекун'), ('grandmother', 'Бабушка'), ('grandfather', 'Дедушка'), ('other', 'Другое')], default='mother', max_length=30, verbose_name='тип связи')),
                ('is_primary', models.BooleanField(default=False, verbose_name='основной представитель')),
                ('signs_contract', models.BooleanField(default=False, verbose_name='подписывает договор')),
                ('receives_schedule', models.BooleanField(default=True, verbose_name='получает расписание')),
                ('is_payer', models.BooleanField(default=False, verbose_name='плательщик')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative_links', to='operations.child', verbose_name='получатель')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='operations.parentguardian', verbose_name='представитель')),
            ],
            options={
                'verbose_name': 'представитель получателя',
                'verbose_name_plural': 'представители получателей',
                'ordering': ['child__last_name', 'child__first_name', '-is_primary', 'representative__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentparticipant',
            index=models.Index(fields=['child', 'starts_at_snapshot', 'ends_at_snapshot'], name='operations__child_i_256c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentparticipant',
            index=models.Index(fields=['appointment', 'appointment_status'], name='operations__appoint_5c93a3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentparticipant',
            index=models.Index(fields=['program_block', 'sequence_number'], name='operations__program_6b9b03_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentparticipant',
            constraint=models.UniqueConstraint(fields=('appointment', 'child'), name='unique_appointment_participant_child'),
        ),
        migrations.AddIndex(
            model_name='appointmentstaffassignment',
            index=models.Index(fields=['staff_member', 'starts_at_snapshot', 'ends_at_snapshot'], name='operations__staff_m_3f5498_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentstaffassignment',
            index=models.Index(fields=['appointment', 'appointment_status'], name='operations__appoint_d6f0cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentstaffassignment',
            constraint=models.UniqueConstraint(fields=('appointment', 'staff_member'), name='unique_appointment_staff_assignment'),
        ),
        migrations.AddIndex(
            model_name='recipientrepresentative',
            index=models.Index(fields=['child', 'receives_schedule'], name='operations__child_i_f26eda_idx'),
        ),
        migrations.AddIndex(
            model_name='recipientrepresentative',
            index=models.Index(fields=['representative', 'receives_schedule'], name='operations__represe_cb77c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipientrepresentative',
            constraint=models.UniqueConstraint(fields=('child', 'representative'), name='unique_recipient_representative'),
        ),
        migrations.AddConstraint(
            model_name='recipientrepresentative',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('child',), name='unique_primary_representative_per_child'),
        ),
        migrations.AddConstraint(
            model_name='recipientrepresentative',
            constraint=models.UniqueConstraint(condition=models.Q(('signs_contract', True)), fields=('child',), name='unique_contract_signer_per_child'),
        ),
        migrations.RunPython(backfill_representatives_and_appointments, unbackfill_representatives_and_appointments),
        migrations.RunPython(update_pg_constraints_forward, update_pg_constraints_reverse),
    ]
