# Generated by Django 5.2.14 on 2026-06-23 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_appointment_session_type_appointment_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCompensationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('rate_type', models.CharField(choices=[('per_session', 'За занятие'), ('hourly', 'За час')], default='per_session', max_length=30, verbose_name='тип ставки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('funding_source', models.ForeignKey(blank=True, help_text='Оставьте пустым для общей ставки; ставка по источнику финансирования приоритетнее.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('service', models.ForeignKey(blank=True, help_text='Оставьте пустым, если ставка действует на все услуги специалиста.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='operations.service', verbose_name='услуга')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_rules', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'правило начисления специалиста',
                'verbose_name_plural': 'правила начисления специалистов',
                'ordering': ['staff_member__full_name', 'service__name', 'funding_source__name', '-starts_on', '-created_at'],
                'indexes': [models.Index(fields=['staff_member', 'is_active', 'starts_on', 'ends_on'], name='operations__staff_m_df00a4_idx'), models.Index(fields=['staff_member', 'service', 'funding_source', 'is_active'], name='operations__staff_m_7e835b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='staff_comp_amount_non_negative'), models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='staff_comp_dates_order')],
            },
        ),
    ]
