# Generated by Django 5.2.14 on 2026-06-23 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_staffcompensationrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingServiceQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('planned_sessions', models.PositiveIntegerField(default=0, verbose_name='план занятий')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_quotas', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_quotas', to='operations.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'квота финансирования по услуге',
                'verbose_name_plural': 'квоты финансирования по услугам',
                'ordering': ['funding_source__name', 'service__name', 'starts_on'],
            },
        ),
        migrations.CreateModel(
            name='FundingStaffAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('allocated_sessions', models.PositiveIntegerField(default=0, verbose_name='выделено занятий')),
                ('session_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стоимость занятия специалисту')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_funding_allocations', to='operations.service', verbose_name='услуга')),
                ('service_quota', models.ForeignKey(blank=True, help_text='Можно оставить пустым, если распределение задаётся сразу как специалист + услуга + количество.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='operations.fundingservicequota', verbose_name='квота услуги')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_allocations', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'распределение квоты по специалисту',
                'verbose_name_plural': 'распределения квот по специалистам',
                'ordering': ['funding_source__name', 'service__name', 'staff_member__full_name', 'starts_on'],
            },
        ),
        migrations.AddIndex(
            model_name='fundingservicequota',
            index=models.Index(fields=['funding_source', 'service', 'starts_on', 'ends_on'], name='operations__funding_52476d_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequota',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='funding_service_quota_dates_order'),
        ),
        migrations.AddIndex(
            model_name='fundingstaffallocation',
            index=models.Index(fields=['funding_source', 'service', 'staff_member'], name='operations__funding_5991c1_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingstaffallocation',
            index=models.Index(fields=['service_quota', 'staff_member'], name='operations__service_544b7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocation',
            constraint=models.CheckConstraint(condition=models.Q(('session_pay_amount__isnull', True), ('session_pay_amount__gte', 0), _connector='OR'), name='funding_staff_alloc_pay_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocation',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='funding_staff_alloc_dates_order'),
        ),
    ]
