# Generated by Django 5.2.14 on 2026-06-23 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_fundingservicequota_fundingstaffallocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('dedupe_key', models.CharField(max_length=160, unique=True, verbose_name='ключ идемпотентности')),
                ('work_date', models.DateField(verbose_name='дата занятия')),
                ('starts_at_snapshot', models.DateTimeField(verbose_name='начало')),
                ('ends_at_snapshot', models.DateTimeField(verbose_name='окончание')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='длительность, мин')),
                ('rate_type_snapshot', models.CharField(choices=[('per_session', 'За занятие'), ('hourly', 'За час')], max_length=30, verbose_name='тип ставки')),
                ('rate_amount_snapshot', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ставка')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма начисления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждено'), ('paid', 'Выплачено'), ('cancelled', 'Отменено')], default='draft', max_length=30, verbose_name='статус')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='утверждено')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='operations.appointment', verbose_name='занятие')),
                ('appointment_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='operations.appointmentparticipant', verbose_name='участник занятия')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_accruals', to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_accruals', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='operations.ledgerentry', verbose_name='проводка списания')),
                ('pay_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='operations.staffcompensationrule', verbose_name='правило начисления')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accruals', to='operations.service', verbose_name='услуга')),
                ('staff_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_accruals', to='operations.appointmentstaffassignment', verbose_name='назначение специалиста')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accruals', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'начисление специалисту',
                'verbose_name_plural': 'начисления специалистам',
                'ordering': ['-work_date', 'staff_member__full_name', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('date_from', models.DateField(verbose_name='дата начала')),
                ('date_to', models.DateField(verbose_name='дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('sent', 'Отправлен'), ('paid', 'Выплачен'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='итого')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='утверждено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_sheets', to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_sheets', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_sheets', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'расчетный лист',
                'verbose_name_plural': 'расчетные листы',
                'ordering': ['-date_to', 'staff_member__full_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSheetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('work_date', models.DateField(verbose_name='дата занятия')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='длительность, мин')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_sheet_lines', to='operations.appointment', verbose_name='занятие')),
                ('payroll_accrual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sheet_lines', to='operations.payrollaccrual', verbose_name='начисление')),
                ('payroll_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='operations.payrollsheet', verbose_name='расчетный лист')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_sheet_lines', to='operations.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'строка расчетного листа',
                'verbose_name_plural': 'строки расчетных листов',
                'ordering': ['work_date', 'service__name'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollaccrual',
            index=models.Index(fields=['staff_member', 'work_date', 'status'], name='operations__staff_m_f23d03_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollaccrual',
            index=models.Index(fields=['appointment', 'staff_assignment'], name='operations__appoint_d19112_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollaccrual',
            index=models.Index(fields=['funding_source', 'service', 'work_date'], name='operations__funding_a9881e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payroll_accrual_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payrollaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('rate_amount_snapshot__gte', 0)), name='payroll_accrual_rate_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payrollsheet',
            index=models.Index(fields=['staff_member', 'date_from', 'date_to', 'status'], name='operations__staff_m_7de06d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollsheet',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='payroll_sheet_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='payrollsheet',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='payroll_sheet_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payrollsheetline',
            index=models.Index(fields=['payroll_sheet', 'work_date'], name='operations__payroll_4a4db0_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollsheetline',
            index=models.Index(fields=['payroll_accrual'], name='operations__payroll_ac72b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollsheetline',
            constraint=models.UniqueConstraint(fields=('payroll_sheet', 'payroll_accrual'), name='unique_payroll_sheet_accrual'),
        ),
        migrations.AddConstraint(
            model_name='payrollsheetline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payroll_sheet_line_amount_non_negative'),
        ),
    ]
