# Generated by Codex on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0014_payrollaccrual_payrollsheet_payrollsheetline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffcompensationrule",
            name="min_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Оставьте пустым, если нижней границы по длительности нет.",
                null=True,
                verbose_name="мин. длительность, мин",
            ),
        ),
        migrations.AddField(
            model_name="staffcompensationrule",
            name="max_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Оставьте пустым, если верхней границы по длительности нет.",
                null=True,
                verbose_name="макс. длительность, мин",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcompensationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_duration_minutes__isnull", True))
                | models.Q(("min_duration_minutes__gte", 1)),
                name="staff_comp_min_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcompensationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_duration_minutes__isnull", True))
                | models.Q(("max_duration_minutes__gte", 1)),
                name="staff_comp_max_duration_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffcompensationrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_duration_minutes__isnull", True))
                | models.Q(("max_duration_minutes__isnull", True))
                | models.Q(("max_duration_minutes__gte", models.F("min_duration_minutes"))),
                name="staff_comp_duration_range_order",
            ),
        ),
    ]
