# Generated by Codex on 2026-06-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0015_staffcompensationrule_duration_bounds"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantRecipientAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                (
                    "allocated_sessions",
                    models.PositiveIntegerField(default=0, verbose_name="выделено занятий"),
                ),
                ("valid_from", models.DateField(blank=True, null=True, verbose_name="действует с")),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="действует до"),
                ),
                ("note", models.TextField(blank=True, verbose_name="примечание")),
                (
                    "balance_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grant_recipient_allocations",
                        to="operations.balanceaccount",
                        verbose_name="счет баланса",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_allocations",
                        to="operations.child",
                        verbose_name="получатель",
                    ),
                ),
                (
                    "funding_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_allocations",
                        to="operations.fundingsource",
                        verbose_name="источник финансирования",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grant_recipient_allocations",
                        to="operations.service",
                        verbose_name="услуга",
                    ),
                ),
            ],
            options={
                "verbose_name": "грантовое выделение получателю",
                "verbose_name_plural": "грантовые выделения получателям",
                "ordering": [
                    "funding_source__name",
                    "service__name",
                    "child__last_name",
                    "valid_from",
                ],
                "indexes": [
                    models.Index(
                        fields=["funding_source", "service", "valid_from", "valid_until"],
                        name="operations__funding_824b4f_idx",
                    ),
                    models.Index(
                        fields=["child", "service"], name="operations__child_i_fadda8_idx"
                    ),
                    models.Index(fields=["balance_account"], name="operations__balance_b2f1c5_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("valid_from__isnull", True))
                        | models.Q(("valid_until__isnull", True))
                        | models.Q(("valid_until__gte", models.F("valid_from"))),
                        name="grant_recipient_alloc_dates_order",
                    ),
                ],
            },
        ),
    ]
