# Generated by Django 5.2.14 on 2026-06-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_grantrecipientallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentconfirmation',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='operations.appointmentparticipant', verbose_name='участник занятия'),
        ),
        migrations.AddField(
            model_name='appointmentconfirmation',
            name='staff_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='operations.appointmentstaffassignment', verbose_name='назначение специалиста'),
        ),
    ]
