# Generated by Django 5.2.14 on 2026-06-30 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_appointment_confirmation_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReschedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готов к проверке'), ('needs_recheck', 'Нужна перепроверка'), ('applied', 'Применен'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('plan_type', models.CharField(choices=[('single_move', 'Перенос занятия'), ('cascade_shift', 'Каскадный сдвиг'), ('staff_absence', 'Отсутствие специалиста'), ('manual', 'Ручной план')], default='single_move', max_length=30, verbose_name='тип плана')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='сводка проверки')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='применено')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='отменено')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_reschedule_plans', to=settings.AUTH_USER_MODEL, verbose_name='применил')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_reschedule_plans', to=settings.AUTH_USER_MODEL, verbose_name='отменил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reschedule_plans', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('root_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_plans', to='operations.appointment', verbose_name='исходное занятие')),
                ('staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_plans', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'план переноса расписания',
                'verbose_name_plural': 'планы переноса расписания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentRescheduleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('position', models.PositiveIntegerField(verbose_name='порядок')),
                ('action_type', models.CharField(choices=[('move', 'Перенести'), ('cancel', 'Отменить'), ('keep', 'Оставить'), ('review_conflict', 'Разобрать конфликт')], default='move', max_length=30, verbose_name='действие')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('valid', 'Проверен'), ('stale', 'Устарел'), ('applied', 'Применен'), ('skipped', 'Пропущен'), ('failed', 'Ошибка')], default='pending', max_length=30, verbose_name='статус')),
                ('proposed_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='предложенное начало')),
                ('proposed_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='предложенное окончание')),
                ('staff_snapshot', models.JSONField(blank=True, default=list, verbose_name='снимок специалистов')),
                ('participant_snapshot', models.JSONField(blank=True, default=list, verbose_name='снимок участников')),
                ('conflict_snapshot', models.JSONField(blank=True, default=dict, verbose_name='снимок конфликтов')),
                ('validation_messages', models.JSONField(blank=True, default=list, verbose_name='сообщения проверки')),
                ('requires_staff_override', models.BooleanField(default=False, verbose_name='требует разрешение выхода вне графика')),
                ('requires_room_override', models.BooleanField(default=False, verbose_name='требует разрешение кабинета')),
                ('admin_note', models.TextField(blank=True, verbose_name='заметка администратора')),
                ('blocking_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking_reschedule_steps', to='operations.appointment', verbose_name='конфликтующее занятие')),
                ('created_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_reschedule_steps', to='operations.appointment', verbose_name='созданное занятие')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='operations.appointmentrescheduleplan', verbose_name='план')),
                ('proposed_primary_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_steps', to='operations.staffmember', verbose_name='предложенный основной специалист')),
                ('proposed_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_steps', to='operations.room', verbose_name='предложенный кабинет')),
                ('source_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_steps', to='operations.appointment', verbose_name='исходное занятие')),
            ],
            options={
                'verbose_name': 'шаг плана переноса',
                'verbose_name_plural': 'шаги плана переноса',
                'ordering': ['plan', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentrescheduleplan',
            index=models.Index(fields=['status', 'created_at'], name='operations__status_794e55_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrescheduleplan',
            index=models.Index(fields=['root_appointment', 'status'], name='operations__root_ap_636c91_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrescheduleplan',
            index=models.Index(fields=['staff_member', 'date_from', 'date_to'], name='operations__staff_m_c058ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrescheduleplan',
            constraint=models.CheckConstraint(condition=models.Q(('date_from__isnull', True), ('date_to__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='reschedule_plan_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrescheduleplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plan_type__in', ['single_move', 'cascade_shift']), _negated=True), ('root_appointment__isnull', False), _connector='OR'), name='reschedule_plan_root_required'),
        ),
        migrations.AddConstraint(
            model_name='appointmentrescheduleplan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('plan_type', 'staff_absence'), _negated=True), ('staff_member__isnull', False), _connector='OR'), name='reschedule_plan_staff_required'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestep',
            index=models.Index(fields=['source_appointment', 'status'], name='operations__source__89e4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestep',
            index=models.Index(fields=['proposed_starts_at', 'proposed_ends_at'], name='operations__propose_77ac1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreschedulestep',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='unique_reschedule_step_position'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreschedulestep',
            constraint=models.CheckConstraint(condition=models.Q(('proposed_starts_at__isnull', True), ('proposed_ends_at__isnull', True), ('proposed_ends_at__gt', models.F('proposed_starts_at')), _connector='OR'), name='reschedule_step_time_order'),
        ),
    ]
