# Generated by Django 5.2.14 on 2026-06-30 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_appointmentrescheduleplan_appointmentreschedulestep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentconfirmation',
            name='reschedule_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='operations.appointmentreschedulestep', verbose_name='шаг плана переноса'),
        ),
        migrations.AddIndex(
            model_name='appointmentconfirmation',
            index=models.Index(fields=['reschedule_step', 'status', 'delivery_status'], name='operations__resched_4fd632_idx'),
        ),
    ]
