# Generated by Django 5.2.14 on 2026-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_appointmentconfirmation_reschedule_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreschedulestep',
            name='confirmation_status',
            field=models.CharField(choices=[('not_requested', 'Не запрошено'), ('waiting', 'Ожидает ответов'), ('approved', 'Согласовано'), ('declined', 'Есть отказ')], default='not_requested', max_length=30, verbose_name='статус согласования'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulestep',
            name='confirmation_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='сводка согласования'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestep',
            index=models.Index(fields=['confirmation_status', 'status'], name='operations__confirm_48c056_idx'),
        ),
    ]
