# Generated by Django 5.2.14 on 2026-07-01 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_appointmentreschedulestep_confirmation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRescheduleStepDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('relation_type', models.CharField(choices=[('frees_target_slot', 'Освобождает целевое окно'), ('must_apply_before', 'Должен примениться раньше')], default='frees_target_slot', max_length=40, verbose_name='тип зависимости')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='снимок')),
            ],
            options={
                'verbose_name': 'зависимость шага переноса',
                'verbose_name_plural': 'зависимости шагов переноса',
                'ordering': ['chain', 'predecessor_step__position', 'successor_step__position'],
            },
        ),
        migrations.AddField(
            model_name='appointmentreschedulestep',
            name='chain_position',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='порядок в цепочке'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulestep',
            name='chain_required',
            field=models.BooleanField(default=False, verbose_name='обязателен в цепочке'),
        ),
        migrations.CreateModel(
            name='AppointmentRescheduleChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('ready', 'Готова'), ('stale', 'Устарела'), ('applying', 'Применяется'), ('applied', 'Применена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='draft', max_length=30, verbose_name='статус')),
                ('apply_policy', models.CharField(choices=[('atomic_all_or_nothing', 'Атомарно все или ничего')], default='atomic_all_or_nothing', max_length=40, verbose_name='правило применения')),
                ('validation_summary', models.JSONField(blank=True, default=dict, verbose_name='сводка проверки')),
                ('admin_note', models.TextField(blank=True, verbose_name='заметка администратора')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='применено')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_reschedule_chains', to=settings.AUTH_USER_MODEL, verbose_name='применил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reschedule_chains', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='operations.appointmentrescheduleplan', verbose_name='план')),
            ],
            options={
                'verbose_name': 'цепочка переноса расписания',
                'verbose_name_plural': 'цепочки переноса расписания',
                'ordering': ['plan', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='appointmentreschedulestep',
            name='chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='operations.appointmentreschedulechain', verbose_name='цепочка'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestep',
            index=models.Index(fields=['chain', 'chain_position'], name='operations__chain_i_688453_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestep',
            index=models.Index(fields=['chain', 'status'], name='operations__chain_i_d68f0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreschedulestep',
            constraint=models.UniqueConstraint(condition=models.Q(('chain__isnull', False)), fields=('chain', 'chain_position'), name='unique_reschedule_step_chain_position'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulestepdependency',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='operations.appointmentreschedulechain', verbose_name='цепочка'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulestepdependency',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_dependencies', to='operations.appointmentrescheduleplan', verbose_name='план'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulestepdependency',
            name='predecessor_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks_successors', to='operations.appointmentreschedulestep', verbose_name='предшествующий шаг'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulestepdependency',
            name='successor_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_edges', to='operations.appointmentreschedulestep', verbose_name='следующий шаг'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulechain',
            index=models.Index(fields=['plan', 'status'], name='operations__plan_id_f90c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulechain',
            index=models.Index(fields=['status', 'updated_at'], name='operations__status_326558_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestepdependency',
            index=models.Index(fields=['chain', 'successor_step'], name='operations__chain_i_4b8cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestepdependency',
            index=models.Index(fields=['chain', 'predecessor_step'], name='operations__chain_i_241977_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentreschedulestepdependency',
            index=models.Index(fields=['relation_type', 'chain'], name='operations__relatio_9882c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreschedulestepdependency',
            constraint=models.UniqueConstraint(fields=('chain', 'predecessor_step', 'successor_step', 'relation_type'), name='unique_reschedule_step_dependency'),
        ),
        migrations.AddConstraint(
            model_name='appointmentreschedulestepdependency',
            constraint=models.CheckConstraint(condition=models.Q(('predecessor_step', models.F('successor_step')), _negated=True), name='reschedule_dependency_not_self'),
        ),
    ]
