# Generated by Django 5.2.14 on 2026-07-14 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_reschedule_chains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIntegrityCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('run_type', models.CharField(choices=[('manual', 'Ручной запуск'), ('scheduled', 'По расписанию'), ('management_command', 'Команда управления'), ('system', 'Системный запуск')], default='manual', max_length=30, verbose_name='тип запуска')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='running', max_length=30, verbose_name='статус')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало проверки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='окончание проверки')),
                ('candidate_count', models.PositiveIntegerField(default=0, verbose_name='проверено занятий')),
                ('issue_count', models.PositiveIntegerField(default=0, verbose_name='всего расхождений')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='ошибок')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='предупреждений')),
                ('info_count', models.PositiveIntegerField(default=0, verbose_name='информационных')),
                ('error_message', models.TextField(blank=True, verbose_name='сообщение ошибки')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_check_runs', to=settings.AUTH_USER_MODEL, verbose_name='запустил')),
            ],
            options={
                'verbose_name': 'запуск финансовой проверки',
                'verbose_name_plural': 'запуски финансовых проверок',
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='FinancialIntegrityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('issue_key', models.CharField(max_length=64, unique=True, verbose_name='ключ расхождения')),
                ('code', models.CharField(max_length=100, verbose_name='код расхождения')),
                ('severity', models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Проверить'), ('info', 'Информация')], max_length=20, verbose_name='важность')),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('acknowledged', 'Принято в работу'), ('resolved', 'Решено'), ('ignored', 'Игнорируется')], default='open', max_length=30, verbose_name='статус')),
                ('first_seen_at', models.DateTimeField(verbose_name='впервые найдено')),
                ('last_seen_at', models.DateTimeField(verbose_name='последний раз найдено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='решено')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('appointment_starts_at', models.DateTimeField(blank=True, null=True, verbose_name='дата занятия')),
                ('appointment_service_name', models.CharField(blank=True, max_length=200, verbose_name='услуга')),
                ('participant_name', models.CharField(blank=True, max_length=240, verbose_name='участник')),
                ('account_label', models.CharField(blank=True, max_length=255, verbose_name='счет')),
                ('funding_source_name', models.CharField(blank=True, max_length=200, verbose_name='источник')),
                ('ledger_entry_type', models.CharField(blank=True, max_length=30, verbose_name='тип ledger')),
                ('ledger_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='сумма ledger')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='данные проверки')),
                ('triage_note', models.TextField(blank=True, verbose_name='заметка разбора')),
                ('triaged_at', models.DateTimeField(blank=True, null=True, verbose_name='разобрано')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_findings', to='operations.balanceaccount', verbose_name='счет')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_findings', to='operations.appointment', verbose_name='занятие')),
                ('appointment_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_findings', to='operations.appointmentparticipant', verbose_name='участник занятия')),
                ('first_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_findings', to='operations.financialintegritycheckrun', verbose_name='первый запуск')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_findings', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_findings', to='operations.financialintegritycheckrun', verbose_name='последний запуск')),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_findings', to='operations.ledgerentry', verbose_name='ledger-проводка')),
                ('resolved_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_findings', to='operations.financialintegritycheckrun', verbose_name='запуск решения')),
                ('triaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_triaged_findings', to=settings.AUTH_USER_MODEL, verbose_name='разобрал')),
            ],
            options={
                'verbose_name': 'финансовое расхождение',
                'verbose_name_plural': 'финансовые расхождения',
                'ordering': ['status', '-last_seen_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='financialintegritycheckrun',
            index=models.Index(fields=['status', 'started_at'], name='operations__status_07136a_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegritycheckrun',
            index=models.Index(fields=['run_type', 'started_at'], name='operations__run_typ_83b70c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegritycheckrun',
            index=models.Index(fields=['-started_at'], name='operations__started_88a700_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegrityfinding',
            index=models.Index(fields=['status', 'severity', '-last_seen_at'], name='operations__status_3565a9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegrityfinding',
            index=models.Index(fields=['code', 'status'], name='operations__code_288920_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegrityfinding',
            index=models.Index(fields=['appointment', 'status'], name='operations__appoint_d036e9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegrityfinding',
            index=models.Index(fields=['account', 'status'], name='operations__account_beb8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='financialintegrityfinding',
            index=models.Index(fields=['funding_source', 'status'], name='operations__funding_83d5ef_idx'),
        ),
    ]
