# Generated by Django 5.2.14 on 2026-07-14 22:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_financialintegritycheckrun_financialintegrityfinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialIntegrityFindingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event_key', models.CharField(max_length=64, unique=True, verbose_name='ключ события')),
                ('event_type', models.CharField(choices=[('created', 'Создано'), ('acknowledged', 'Принято в работу'), ('returned_to_open', 'Возвращено в очередь'), ('ignored', 'Скрыто из очереди'), ('reopened', 'Открыто повторно'), ('resolved', 'Решено'), ('scoped_recheck', 'Точечная перепроверка'), ('note_added', 'Добавлена заметка')], max_length=40, verbose_name='тип события')),
                ('event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время события')),
                ('status_from', models.CharField(blank=True, max_length=30, verbose_name='статус был')),
                ('status_to', models.CharField(blank=True, max_length=30, verbose_name='статус стал')),
                ('severity', models.CharField(blank=True, max_length=20, verbose_name='важность')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='код расхождения')),
                ('issue_key', models.CharField(blank=True, max_length=64, verbose_name='ключ расхождения')),
                ('message', models.TextField(blank=True, verbose_name='сообщение')),
                ('note', models.TextField(blank=True, verbose_name='заметка')),
                ('source_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot источников')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_integrity_events', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='operations.financialintegrityfinding', verbose_name='финансовое расхождение')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_events', to='operations.financialintegritycheckrun', verbose_name='запуск проверки')),
            ],
            options={
                'verbose_name': 'событие финансового расхождения',
                'verbose_name_plural': 'события финансовых расхождений',
                'ordering': ['-event_at', '-pk'],
                'indexes': [models.Index(fields=['finding', '-event_at'], name='operations__finding_f1bdfa_idx'), models.Index(fields=['event_type', '-event_at'], name='operations__event_t_a0e4cd_idx'), models.Index(fields=['run', 'event_type'], name='operations__run_id_a104a4_idx'), models.Index(fields=['code', '-event_at'], name='operations__code_29388f_idx'), models.Index(fields=['status_to', '-event_at'], name='operations__status__ae1125_idx')],
            },
        ),
    ]
