# Generated by Django 5.2.14 on 2026-07-15 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_financialintegrityfindingevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollaccrual',
            name='charged_participants_count_snapshot',
            field=models.PositiveIntegerField(default=1, verbose_name='списано участников'),
        ),
        migrations.AddField(
            model_name='payrollaccrual',
            name='group_pay_policy_snapshot',
            field=models.CharField(choices=[('per_session', 'Один раз за группу'), ('per_charged_participant', 'По списанным участникам'), ('fixed_group_amount', 'Фиксированная сумма за группу')], default='per_session', max_length=40, verbose_name='начисление в группе'),
        ),
        migrations.AddField(
            model_name='payrollaccrual',
            name='pay_units_snapshot',
            field=models.PositiveIntegerField(default=1, verbose_name='единиц начисления'),
        ),
        migrations.AddField(
            model_name='payrollaccrual',
            name='session_scope_snapshot',
            field=models.CharField(choices=[('all', 'Все занятия'), ('individual', 'Индивидуальные'), ('group', 'Групповые')], default='all', max_length=30, verbose_name='формат правила'),
        ),
        migrations.AddField(
            model_name='staffcompensationrule',
            name='group_fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Заполняется только для варианта «Фиксированная сумма за группу».', max_digits=12, null=True, verbose_name='фиксированная сумма за группу'),
        ),
        migrations.AddField(
            model_name='staffcompensationrule',
            name='group_pay_policy',
            field=models.CharField(choices=[('per_session', 'Один раз за группу'), ('per_charged_participant', 'По списанным участникам'), ('fixed_group_amount', 'Фиксированная сумма за группу')], default='per_session', help_text='Для групповых занятий: один раз за группу, по списанным участникам или фиксированной суммой.', max_length=40, verbose_name='начисление в группе'),
        ),
        migrations.AddField(
            model_name='staffcompensationrule',
            name='session_scope',
            field=models.CharField(choices=[('all', 'Все занятия'), ('individual', 'Индивидуальные'), ('group', 'Групповые')], default='all', help_text='Ограничьте ставку индивидуальными или групповыми занятиями, если суммы отличаются.', max_length=30, verbose_name='формат занятий'),
        ),
        migrations.AddIndex(
            model_name='staffcompensationrule',
            index=models.Index(fields=['staff_member', 'session_scope', 'service', 'funding_source', 'is_active'], name='operations__staff_m_b32dc3_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('charged_participants_count_snapshot__gte', 1)), name='payroll_accrual_charged_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='payrollaccrual',
            constraint=models.CheckConstraint(condition=models.Q(('pay_units_snapshot__gte', 1)), name='payroll_accrual_pay_units_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffcompensationrule',
            constraint=models.CheckConstraint(condition=models.Q(('group_fixed_amount__isnull', True), ('group_fixed_amount__gte', 0), _connector='OR'), name='staff_comp_group_fixed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='staffcompensationrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('group_pay_policy', 'fixed_group_amount'), _negated=True), ('group_fixed_amount__isnull', False), _connector='OR'), name='staff_comp_group_fixed_required'),
        ),
    ]
