# Generated by Django 5.2.14 on 2026-07-15 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0024_payrollaccrual_charged_participants_count_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='название')),
                ('expense_type', models.CharField(choices=[('household', 'Хозяйственные расходы'), ('utilities', 'Коммунальные платежи'), ('equipment', 'Оборудование'), ('inventory', 'Инвентарь и материалы'), ('rent', 'Аренда'), ('services', 'Внешние услуги'), ('admin_payroll', 'Административная зарплата'), ('other', 'Прочее')], default='other', max_length=30, verbose_name='тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'категория расхода центра',
                'verbose_name_plural': 'категории расходов центра',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['expense_type', 'is_active'], name='operations__expense_8cc6f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='архивировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('counterparty_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Организация'), ('foundation', 'Фонд'), ('sponsor', 'Спонсор'), ('vendor', 'Поставщик'), ('other', 'Прочее')], default='organization', max_length=30, verbose_name='тип')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН/ОГРНИП')),
                ('legal_address', models.TextField(blank=True, verbose_name='юридический адрес')),
                ('postal_address', models.TextField(blank=True, verbose_name='почтовый адрес')),
                ('bank_details', models.TextField(blank=True, verbose_name='банковские реквизиты')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='контактное лицо')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'контрагент',
                'verbose_name_plural': 'контрагенты',
                'ordering': ['archived_at', 'name'],
                'indexes': [models.Index(fields=['counterparty_type', 'archived_at', 'name'], name='operations__counter_0fdb47_idx')],
            },
        ),
        migrations.CreateModel(
            name='CenterExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата расхода')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('paid', 'Оплачен'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='утверждено')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='оплачено')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='причина отмены')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_center_expenses', to=settings.AUTH_USER_MODEL, verbose_name='утвердил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_center_expenses', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='center_expenses', to='operations.document', verbose_name='документ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='center_expenses', to='operations.centerexpensecategory', verbose_name='категория')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='center_expenses', to='operations.counterparty', verbose_name='контрагент')),
            ],
            options={
                'verbose_name': 'расход центра',
                'verbose_name_plural': 'расходы центра',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseFundingSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_splits', to='operations.centerexpense', verbose_name='расход')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_splits', to='operations.fundingsource', verbose_name='источник финансирования')),
            ],
            options={
                'verbose_name': 'распределение расхода по источнику',
                'verbose_name_plural': 'распределение расходов по источникам',
                'ordering': ['expense_id', 'funding_source__name'],
            },
        ),
        migrations.AddIndex(
            model_name='centerexpense',
            index=models.Index(fields=['expense_date', 'status'], name='operations__expense_2c138f_idx'),
        ),
        migrations.AddIndex(
            model_name='centerexpense',
            index=models.Index(fields=['category', 'expense_date'], name='operations__categor_622ea2_idx'),
        ),
        migrations.AddIndex(
            model_name='centerexpense',
            index=models.Index(fields=['counterparty', 'expense_date'], name='operations__counter_81e2f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='centerexpense',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='center_expense_total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='centerexpense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='center_expense_paid_requires_paid_at'),
        ),
        migrations.AddIndex(
            model_name='expensefundingsplit',
            index=models.Index(fields=['funding_source', 'expense'], name='operations__funding_3e55fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensefundingsplit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_funding_split_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expensefundingsplit',
            constraint=models.UniqueConstraint(fields=('expense', 'funding_source'), name='unique_expense_funding_source'),
        ),
    ]
