# Generated by Django 5.2.14 on 2026-07-15 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0025_centerexpensecategory_counterparty_centerexpense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('asset_type', models.CharField(choices=[('therapy_equipment', 'Реабилитационное оборудование'), ('therapy_tool', 'Инструменты для занятий'), ('furniture', 'Мебель'), ('it', 'ИТ и оргтехника'), ('household', 'Хозяйственный инвентарь'), ('other', 'Прочее')], default='other', max_length=40, verbose_name='тип')),
                ('inventory_number', models.CharField(blank=True, max_length=80, verbose_name='инвентарный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='дата покупки')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стоимость')),
                ('status', models.CharField(choices=[('active', 'В работе'), ('in_repair', 'В ремонте'), ('written_off', 'Списан'), ('lost', 'Утерян'), ('archived', 'Архив')], default='active', max_length=30, verbose_name='статус')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='местонахождение')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('purchase_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_assets', to='operations.centerexpense', verbose_name='расход покупки')),
                ('responsible_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_assets', to='operations.staffmember', verbose_name='ответственный специалист')),
            ],
            options={
                'verbose_name': 'оборудование',
                'verbose_name_plural': 'оборудование',
                'ordering': ['status', 'asset_type', 'name'],
                'indexes': [models.Index(fields=['status', 'asset_type'], name='operations__status_891ce1_idx'), models.Index(fields=['purchase_expense'], name='operations__purchas_c1a0bb_idx'), models.Index(fields=['responsible_staff', 'status'], name='operations__respons_25fdee_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__isnull', True), ('total_amount__gt', 0), _connector='OR'), name='equipment_asset_total_amount_positive_or_null'), models.UniqueConstraint(condition=models.Q(('inventory_number', ''), _negated=True), fields=('inventory_number',), name='unique_non_empty_equipment_inventory_number')],
            },
        ),
    ]
