# Generated by Django 5.2.14 on 2026-07-15 21:04

import django.db.models.deletion
import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0026_equipmentasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('template_type', models.CharField(choices=[('recipient_service', 'Договор с получателем услуг'), ('donation_one_time', 'Разовое пожертвование'), ('donation_monthly', 'Регулярная помощь'), ('sponsor', 'Спонсорский договор'), ('vendor', 'Договор с поставщиком'), ('other', 'Прочее')], default='recipient_service', max_length=40, verbose_name='тип шаблона')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='версия')),
                ('file', models.FileField(blank=True, upload_to=operations.models.contract_template_upload_path, verbose_name='файл шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'шаблон договора',
                'verbose_name_plural': 'шаблоны договоров',
                'ordering': ['template_type', '-is_active', 'title', 'version'],
                'indexes': [models.Index(fields=['template_type', 'is_active'], name='operations__templat_642415_idx')],
            },
        ),
        migrations.CreateModel(
            name='DonationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('contract_type', models.CharField(choices=[('one_time', 'Разовое пожертвование'), ('monthly', 'Регулярная помощь'), ('project', 'Проектный договор'), ('other', 'Прочее')], default='one_time', max_length=30, verbose_name='тип договора')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='номер')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='подписан')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('amount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='лимит суммы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_contracts', to='operations.counterparty', verbose_name='контрагент')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_contracts', to='operations.document', verbose_name='файл договора')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donation_contracts', to='operations.fundingsource', verbose_name='источник финансирования')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_contracts', to='operations.contracttemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'договор пожертвования',
                'verbose_name_plural': 'договоры пожертвования',
                'ordering': ['-signed_on', '-created_at'],
                'indexes': [models.Index(fields=['funding_source', 'status', 'valid_from', 'valid_until'], name='operations__funding_3d409f_idx'), models.Index(fields=['counterparty', 'status'], name='operations__counter_acc427_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_limit__isnull', True), ('amount_limit__gt', 0), _connector='OR'), name='donation_contract_amount_limit_positive_or_null'), models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='donation_contract_dates_order'), models.UniqueConstraint(condition=models.Q(models.Q(('number', ''), _negated=True), ('signed_on__isnull', False)), fields=('contract_type', 'number', 'signed_on'), name='unique_donation_contract_number_signed_on_per_type')],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('contract_type', models.CharField(choices=[('standard', 'Стандартный договор услуг'), ('grant', 'Договор по гранту'), ('certificate', 'Договор по сертификату'), ('other', 'Прочее')], default='standard', max_length=30, verbose_name='тип договора')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='номер')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='подписан')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='operations.child', verbose_name='получатель')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contracts', to='operations.document', verbose_name='файл договора')),
                ('representative_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='operations.recipientrepresentative', verbose_name='подписант')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_contracts', to='operations.contracttemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'договор с получателем',
                'verbose_name_plural': 'договоры с получателями',
                'ordering': ['-signed_on', '-created_at'],
                'indexes': [models.Index(fields=['child', 'status', 'valid_from', 'valid_until'], name='operations__child_i_4109a7_idx'), models.Index(fields=['representative_link', 'status'], name='operations__represe_c0584a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='service_contract_dates_order'), models.UniqueConstraint(condition=models.Q(models.Q(('number', ''), _negated=True), ('signed_on__isnull', False)), fields=('contract_type', 'number', 'signed_on'), name='unique_service_contract_number_signed_on_per_type')],
            },
        ),
    ]
