# Generated by Django 5.2.14 on 2026-07-18 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0027_contracttemplate_donationcontract_servicecontract"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="counterparty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="operations.counterparty",
                verbose_name="контрагент",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("recipient", "Получатель"),
                    ("center", "Центр"),
                    ("counterparty", "Контрагент"),
                    ("contract", "Договор"),
                    ("other", "Прочее"),
                ],
                default="recipient",
                max_length=30,
                verbose_name="цель документа",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="operations.child",
                verbose_name="получатель",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["target_type", "category"], name="operations__target__4816d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["counterparty", "category"], name="operations__counter_be7475_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_type", "recipient"), _negated=True),
                    ("child__isnull", False),
                    _connector="OR",
                ),
                name="document_recipient_target_requires_child",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("target_type", "counterparty"), _negated=True),
                    ("counterparty__isnull", False),
                    _connector="OR",
                ),
                name="document_counterparty_target_requires_counterparty",
            ),
        ),
    ]
