# Generated by Django 5.2.14 on 2026-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0028_document_counterparty_document_target_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterLegalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('full_name', models.CharField(max_length=255, verbose_name='полное наименование')),
                ('short_name', models.CharField(blank=True, max_length=160, verbose_name='краткое наименование')),
                ('director_full_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО руководителя')),
                ('director_short_name', models.CharField(blank=True, max_length=120, verbose_name='ФИО руководителя кратко')),
                ('director_position', models.CharField(blank=True, max_length=120, verbose_name='должность руководителя')),
                ('authority_basis', models.CharField(blank=True, max_length=200, verbose_name='основание полномочий')),
                ('license_number', models.CharField(blank=True, max_length=120, verbose_name='номер лицензии')),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='дата лицензии')),
                ('license_authority', models.CharField(blank=True, max_length=255, verbose_name='кем выдана лицензия')),
                ('ogrn', models.CharField(blank=True, max_length=20, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, verbose_name='КПП')),
                ('legal_address', models.TextField(blank=True, verbose_name='юридический адрес')),
                ('location_address', models.TextField(blank=True, verbose_name='адрес места оказания услуг')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('site', models.CharField(blank=True, max_length=160, verbose_name='сайт')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='банк')),
                ('bank_bik', models.CharField(blank=True, max_length=20, verbose_name='БИК')),
                ('bank_account', models.CharField(blank=True, max_length=40, verbose_name='расчетный счет')),
                ('bank_corr_account', models.CharField(blank=True, max_length=40, verbose_name='корреспондентский счет')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный профиль')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'юридический профиль центра',
                'verbose_name_plural': 'юридические профили центра',
                'ordering': ['-is_active', '-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_center_legal_profile')],
            },
        ),
    ]
