# Generated by Django 5.2.14 on 2026-07-18 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0029_centerlegalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLegalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('contract_kind', models.CharField(choices=[('service', 'Договор с получателем'), ('donation', 'Договор пожертвования')], max_length=30, verbose_name='тип договора')),
                ('contract_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные договора')),
                ('center_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные центра')),
                ('recipient_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные получателя')),
                ('representative_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные представителя')),
                ('counterparty_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные контрагента')),
                ('funding_source_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные источника финансирования')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные шаблона')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_legal_snapshot', to='operations.document', verbose_name='файл договора')),
                ('donation_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_snapshots', to='operations.donationcontract', verbose_name='договор пожертвования')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contract_legal_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='сформировал')),
                ('service_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_snapshots', to='operations.servicecontract', verbose_name='договор с получателем')),
            ],
            options={
                'verbose_name': 'юридический снимок договора',
                'verbose_name_plural': 'юридические снимки договоров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract_kind', '-created_at'], name='operations__contrac_b2df29_idx'), models.Index(fields=['service_contract', '-created_at'], name='operations__service_69d786_idx'), models.Index(fields=['donation_contract', '-created_at'], name='operations__donatio_51fc2f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('contract_kind', 'service'), ('donation_contract__isnull', True), ('service_contract__isnull', False)), models.Q(('contract_kind', 'donation'), ('donation_contract__isnull', False), ('service_contract__isnull', True)), _connector='OR'), name='contract_snapshot_matches_contract_kind')],
            },
        ),
    ]
