# Generated by Django 5.2.14 on 2026-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0030_contractlegalsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='template_type',
            field=models.CharField(choices=[('recipient_service', 'Договор с получателем услуг'), ('recipient_free_service', 'Безвозмездные услуги получателю'), ('recipient_care', 'Присмотр и уход'), ('recipient_certificate', 'Материнский капитал / сертификат'), ('donation_one_time', 'Разовое пожертвование'), ('donation_monthly', 'Регулярная помощь'), ('donation_project', 'Проектное пожертвование'), ('sponsor', 'Спонсорский договор'), ('organization_service', 'B2B-договор услуг организации'), ('vendor', 'Договор с поставщиком'), ('consent_photo_video', 'Согласие на фото/видео'), ('act', 'Акт'), ('other', 'Прочее')], default='recipient_service', max_length=40, verbose_name='тип шаблона'),
        ),
    ]
