# Generated by Django 5.2.14 on 2026-07-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0031_alter_contracttemplate_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='адрес регистрации'),
        ),
        migrations.AddField(
            model_name='child',
            name='residential_address',
            field=models.TextField(blank=True, verbose_name='адрес проживания'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='passport_issued_by',
            field=models.TextField(blank=True, verbose_name='кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='passport_issued_on',
            field=models.DateField(blank=True, null=True, verbose_name='дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='номер паспорта'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='passport_series',
            field=models.CharField(blank=True, max_length=20, verbose_name='серия паспорта'),
        ),
        migrations.AddField(
            model_name='parentguardian',
            name='registration_address',
            field=models.TextField(blank=True, verbose_name='адрес регистрации'),
        ),
    ]
