# Generated by Django 5.2.14 on 2026-07-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0032_child_registration_address_child_residential_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('service_name', models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название услуги.', max_length=240, verbose_name='наименование услуги в договоре')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='количество')),
                ('unit', models.CharField(choices=[('session', 'занятие'), ('hour', 'час'), ('course', 'курс'), ('month', 'месяц'), ('other', 'другое')], default='session', max_length=20, verbose_name='единица')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена за единицу')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='период с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='период по')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'строка спецификации договора',
                'verbose_name_plural': 'строки спецификации договора',
                'ordering': ['service_contract', 'sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='servicecontract',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='operations.fundingsource', verbose_name='источник финансирования'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['funding_source', 'status', 'valid_from', 'valid_until'], name='operations__funding_f66ea5_idx'),
        ),
        migrations.AddField(
            model_name='servicecontractline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_lines', to='operations.service', verbose_name='услуга'),
        ),
        migrations.AddField(
            model_name='servicecontractline',
            name='service_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='operations.servicecontract', verbose_name='договор'),
        ),
        migrations.AddIndex(
            model_name='servicecontractline',
            index=models.Index(fields=['service_contract', 'sort_order'], name='operations__service_33041e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontractline',
            index=models.Index(fields=['service', 'unit'], name='operations__service_f61d52_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecontractline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='service_contract_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='servicecontractline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='service_contract_line_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='servicecontractline',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='service_contract_line_dates_order'),
        ),
    ]
