# Generated by Django 5.2.14 on 2026-07-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0033_servicecontractline_servicecontract_funding_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontract',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='operations.certificate', verbose_name='сертификат'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['certificate', 'status'], name='operations__certifi_fb38d7_idx'),
        ),
    ]
