# Generated by Django 5.2.14 on 2026-07-18 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0035_contractsignedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('contract_type', models.CharField(choices=[('standard', 'Договор оказания услуг организации'), ('project', 'Проектный договор услуг'), ('other', 'Прочее')], default='standard', max_length=30, verbose_name='тип договора')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='номер')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='подписан')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='действует до')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'B2B-договор оказания услуг',
                'verbose_name_plural': 'B2B-договоры оказания услуг',
                'ordering': ['-signed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationServiceContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('service_name', models.CharField(blank=True, help_text='Если оставить пустым, будет использовано название услуги.', max_length=240, verbose_name='наименование услуги в договоре')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='количество')),
                ('unit', models.CharField(choices=[('session', 'занятие'), ('hour', 'час'), ('course', 'курс'), ('month', 'месяц'), ('other', 'другое')], default='session', max_length=20, verbose_name='единица')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='цена за единицу')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='период с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='период по')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
            ],
            options={
                'verbose_name': 'строка спецификации B2B-договора',
                'verbose_name_plural': 'строки спецификации B2B-договора',
                'ordering': ['organization_contract', 'sort_order', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='contractlegalsnapshot',
            name='contract_snapshot_matches_contract_kind',
        ),
        migrations.RemoveConstraint(
            model_name='contractsignedfile',
            name='contract_signed_file_matches_contract_kind',
        ),
        migrations.AlterField(
            model_name='contractlegalsnapshot',
            name='contract_kind',
            field=models.CharField(choices=[('service', 'Договор с получателем'), ('donation', 'Договор пожертвования'), ('organization_service', 'B2B-договор услуг организации')], max_length=30, verbose_name='тип договора'),
        ),
        migrations.AlterField(
            model_name='contractsignedfile',
            name='contract_kind',
            field=models.CharField(choices=[('service', 'Договор с получателем'), ('donation', 'Договор пожертвования'), ('organization_service', 'B2B-договор услуг организации')], max_length=30, verbose_name='тип договора'),
        ),
        migrations.AddField(
            model_name='organizationservicecontract',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_service_contracts', to='operations.counterparty', verbose_name='организация'),
        ),
        migrations.AddField(
            model_name='organizationservicecontract',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_service_contracts', to='operations.document', verbose_name='файл договора'),
        ),
        migrations.AddField(
            model_name='organizationservicecontract',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_service_contracts', to='operations.fundingsource', verbose_name='источник финансирования'),
        ),
        migrations.AddField(
            model_name='organizationservicecontract',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_service_contracts', to='operations.contracttemplate', verbose_name='шаблон'),
        ),
        migrations.AddField(
            model_name='contractlegalsnapshot',
            name='organization_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_snapshots', to='operations.organizationservicecontract', verbose_name='B2B-договор услуг организации'),
        ),
        migrations.AddField(
            model_name='contractsignedfile',
            name='organization_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_files', to='operations.organizationservicecontract', verbose_name='B2B-договор услуг организации'),
        ),
        migrations.AddIndex(
            model_name='contractlegalsnapshot',
            index=models.Index(fields=['organization_contract', '-created_at'], name='operations__organiz_7b5459_idx'),
        ),
        migrations.AddIndex(
            model_name='contractsignedfile',
            index=models.Index(fields=['organization_contract', 'status', '-signed_on'], name='operations__organiz_35a897_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractlegalsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_kind', 'service'), ('donation_contract__isnull', True), ('organization_contract__isnull', True), ('service_contract__isnull', False)), models.Q(('contract_kind', 'donation'), ('donation_contract__isnull', False), ('organization_contract__isnull', True), ('service_contract__isnull', True)), models.Q(('contract_kind', 'organization_service'), ('donation_contract__isnull', True), ('organization_contract__isnull', False), ('service_contract__isnull', True)), _connector='OR'), name='contract_snapshot_matches_contract_kind'),
        ),
        migrations.AddConstraint(
            model_name='contractsignedfile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contract_kind', 'service'), ('donation_contract__isnull', True), ('organization_contract__isnull', True), ('service_contract__isnull', False)), models.Q(('contract_kind', 'donation'), ('donation_contract__isnull', False), ('organization_contract__isnull', True), ('service_contract__isnull', True)), models.Q(('contract_kind', 'organization_service'), ('donation_contract__isnull', True), ('organization_contract__isnull', False), ('service_contract__isnull', True)), _connector='OR'), name='contract_signed_file_matches_contract_kind'),
        ),
        migrations.AddField(
            model_name='organizationservicecontractline',
            name='organization_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='operations.organizationservicecontract', verbose_name='B2B-договор'),
        ),
        migrations.AddField(
            model_name='organizationservicecontractline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_contract_lines', to='operations.service', verbose_name='услуга'),
        ),
        migrations.AddIndex(
            model_name='organizationservicecontract',
            index=models.Index(fields=['counterparty', 'status', 'valid_from', 'valid_until'], name='operations__counter_40f99f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationservicecontract',
            index=models.Index(fields=['funding_source', 'status', 'valid_from', 'valid_until'], name='operations__funding_ab6675_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationservicecontract',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='organization_service_contract_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='organizationservicecontract',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('number', ''), _negated=True), ('signed_on__isnull', False)), fields=('contract_type', 'number', 'signed_on'), name='unique_organization_service_contract_number_signed_on_per_type'),
        ),
        migrations.AddIndex(
            model_name='organizationservicecontractline',
            index=models.Index(fields=['organization_contract', 'sort_order'], name='operations__organiz_e37a01_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationservicecontractline',
            index=models.Index(fields=['service', 'unit'], name='operations__service_e2e6f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationservicecontractline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='organization_contract_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='organizationservicecontractline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='organization_contract_line_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='organizationservicecontractline',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='organization_contract_line_dates_order'),
        ),
    ]
