# Generated by Django 5.2.14 on 2026-07-18 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0036_organizationservicecontract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='signatory_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_consents', to='operations.recipientrepresentative', verbose_name='подписант'),
        ),
        migrations.AddField(
            model_name='consent',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents', to='operations.contracttemplate', verbose_name='шаблон'),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['template', 'consent_type'], name='operations__templat_695cb5_idx'),
        ),
    ]
