# Generated by Django 5.2.14 on 2026-07-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0037_consent_signatory_representative_consent_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('medical_report', 'Медицинское заключение'), ('consent', 'Согласие'), ('ipr', 'ИПР / ИПРА'), ('contract', 'Договор'), ('act', 'Акт'), ('other', 'Прочее')], default='other', max_length=30, verbose_name='категория'),
        ),
        migrations.CreateModel(
            name='ContractAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('act_kind', models.CharField(choices=[('service', 'Акт к договору с получателем'), ('organization_service', 'Акт к B2B-договору услуг')], max_length=30, verbose_name='тип акта')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='номер акта')),
                ('act_on', models.DateField(blank=True, null=True, verbose_name='дата акта')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='период с')),
                ('period_until', models.DateField(blank=True, null=True, verbose_name='период по')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='сумма акта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Сформирован'), ('signed', 'Подписан'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус')),
                ('act_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные акта')),
                ('contract_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные договора')),
                ('center_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные центра')),
                ('recipient_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные получателя')),
                ('representative_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные представителя')),
                ('counterparty_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные контрагента')),
                ('funding_source_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные источника финансирования')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные шаблона')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_acts', to='operations.document', verbose_name='файл акта')),
                ('organization_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='operations.organizationservicecontract', verbose_name='B2B-договор услуг организации')),
                ('service_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='operations.servicecontract', verbose_name='договор с получателем')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_acts', to='operations.contracttemplate', verbose_name='шаблон')),
            ],
            options={
                'verbose_name': 'акт оказанных услуг',
                'verbose_name_plural': 'акты оказанных услуг',
                'ordering': ['-act_on', '-created_at'],
                'indexes': [models.Index(fields=['act_kind', 'status', '-act_on'], name='operations__act_kin_ad792a_idx'), models.Index(fields=['service_contract', 'status', '-act_on'], name='operations__service_0cc03e_idx'), models.Index(fields=['organization_contract', 'status', '-act_on'], name='operations__organiz_1ca44a_idx'), models.Index(fields=['template', 'status'], name='operations__templat_4b72b9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='contract_act_amount_positive_or_null'), models.CheckConstraint(condition=models.Q(('period_from__isnull', True), ('period_until__isnull', True), ('period_until__gte', models.F('period_from')), _connector='OR'), name='contract_act_period_dates_order'), models.CheckConstraint(condition=models.Q(models.Q(('act_kind', 'service'), ('organization_contract__isnull', True), ('service_contract__isnull', False)), models.Q(('act_kind', 'organization_service'), ('organization_contract__isnull', False), ('service_contract__isnull', True)), _connector='OR'), name='contract_act_matches_contract_kind'), models.UniqueConstraint(condition=models.Q(models.Q(('number', ''), _negated=True), ('act_on__isnull', False)), fields=('act_kind', 'number', 'act_on'), name='unique_contract_act_number_act_on_per_kind')],
            },
        ),
    ]
