# Generated by Django 5.2.14 on 2026-07-19 00:52

import django.db.models.deletion
import django.utils.timezone
import operations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0039_contractactsignedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentSignedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('file', models.FileField(upload_to=operations.models.consent_signed_file_upload_path, verbose_name='архивный файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='исходное имя файла')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='тип содержимого')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='размер файла')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('signed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата подписания')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('void', 'Аннулирован')], default='active', max_length=20, verbose_name='статус')),
                ('void_reason', models.TextField(blank=True, verbose_name='причина аннулирования')),
                ('consent_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные согласия')),
                ('center_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные центра')),
                ('recipient_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные получателя')),
                ('representative_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные представителя')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, verbose_name='данные шаблона')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signed_files', to='operations.consent', verbose_name='согласие')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_signed_files', to='operations.document', verbose_name='исходный файл согласия')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_consent_signed_files', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'архивный подписанный файл согласия',
                'verbose_name_plural': 'архивные подписанные файлы согласий',
                'ordering': ['-signed_on', '-created_at'],
                'indexes': [models.Index(fields=['consent', 'status', '-signed_on'], name='operations__consent_235b46_idx'), models.Index(fields=['status', '-signed_on'], name='operations__status_9f8277_idx'), models.Index(fields=['file_sha256'], name='operations__file_sh_499463_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file_size__gt', 0)), name='consent_signed_file_size_positive')],
            },
        ),
    ]
