# Generated by Django 5.2.14 on 2026-07-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0040_consentsignedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='operations.fundingsource', verbose_name='источник финансирования'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='плательщик по сертификату'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='payer_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payer_certificates', to='operations.recipientrepresentative', verbose_name='представитель-плательщик'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['child', 'certificate_type'], name='operations__child_i_2403a8_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['funding_source', 'certificate_type'], name='operations__funding_e7a442_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['payer_representative'], name='operations__payer_r_9005c6_idx'),
        ),
    ]
