# Generated by Django 5.2.14 on 2026-07-19 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0041_certificate_funding_source_certificate_payer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('import_kind', models.CharField(choices=[('certificates', 'Сертификаты')], max_length=40, verbose_name='тип импорта')),
                ('status', models.CharField(choices=[('previewed', 'Проверен'), ('applying', 'Применяется'), ('applied', 'Применен'), ('partially_applied', 'Применен частично'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='previewed', max_length=40, verbose_name='статус')),
                ('original_filename', models.CharField(max_length=255, verbose_name='исходное имя файла')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='SHA-256 файла')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='применено')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='строк всего')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='валидных строк')),
                ('invalid_rows', models.PositiveIntegerField(default=0, verbose_name='ошибочных строк')),
                ('warning_rows', models.PositiveIntegerField(default=0, verbose_name='строк с предупреждениями')),
                ('applied_rows', models.PositiveIntegerField(default=0, verbose_name='примененных строк')),
                ('skipped_rows', models.PositiveIntegerField(default=0, verbose_name='пропущенных строк')),
                ('header_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot заголовков')),
                ('error_summary', models.JSONField(blank=True, default=dict, verbose_name='сводка ошибок')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='применил')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='загрузил')),
            ],
            options={
                'verbose_name': 'пакет импорта',
                'verbose_name_plural': 'пакеты импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatchRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('row_number', models.PositiveIntegerField(verbose_name='номер строки')),
                ('status', models.CharField(choices=[('valid', 'Готова'), ('invalid', 'Ошибка'), ('applied', 'Применена'), ('skipped', 'Пропущена'), ('failed', 'Сбой')], max_length=30, verbose_name='статус')),
                ('raw_values', models.JSONField(blank=True, default=dict, verbose_name='значения строки')),
                ('normalized_values', models.JSONField(blank=True, default=dict, verbose_name='нормализованные значения')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='ошибки')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='предупреждения')),
                ('target_model', models.CharField(blank=True, max_length=120, verbose_name='целевая модель')),
                ('target_pk', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID целевой записи')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='применено')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='operations.importbatch', verbose_name='пакет импорта')),
            ],
            options={
                'verbose_name': 'строка пакета импорта',
                'verbose_name_plural': 'строки пакетов импорта',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['import_kind', 'status', 'created_at'], name='operations__import__3fd592_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='operations__uploade_7536ec_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['source_sha256'], name='operations__source__485773_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatchrow',
            index=models.Index(fields=['batch', 'status'], name='operations__batch_i_1b5b61_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatchrow',
            index=models.Index(fields=['target_model', 'target_pk'], name='operations__target__454797_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatchrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_import_batch_row_number'),
        ),
    ]
