# Generated by Django 5.2.14 on 2026-07-19 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0042_importbatch_importbatchrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='balance_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='operations.balanceaccount', verbose_name='счет баланса'),
        ),
    ]
