# Generated by Django 5.2.14 on 2026-07-24 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0043_certificate_balance_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentConfirmationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('decision', models.CharField(choices=[('confirmed', 'Подтвердить'), ('declined', 'Отклонить')], max_length=30, verbose_name='решение')),
                ('source', models.CharField(choices=[('specialist_response', 'Ответ специалиста'), ('representative_response', 'Ответ представителя'), ('recipient_response', 'Ответ получателя'), ('administrator_manual', 'Ручное решение администратора'), ('director_manual', 'Ручное решение руководителя')], max_length=40, verbose_name='источник решения')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор'), ('specialist', 'Специалист'), ('representative', 'Представитель'), ('recipient', 'Получатель')], max_length=30, verbose_name='роль на момент решения')),
                ('note', models.TextField(blank=True, verbose_name='основание или комментарий')),
                ('is_current', models.BooleanField(default=True, verbose_name='текущее решение')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_confirmation_decisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал')),
                ('confirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_history', to='operations.appointmentconfirmation', verbose_name='согласование')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='operations.appointmentconfirmationdecision', verbose_name='переопределяет решение')),
            ],
            options={
                'verbose_name': 'решение по согласованию',
                'verbose_name_plural': 'решения по согласованиям',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['confirmation', 'is_current', 'created_at'], name='operations__confirm_373192_idx'), models.Index(fields=['source', 'created_at'], name='operations__source_8b5ee8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('confirmation',), name='unique_current_confirmation_decision'), models.CheckConstraint(condition=models.Q(models.Q(('source__in', ['administrator_manual', 'director_manual']), _negated=True), ('actor__isnull', False), _connector='OR'), name='confirmation_manual_decision_actor_required'), models.CheckConstraint(condition=models.Q(models.Q(('source__in', ['administrator_manual', 'director_manual']), _negated=True), models.Q(('note', ''), _negated=True), _connector='OR'), name='confirmation_manual_decision_note_required'), models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot', 'specialist'), ('source', 'specialist_response')), models.Q(('actor_role_snapshot', 'representative'), ('source', 'representative_response')), models.Q(('actor_role_snapshot', 'recipient'), ('source', 'recipient_response')), models.Q(('actor_role_snapshot', 'administrator'), ('source', 'administrator_manual')), models.Q(('actor_role_snapshot', 'director'), ('source', 'director_manual')), _connector='OR'), name='confirmation_decision_source_role_match')],
            },
        ),
    ]
