# Generated by Django 5.2.14 on 2026-07-24 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0044_appointment_confirmation_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentconfirmationdecision',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.appointmentconfirmationdecision', verbose_name='переопределяет решение'),
        ),
        migrations.CreateModel(
            name='TimeOffRequestDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('decision', models.CharField(choices=[('approved', 'Согласовать'), ('rejected', 'Отклонить')], max_length=30, verbose_name='решение')),
                ('source', models.CharField(choices=[('administrator_manual', 'Решение администратора'), ('director_manual', 'Решение руководителя')], max_length=40, verbose_name='источник решения')),
                ('actor_role_snapshot', models.CharField(choices=[('administrator', 'Администратор'), ('director', 'Руководитель')], max_length=30, verbose_name='роль на момент решения')),
                ('note', models.TextField(verbose_name='основание решения')),
                ('director_priority', models.BooleanField(default=False, verbose_name='область приоритета руководителя')),
                ('is_current', models.BooleanField(default=True, verbose_name='текущее решение')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_off_request_decisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.timeoffrequestdecision', verbose_name='переопределяет решение')),
                ('time_off_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_history', to='operations.timeoffrequest', verbose_name='заявка специалиста')),
            ],
            options={
                'verbose_name': 'решение по заявке специалиста',
                'verbose_name_plural': 'решения по заявкам специалистов',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['time_off_request', 'is_current', 'created_at'], name='operations__time_of_c10d91_idx'), models.Index(fields=['source', 'created_at'], name='operations__source_f87aa1_idx'), models.Index(fields=['director_priority', 'is_current', 'created_at'], name='operations__directo_869a6c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('time_off_request',), name='unique_current_time_off_decision'), models.CheckConstraint(condition=models.Q(('note', ''), _negated=True), name='time_off_decision_note_required'), models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot', 'administrator'), ('source', 'administrator_manual')), models.Q(('actor_role_snapshot', 'director'), ('source', 'director_manual')), _connector='OR'), name='time_off_decision_source_role_match')],
            },
        ),
    ]
