# Generated by Django 5.2.14 on 2026-07-25 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0045_time_off_request_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollsheet',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('sent', 'Передан в выплату'), ('paid', 'Выплачен'), ('cancelled', 'Отменен')], default='draft', max_length=30, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='PayrollPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма выплаты')),
                ('method', models.CharField(choices=[('bank_transfer', 'Банковский перевод'), ('cash', 'Наличные'), ('other', 'Другое')], max_length=30, verbose_name='способ выплаты')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата выплаты')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='номер платежа / документа')),
                ('note', models.TextField(blank=True, verbose_name='комментарий')),
                ('payroll_sheet', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='operations.payrollsheet', verbose_name='расчетный лист')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payroll_payouts', to=settings.AUTH_USER_MODEL, verbose_name='выплату зафиксировал')),
            ],
            options={
                'verbose_name': 'выплата специалисту',
                'verbose_name_plural': 'выплаты специалистам',
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['-paid_at'], name='operations__paid_at_a22e15_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payroll_payout_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='PayrollSheetLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event_type', models.CharField(choices=[('sent', 'Передан в выплату'), ('paid', 'Выплата зафиксирована')], max_length=30, verbose_name='тип события')),
                ('status_from', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('sent', 'Передан в выплату'), ('paid', 'Выплачен'), ('cancelled', 'Отменен')], max_length=30, verbose_name='статус был')),
                ('status_to', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утвержден'), ('sent', 'Передан в выплату'), ('paid', 'Выплачен'), ('cancelled', 'Отменен')], max_length=30, verbose_name='статус стал')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель')], max_length=30, verbose_name='роль на момент действия')),
                ('note', models.TextField(blank=True, verbose_name='основание')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время действия')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_sheet_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='действие выполнил')),
                ('payroll_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='operations.payrollsheet', verbose_name='расчетный лист')),
            ],
            options={
                'verbose_name': 'событие расчетного листа',
                'verbose_name_plural': 'события расчетных листов',
                'ordering': ['-occurred_at', '-pk'],
                'indexes': [models.Index(fields=['payroll_sheet', '-occurred_at'], name='operations__payroll_bdc95f_idx'), models.Index(fields=['event_type', '-occurred_at'], name='operations__event_t_3f72b0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot', 'director'), ('event_type', 'sent'), ('status_from', 'approved'), ('status_to', 'sent')), models.Q(('actor_role_snapshot', 'director'), ('event_type', 'paid'), ('status_from', 'sent'), ('status_to', 'paid')), _connector='OR'), name='payroll_lifecycle_event_valid_transition'), models.CheckConstraint(condition=models.Q(('event_type', 'paid'), models.Q(('note', ''), _negated=True), _connector='OR'), name='payroll_sent_event_note_required')],
            },
        ),
    ]
