# Generated by Django 5.2.14 on 2026-07-25 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0046_payroll_payout_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='transfer_side',
            field=models.CharField(blank=True, choices=[('debit', 'Списание'), ('credit', 'Пополнение')], max_length=10, null=True, verbose_name='сторона переноса'),
        ),
        migrations.CreateModel(
            name='BalanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('operation_kind', models.CharField(choices=[('direct', 'Перенос в одинаковых единицах'), ('money_to_sessions', 'Конвертация рублей в занятия')], max_length=30, verbose_name='вид операции')),
                ('amount_from', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='списано')),
                ('amount_to', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='зачислено')),
                ('from_unit_snapshot', models.CharField(choices=[('sessions', 'Занятия'), ('money', 'Рубли')], max_length=20, verbose_name='единица исходного счета на момент операции')),
                ('to_unit_snapshot', models.CharField(choices=[('sessions', 'Занятия'), ('money', 'Рубли')], max_length=20, verbose_name='единица целевого счета на момент операции')),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='курс конвертации')),
                ('reason', models.TextField(verbose_name='основание')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ключ идемпотентности')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_balance_transfers', to=settings.AUTH_USER_MODEL, verbose_name='операцию создал')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_balance_transfers', to='operations.balanceaccount', verbose_name='исходный счет')),
                ('program_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balance_transfers', to='operations.programblock', verbose_name='каскад программы')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_balance_transfers', to='operations.balanceaccount', verbose_name='целевой счет')),
            ],
            options={
                'verbose_name': 'операция переноса баланса',
                'verbose_name_plural': 'операции переноса балансов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='balance_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='operations.balancetransfer', verbose_name='операция переноса'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['balance_transfer', 'transfer_side'], name='operations__balance_2ed413_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('balance_transfer__isnull', True), ('transfer_side__isnull', True)), models.Q(('amount__lt', 0), ('balance_transfer__isnull', False), ('entry_type', 'transfer'), ('transfer_side', 'debit')), models.Q(('amount__gt', 0), ('balance_transfer__isnull', False), ('entry_type', 'transfer'), ('transfer_side', 'credit')), _connector='OR'), name='ledger_transfer_link_matches_entry'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('balance_transfer__isnull', False)), fields=('balance_transfer', 'transfer_side'), name='unique_balance_transfer_ledger_side'),
        ),
        migrations.AddIndex(
            model_name='balancetransfer',
            index=models.Index(fields=['from_account', '-created_at'], name='operations__from_ac_20dcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransfer',
            index=models.Index(fields=['to_account', '-created_at'], name='operations__to_acco_d08cff_idx'),
        ),
        migrations.AddIndex(
            model_name='balancetransfer',
            index=models.Index(fields=['program_block', '-created_at'], name='operations__program_afcf00_idx'),
        ),
        migrations.AddConstraint(
            model_name='balancetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='balance_transfer_accounts_differ'),
        ),
        migrations.AddConstraint(
            model_name='balancetransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount_from__gt', 0), ('amount_to__gt', 0)), name='balance_transfer_amounts_positive'),
        ),
        migrations.AddConstraint(
            model_name='balancetransfer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_from', models.F('amount_to')), ('conversion_rate__isnull', True), ('from_unit_snapshot', models.F('to_unit_snapshot')), ('operation_kind', 'direct')), models.Q(('conversion_rate__gt', 0), ('from_unit_snapshot', 'money'), ('operation_kind', 'money_to_sessions'), ('to_unit_snapshot', 'sessions')), _connector='OR'), name='balance_transfer_kind_snapshot_rules'),
        ),
    ]
