# Generated by Django 5.2.14 on 2026-07-26 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _batches(queryset, *, batch_size=500):
    batch = []
    for item in queryset.iterator(chunk_size=batch_size):
        batch.append(item)
        if len(batch) == batch_size:
            yield batch
            batch = []
    if batch:
        yield batch


def backfill_grant_plan_revisions(apps, schema_editor):
    FundingServiceQuota = apps.get_model("operations", "FundingServiceQuota")
    FundingServiceQuotaRevision = apps.get_model(
        "operations", "FundingServiceQuotaRevision"
    )
    FundingStaffAllocation = apps.get_model("operations", "FundingStaffAllocation")
    FundingStaffAllocationRevision = apps.get_model(
        "operations", "FundingStaffAllocationRevision"
    )

    for quotas in _batches(FundingServiceQuota.objects.order_by("pk")):
        FundingServiceQuotaRevision.objects.bulk_create(
            [
                FundingServiceQuotaRevision(
                    service_quota_id=quota.pk,
                    revision_number=1,
                    event_type="legacy_import",
                    planned_sessions=quota.planned_sessions,
                    starts_on=quota.starts_on,
                    ends_on=quota.ends_on,
                    note=quota.note,
                    lifecycle_status=quota.lifecycle_status,
                    actor_id=None,
                    actor_role_snapshot="legacy",
                    reason=(
                        "Перенос существующей строки; "
                        "автор исходного решения неизвестен."
                    ),
                    supersedes_id=None,
                    decided_at=None,
                )
                for quota in quotas
            ],
            batch_size=500,
        )
        revisions = {
            revision.service_quota_id: revision.pk
            for revision in FundingServiceQuotaRevision.objects.filter(
                service_quota_id__in=[quota.pk for quota in quotas]
            )
        }
        for quota in quotas:
            quota.current_revision_id = revisions[quota.pk]
        FundingServiceQuota.objects.bulk_update(
            quotas,
            ["current_revision"],
            batch_size=500,
        )

    for allocations in _batches(FundingStaffAllocation.objects.order_by("pk")):
        FundingStaffAllocationRevision.objects.bulk_create(
            [
                FundingStaffAllocationRevision(
                    staff_allocation_id=allocation.pk,
                    revision_number=1,
                    event_type="legacy_import",
                    allocated_sessions=allocation.allocated_sessions,
                    session_pay_amount=allocation.session_pay_amount,
                    starts_on=allocation.starts_on,
                    ends_on=allocation.ends_on,
                    note=allocation.note,
                    lifecycle_status=allocation.lifecycle_status,
                    actor_id=None,
                    actor_role_snapshot="legacy",
                    reason=(
                        "Перенос существующей строки; "
                        "автор исходного решения неизвестен."
                    ),
                    supersedes_id=None,
                    decided_at=None,
                )
                for allocation in allocations
            ],
            batch_size=500,
        )
        revisions = {
            revision.staff_allocation_id: revision.pk
            for revision in FundingStaffAllocationRevision.objects.filter(
                staff_allocation_id__in=[
                    allocation.pk for allocation in allocations
                ]
            )
        }
        for allocation in allocations:
            allocation.current_revision_id = revisions[allocation.pk]
        FundingStaffAllocation.objects.bulk_update(
            allocations,
            ["current_revision"],
            batch_size=500,
        )


def install_postgresql_grant_revision_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE FUNCTION operations_block_grant_revision_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'grant plan revision rows are immutable'
                USING DETAIL = TG_TABLE_NAME || '.' || OLD.id::text;
        END;
        $$;
        """
    )
    for table_name in (
        "operations_fundingservicequotarevision",
        "operations_fundingstaffallocationrevision",
    ):
        trigger_name = f"{table_name}_immutable"
        schema_editor.execute(
            f"""
            CREATE TRIGGER {schema_editor.quote_name(trigger_name)}
            BEFORE UPDATE OR DELETE ON {schema_editor.quote_name(table_name)}
            FOR EACH ROW
            EXECUTE FUNCTION operations_block_grant_revision_mutation();
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0047_persisted_balance_transfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingStaffAllocationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('revision_number', models.PositiveIntegerField(verbose_name='номер редакции')),
                ('event_type', models.CharField(choices=[('created', 'Создано'), ('revised', 'Изменено'), ('closed', 'Закрыто'), ('legacy_import', 'Перенесено из прежней модели')], max_length=20, verbose_name='действие')),
                ('allocated_sessions', models.PositiveIntegerField(default=0, verbose_name='выделено занятий')),
                ('session_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='стоимость занятия специалисту')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], max_length=20, verbose_name='статус плановой позиции')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('legacy', 'Автор неизвестен')], max_length=20, verbose_name='роль на момент решения')),
                ('reason', models.TextField(verbose_name='основание')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='время решения')),
            ],
            options={
                'verbose_name': 'редакция распределения грантовой квоты',
                'verbose_name_plural': 'редакции распределений грантовых квот',
                'ordering': ['staff_allocation_id', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='fundingservicequota',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта')], default='active', max_length=20, verbose_name='статус плановой позиции'),
        ),
        migrations.AddField(
            model_name='fundingstaffallocation',
            name='lifecycle_status',
            field=models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=20, verbose_name='статус плановой позиции'),
        ),
        migrations.AlterField(
            model_name='fundingservicequota',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_quotas', to='operations.fundingsource', verbose_name='источник финансирования'),
        ),
        migrations.AlterField(
            model_name='fundingservicequota',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_quotas', to='operations.service', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='fundingstaffallocation',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_allocations', to='operations.fundingsource', verbose_name='источник финансирования'),
        ),
        migrations.AlterField(
            model_name='fundingstaffallocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_funding_allocations', to='operations.service', verbose_name='услуга'),
        ),
        migrations.AlterField(
            model_name='fundingstaffallocation',
            name='service_quota',
            field=models.ForeignKey(blank=True, help_text='Можно оставить пустым, если распределение задаётся сразу как специалист + услуга + количество.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_allocations', to='operations.fundingservicequota', verbose_name='квота услуги'),
        ),
        migrations.AlterField(
            model_name='fundingstaffallocation',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funding_allocations', to='operations.staffmember', verbose_name='специалист'),
        ),
        migrations.CreateModel(
            name='FundingServiceQuotaRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('revision_number', models.PositiveIntegerField(verbose_name='номер редакции')),
                ('event_type', models.CharField(choices=[('created', 'Создана'), ('revised', 'Изменена'), ('closed', 'Закрыта'), ('legacy_import', 'Перенесена из прежней модели')], max_length=20, verbose_name='действие')),
                ('planned_sessions', models.PositiveIntegerField(default=0, verbose_name='план занятий')),
                ('starts_on', models.DateField(blank=True, null=True, verbose_name='действует с')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='действует по')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта')], max_length=20, verbose_name='статус плановой позиции')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('legacy', 'Автор неизвестен')], max_length=20, verbose_name='роль на момент решения')),
                ('reason', models.TextField(verbose_name='основание')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='время решения')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_service_quota_revisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал')),
                ('service_quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='operations.fundingservicequota', verbose_name='квота услуги')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.fundingservicequotarevision', verbose_name='предыдущая редакция')),
            ],
            options={
                'verbose_name': 'редакция квоты финансирования',
                'verbose_name_plural': 'редакции квот финансирования',
                'ordering': ['service_quota_id', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='fundingservicequota',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_service_quota', to='operations.fundingservicequotarevision', verbose_name='текущая редакция'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequota',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status', 'active'), ('ends_on__isnull', False), _connector='OR'), name='funding_service_quota_closed_has_end'),
        ),
        migrations.AddField(
            model_name='fundingstaffallocationrevision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_staff_allocation_revisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал'),
        ),
        migrations.AddField(
            model_name='fundingstaffallocationrevision',
            name='staff_allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='operations.fundingstaffallocation', verbose_name='распределение специалисту'),
        ),
        migrations.AddField(
            model_name='fundingstaffallocationrevision',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.fundingstaffallocationrevision', verbose_name='предыдущая редакция'),
        ),
        migrations.AddField(
            model_name='fundingstaffallocation',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_staff_allocation', to='operations.fundingstaffallocationrevision', verbose_name='текущая редакция'),
        ),
        migrations.RunPython(backfill_grant_plan_revisions),
        migrations.AddField(
            model_name='payrollaccrual',
            name='grant_allocation_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_accruals', to='operations.fundingstaffallocationrevision', verbose_name='редакция грантовой ставки'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocation',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status', 'active'), ('ends_on__isnull', False), _connector='OR'), name='funding_staff_alloc_closed_has_end'),
        ),
        migrations.AddIndex(
            model_name='fundingservicequotarevision',
            index=models.Index(fields=['service_quota', '-revision_number'], name='operations__service_a74f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingservicequotarevision',
            index=models.Index(fields=['actor', '-created_at'], name='operations__actor_i_4aec4c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.UniqueConstraint(fields=('service_quota', 'revision_number'), name='unique_funding_quota_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_funding_quota_revision_successor'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='funding_quota_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='funding_quota_revision_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status', 'active'), ('ends_on__isnull', False), _connector='OR'), name='funding_quota_revision_closed_has_end'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('actor_role_snapshot', 'legacy'), ('decided_at__isnull', True), ('event_type', 'legacy_import')), models.Q(models.Q(('event_type', 'legacy_import'), _negated=True), ('actor__isnull', False), ('actor_role_snapshot', 'director'), ('decided_at__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='funding_quota_revision_actor_matches_event'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['created', 'legacy_import']), ('supersedes__isnull', True)), models.Q(('event_type__in', ['revised', 'closed']), ('supersedes__isnull', False)), _connector='OR'), name='funding_quota_revision_chain_matches_event'),
        ),
        migrations.AddConstraint(
            model_name='fundingservicequotarevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'closed'), _negated=True), ('lifecycle_status', 'closed'), _connector='OR'), name='funding_quota_closed_event_has_closed_status'),
        ),
        migrations.AddIndex(
            model_name='fundingstaffallocationrevision',
            index=models.Index(fields=['staff_allocation', '-revision_number'], name='operations__staff_a_a4dc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingstaffallocationrevision',
            index=models.Index(fields=['actor', '-created_at'], name='operations__actor_i_0e209f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.UniqueConstraint(fields=('staff_allocation', 'revision_number'), name='unique_funding_staff_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_funding_staff_revision_successor'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='funding_staff_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('session_pay_amount__isnull', True), ('session_pay_amount__gte', 0), _connector='OR'), name='funding_staff_revision_pay_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('starts_on__isnull', True), ('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='funding_staff_revision_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_status', 'active'), ('ends_on__isnull', False), _connector='OR'), name='funding_staff_revision_closed_has_end'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('actor_role_snapshot', 'legacy'), ('decided_at__isnull', True), ('event_type', 'legacy_import')), models.Q(models.Q(('event_type', 'legacy_import'), _negated=True), ('actor__isnull', False), ('actor_role_snapshot', 'director'), ('decided_at__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='funding_staff_revision_actor_matches_event'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['created', 'legacy_import']), ('supersedes__isnull', True)), models.Q(('event_type__in', ['revised', 'closed']), ('supersedes__isnull', False)), _connector='OR'), name='funding_staff_revision_chain_matches_event'),
        ),
        migrations.AddConstraint(
            model_name='fundingstaffallocationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'closed'), _negated=True), ('lifecycle_status', 'closed'), _connector='OR'), name='funding_staff_closed_event_has_closed_status'),
        ),
        migrations.RunPython(install_postgresql_grant_revision_guards),
    ]
