# Generated by Django 5.2.14 on 2026-07-26 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def install_postgresql_grant_compensation_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    schema_editor.execute(
        """
        ALTER TABLE operations_fundingpayrollbudget
        ADD CONSTRAINT payroll_budget_period_exclusion
        EXCLUDE USING gist (
            funding_source_id WITH =,
            daterange(starts_on, ends_on, '[]') WITH &&
        )
        """
    )
    schema_editor.execute(
        """
        ALTER TABLE operations_grantfixedcompensation
        ADD CONSTRAINT grant_fixed_service_period_exclusion
        EXCLUDE USING gist (
            payroll_budget_id WITH =,
            staff_member_id WITH =,
            service_id WITH =,
            daterange(period_from, period_to, '[]') WITH &&
        )
        WHERE (compensation_scope = 'service_delivery')
        """
    )
    schema_editor.execute(
        """
        ALTER TABLE operations_grantfixedcompensation
        ADD CONSTRAINT grant_fixed_role_period_exclusion
        EXCLUDE USING gist (
            payroll_budget_id WITH =,
            staff_member_id WITH =,
            assignment_key WITH =,
            daterange(period_from, period_to, '[]') WITH &&
        )
        WHERE (compensation_scope = 'project_role')
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_block_grant_comp_revision_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'grant compensation revision rows are immutable'
                USING DETAIL = TG_TABLE_NAME || '.' || OLD.id::text;
        END;
        $$
        """
    )
    for table_name in (
        "operations_fundingpayrollbudgetrevision",
        "operations_grantfixedcompensationrevision",
    ):
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table_name}_immutable
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION operations_block_grant_comp_revision_mutation()
            """
        )

    schema_editor.execute(
        """
        CREATE FUNCTION operations_block_grant_comp_root_delete()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'grant compensation roots cannot be deleted'
                USING DETAIL = TG_TABLE_NAME || '.' || OLD.id::text;
        END;
        $$
        """
    )
    for table_name in (
        "operations_fundingpayrollbudget",
        "operations_grantfixedcompensation",
    ):
        schema_editor.execute(
            f"""
            CREATE TRIGGER {table_name}_no_delete
            BEFORE DELETE ON {table_name}
            FOR EACH ROW
            EXECUTE FUNCTION operations_block_grant_comp_root_delete()
            """
        )

    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_payroll_budget_root_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.funding_source_id IS DISTINCT FROM OLD.funding_source_id THEN
                RAISE EXCEPTION 'payroll budget funding source is immutable';
            END IF;

            IF ROW(
                NEW.starts_on,
                NEW.ends_on,
                NEW.planned_amount,
                NEW.enforcement_mode,
                NEW.lifecycle_status,
                NEW.note,
                NEW.current_revision_id
            ) IS DISTINCT FROM ROW(
                OLD.starts_on,
                OLD.ends_on,
                OLD.planned_amount,
                OLD.enforcement_mode,
                OLD.lifecycle_status,
                OLD.note,
                OLD.current_revision_id
            ) AND (
                NEW.current_revision_id IS NULL
                OR NOT EXISTS (
                    SELECT 1
                    FROM operations_fundingpayrollbudgetrevision revision
                    WHERE revision.id = NEW.current_revision_id
                      AND revision.payroll_budget_id = NEW.id
                      AND revision.starts_on IS NOT DISTINCT FROM NEW.starts_on
                      AND revision.ends_on IS NOT DISTINCT FROM NEW.ends_on
                      AND revision.planned_amount IS NOT DISTINCT FROM NEW.planned_amount
                      AND revision.enforcement_mode IS NOT DISTINCT FROM NEW.enforcement_mode
                      AND revision.lifecycle_status IS NOT DISTINCT FROM NEW.lifecycle_status
                      AND revision.note IS NOT DISTINCT FROM NEW.note
                      AND (
                          (
                              OLD.current_revision_id IS NULL
                              AND revision.supersedes_id IS NULL
                              AND revision.revision_number = 1
                          )
                          OR revision.supersedes_id = OLD.current_revision_id
                      )
                )
            ) THEN
                RAISE EXCEPTION 'payroll budget projection requires its matching revision';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_fundingpayrollbudget_root_update_guard
        BEFORE UPDATE OF
            funding_source_id,
            starts_on,
            ends_on,
            planned_amount,
            enforcement_mode,
            lifecycle_status,
            note,
            current_revision_id
        ON operations_fundingpayrollbudget
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_payroll_budget_root_update()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_grant_fixed_root_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.payroll_budget_id IS DISTINCT FROM OLD.payroll_budget_id
               OR NEW.staff_member_id IS DISTINCT FROM OLD.staff_member_id
               OR NEW.compensation_scope IS DISTINCT FROM OLD.compensation_scope
               OR NEW.service_id IS DISTINCT FROM OLD.service_id
               OR NEW.assignment_label IS DISTINCT FROM OLD.assignment_label
               OR NEW.assignment_key IS DISTINCT FROM OLD.assignment_key
            THEN
                RAISE EXCEPTION 'fixed compensation business identity is immutable';
            END IF;

            IF ROW(
                NEW.period_from,
                NEW.period_to,
                NEW.accrual_on,
                NEW.amount,
                NEW.lifecycle_status,
                NEW.note,
                NEW.current_revision_id
            ) IS DISTINCT FROM ROW(
                OLD.period_from,
                OLD.period_to,
                OLD.accrual_on,
                OLD.amount,
                OLD.lifecycle_status,
                OLD.note,
                OLD.current_revision_id
            ) AND (
                NEW.current_revision_id IS NULL
                OR NOT EXISTS (
                    SELECT 1
                    FROM operations_grantfixedcompensationrevision revision
                    WHERE revision.id = NEW.current_revision_id
                      AND revision.fixed_compensation_id = NEW.id
                      AND revision.compensation_scope IS NOT DISTINCT FROM NEW.compensation_scope
                      AND revision.service_id IS NOT DISTINCT FROM NEW.service_id
                      AND revision.assignment_label IS NOT DISTINCT FROM NEW.assignment_label
                      AND revision.assignment_key IS NOT DISTINCT FROM NEW.assignment_key
                      AND revision.period_from IS NOT DISTINCT FROM NEW.period_from
                      AND revision.period_to IS NOT DISTINCT FROM NEW.period_to
                      AND revision.accrual_on IS NOT DISTINCT FROM NEW.accrual_on
                      AND revision.amount IS NOT DISTINCT FROM NEW.amount
                      AND revision.lifecycle_status IS NOT DISTINCT FROM NEW.lifecycle_status
                      AND revision.note IS NOT DISTINCT FROM NEW.note
                      AND (
                          (
                              OLD.current_revision_id IS NULL
                              AND revision.supersedes_id IS NULL
                              AND revision.revision_number = 1
                          )
                          OR revision.supersedes_id = OLD.current_revision_id
                      )
                )
            ) THEN
                RAISE EXCEPTION 'fixed compensation projection requires its matching revision';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_grantfixedcompensation_root_update_guard
        BEFORE UPDATE OF
            payroll_budget_id,
            staff_member_id,
            compensation_scope,
            service_id,
            assignment_label,
            assignment_key,
            period_from,
            period_to,
            accrual_on,
            amount,
            lifecycle_status,
            note,
            current_revision_id
        ON operations_grantfixedcompensation
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_grant_fixed_root_update()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_payroll_budget_revision_insert()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            source_id bigint;
            current_revision_id bigint;
            previous_root_id bigint;
            previous_revision_number integer;
            previous_event_type varchar(20);
            previous_lifecycle_status varchar(20);
        BEGIN
            SELECT budget.funding_source_id
            INTO source_id
            FROM operations_fundingpayrollbudget budget
            WHERE budget.id = NEW.payroll_budget_id;

            IF source_id IS NULL THEN
                RAISE EXCEPTION 'payroll budget revision root does not exist';
            END IF;

            PERFORM 1
            FROM operations_fundingsource source
            WHERE source.id = source_id
            FOR UPDATE;

            SELECT budget.current_revision_id
            INTO current_revision_id
            FROM operations_fundingpayrollbudget budget
            WHERE budget.id = NEW.payroll_budget_id
            FOR UPDATE;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'payroll budget revision root does not exist';
            END IF;

            IF NEW.supersedes_id IS NULL THEN
                IF NEW.revision_number <> 1 OR current_revision_id IS NOT NULL THEN
                    RAISE EXCEPTION 'initial payroll budget revision must be revision 1';
                END IF;
                IF NEW.event_type NOT IN ('created', 'legacy_import') THEN
                    RAISE EXCEPTION 'initial payroll budget revision has invalid event type';
                END IF;
                IF NEW.event_type = 'created' AND NEW.lifecycle_status <> 'active' THEN
                    RAISE EXCEPTION 'created payroll budget revision must be active';
                END IF;
            ELSE
                SELECT
                    previous.payroll_budget_id,
                    previous.revision_number,
                    previous.event_type,
                    previous.lifecycle_status
                INTO
                    previous_root_id,
                    previous_revision_number,
                    previous_event_type,
                    previous_lifecycle_status
                FROM operations_fundingpayrollbudgetrevision previous
                WHERE previous.id = NEW.supersedes_id;

                IF previous_root_id IS NULL
                   OR previous_root_id <> NEW.payroll_budget_id
                   OR NEW.revision_number <> previous_revision_number + 1
                   OR current_revision_id IS DISTINCT FROM NEW.supersedes_id
                THEN
                    RAISE EXCEPTION 'payroll budget revision must extend the current chain';
                END IF;
                IF previous_event_type = 'closed'
                   OR previous_lifecycle_status = 'closed'
                THEN
                    RAISE EXCEPTION 'closed payroll budget cannot be reopened or revised';
                END IF;
                IF NEW.event_type = 'revised' THEN
                    IF NEW.lifecycle_status IS DISTINCT FROM previous_lifecycle_status THEN
                        RAISE EXCEPTION 'revised payroll budget must preserve lifecycle status';
                    END IF;
                ELSIF NEW.event_type = 'closed' THEN
                    IF NEW.lifecycle_status <> 'closed' THEN
                        RAISE EXCEPTION 'closed payroll budget revision must be closed';
                    END IF;
                ELSE
                    RAISE EXCEPTION 'successor payroll budget revision has invalid event type';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_fundingpayrollbudgetrevision_chain_guard
        BEFORE INSERT ON operations_fundingpayrollbudgetrevision
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_payroll_budget_revision_insert()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_grant_fixed_revision_insert()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            source_id bigint;
            budget_id bigint;
            budget_current_revision_id bigint;
            current_revision_id bigint;
            previous_root_id bigint;
            previous_revision_number integer;
            previous_event_type varchar(20);
            previous_lifecycle_status varchar(20);
        BEGIN
            SELECT fixed.payroll_budget_id, budget.funding_source_id
            INTO budget_id, source_id
            FROM operations_grantfixedcompensation fixed
            JOIN operations_fundingpayrollbudget budget
              ON budget.id = fixed.payroll_budget_id
            WHERE fixed.id = NEW.fixed_compensation_id;

            IF source_id IS NULL OR budget_id IS NULL THEN
                RAISE EXCEPTION 'fixed compensation revision root does not exist';
            END IF;

            PERFORM 1
            FROM operations_fundingsource source
            WHERE source.id = source_id
            FOR UPDATE;

            SELECT budget.current_revision_id
            INTO budget_current_revision_id
            FROM operations_fundingpayrollbudget budget
            WHERE budget.id = budget_id
            FOR UPDATE;

            SELECT fixed.current_revision_id
            INTO current_revision_id
            FROM operations_grantfixedcompensation fixed
            WHERE fixed.id = NEW.fixed_compensation_id
            FOR UPDATE;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'fixed compensation revision root does not exist';
            END IF;
            IF NEW.budget_revision_at_decision_id
               IS DISTINCT FROM budget_current_revision_id
            THEN
                RAISE EXCEPTION 'fixed compensation revision must use current budget revision';
            END IF;
            IF NEW.compensation_scope = 'project_role'
               AND NEW.assignment_key IS DISTINCT FROM lower(
                   regexp_replace(
                       btrim(NEW.assignment_label),
                       '[[:space:]]+',
                       ' ',
                       'g'
                   )
               )
            THEN
                RAISE EXCEPTION 'fixed compensation assignment key must be canonical';
            END IF;

            IF NEW.supersedes_id IS NULL THEN
                IF NEW.revision_number <> 1 OR current_revision_id IS NOT NULL THEN
                    RAISE EXCEPTION 'initial fixed compensation revision must be revision 1';
                END IF;
                IF NEW.event_type NOT IN ('created', 'legacy_import') THEN
                    RAISE EXCEPTION 'initial fixed compensation revision has invalid event type';
                END IF;
                IF NEW.event_type = 'created' AND NEW.lifecycle_status <> 'active' THEN
                    RAISE EXCEPTION 'created fixed compensation revision must be active';
                END IF;
            ELSE
                SELECT
                    previous.fixed_compensation_id,
                    previous.revision_number,
                    previous.event_type,
                    previous.lifecycle_status
                INTO
                    previous_root_id,
                    previous_revision_number,
                    previous_event_type,
                    previous_lifecycle_status
                FROM operations_grantfixedcompensationrevision previous
                WHERE previous.id = NEW.supersedes_id;

                IF previous_root_id IS NULL
                   OR previous_root_id <> NEW.fixed_compensation_id
                   OR NEW.revision_number <> previous_revision_number + 1
                   OR current_revision_id IS DISTINCT FROM NEW.supersedes_id
                THEN
                    RAISE EXCEPTION 'fixed compensation revision must extend the current chain';
                END IF;
                IF previous_event_type = 'closed'
                   OR previous_lifecycle_status = 'closed'
                THEN
                    RAISE EXCEPTION 'closed fixed compensation cannot be reopened or revised';
                END IF;
                IF NEW.event_type = 'revised' THEN
                    IF NEW.lifecycle_status IS DISTINCT FROM previous_lifecycle_status THEN
                        RAISE EXCEPTION 'revised fixed compensation must preserve lifecycle status';
                    END IF;
                ELSIF NEW.event_type = 'closed' THEN
                    IF NEW.lifecycle_status <> 'closed' THEN
                        RAISE EXCEPTION 'closed fixed compensation revision must be closed';
                    END IF;
                ELSE
                    RAISE EXCEPTION 'successor fixed compensation revision has invalid event type';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_grantfixedcompensationrevision_chain_guard
        BEFORE INSERT ON operations_grantfixedcompensationrevision
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_grant_fixed_revision_insert()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_fixed_compensation_budget()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            source_id bigint;
            budget_status varchar(20);
        BEGIN
            IF NEW.compensation_scope = 'project_role'
               AND NEW.assignment_key IS DISTINCT FROM lower(
                   regexp_replace(
                       btrim(NEW.assignment_label),
                       '[[:space:]]+',
                       ' ',
                       'g'
                   )
               )
            THEN
                RAISE EXCEPTION 'fixed compensation assignment key must be canonical';
            END IF;
            SELECT budget.funding_source_id
            INTO source_id
            FROM operations_fundingpayrollbudget budget
            WHERE budget.id = NEW.payroll_budget_id;

            IF source_id IS NULL THEN
                RAISE EXCEPTION 'fixed compensation payroll budget does not exist';
            END IF;

            PERFORM 1
            FROM operations_fundingsource source
            WHERE source.id = source_id
            FOR UPDATE;

            SELECT budget.lifecycle_status
            INTO budget_status
            FROM operations_fundingpayrollbudget budget
            WHERE budget.id = NEW.payroll_budget_id
              AND NEW.period_from >= budget.starts_on
              AND NEW.period_to <= budget.ends_on
              AND NEW.accrual_on >= budget.starts_on
              AND NEW.accrual_on <= budget.ends_on
            FOR UPDATE;

            IF budget_status IS NULL THEN
                RAISE EXCEPTION 'fixed compensation must fit its payroll budget';
            END IF;
            IF TG_OP = 'INSERT' AND budget_status <> 'active' THEN
                RAISE EXCEPTION 'fixed compensation requires an active payroll budget';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_grantfixedcompensation_budget_guard
        BEFORE INSERT OR UPDATE OF
            payroll_budget_id,
            compensation_scope,
            assignment_label,
            assignment_key,
            period_from,
            period_to,
            accrual_on
        ON operations_grantfixedcompensation
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_fixed_compensation_budget()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_payroll_budget_period()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            PERFORM 1
            FROM operations_fundingsource source
            WHERE source.id = NEW.funding_source_id
            FOR UPDATE;

            IF EXISTS (
                SELECT 1
                FROM operations_grantfixedcompensation fixed
                WHERE fixed.payroll_budget_id = NEW.id
                  AND (
                      fixed.period_from < NEW.starts_on
                      OR fixed.period_to > NEW.ends_on
                      OR fixed.accrual_on < NEW.starts_on
                      OR fixed.accrual_on > NEW.ends_on
                  )
            ) THEN
                RAISE EXCEPTION 'payroll budget period cannot exclude fixed compensation';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_fundingpayrollbudget_period_guard
        BEFORE UPDATE OF starts_on, ends_on ON operations_fundingpayrollbudget
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_payroll_budget_period()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_fixed_vs_staff_allocation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            source_id bigint;
        BEGIN
            SELECT budget.funding_source_id
            INTO source_id
            FROM operations_fundingpayrollbudget budget
            WHERE budget.id = NEW.payroll_budget_id;

            PERFORM 1
            FROM operations_fundingsource source
            WHERE source.id = source_id
            FOR UPDATE;

            IF NEW.compensation_scope = 'service_delivery' AND EXISTS (
                SELECT 1
                FROM operations_fundingstaffallocation allocation
                WHERE allocation.funding_source_id = source_id
                  AND allocation.staff_member_id = NEW.staff_member_id
                  AND allocation.service_id = NEW.service_id
                  AND daterange(allocation.starts_on, allocation.ends_on, '[]')
                      && daterange(NEW.period_from, NEW.period_to, '[]')
            ) THEN
                RAISE EXCEPTION
                    'fixed service compensation conflicts with per-session allocation';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_grantfixedcompensation_staff_allocation_guard
        BEFORE INSERT OR UPDATE OF
            payroll_budget_id,
            staff_member_id,
            compensation_scope,
            service_id,
            period_from,
            period_to
        ON operations_grantfixedcompensation
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_fixed_vs_staff_allocation()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_staff_allocation_vs_fixed()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            PERFORM 1
            FROM operations_fundingsource source
            WHERE source.id = NEW.funding_source_id
            FOR UPDATE;

            IF EXISTS (
                SELECT 1
                FROM operations_grantfixedcompensation fixed
                JOIN operations_fundingpayrollbudget budget
                  ON budget.id = fixed.payroll_budget_id
                WHERE budget.funding_source_id = NEW.funding_source_id
                  AND fixed.compensation_scope = 'service_delivery'
                  AND fixed.staff_member_id = NEW.staff_member_id
                  AND fixed.service_id = NEW.service_id
                  AND daterange(fixed.period_from, fixed.period_to, '[]')
                      && daterange(NEW.starts_on, NEW.ends_on, '[]')
            ) THEN
                RAISE EXCEPTION
                    'per-session allocation conflicts with fixed service compensation';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_fundingstaffallocation_fixed_guard
        BEFORE INSERT OR UPDATE OF
            funding_source_id,
            staff_member_id,
            service_id,
            starts_on,
            ends_on
        ON operations_fundingstaffallocation
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_staff_allocation_vs_fixed()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_payroll_budget_terminal_state()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            root_id bigint;
        BEGIN
            IF TG_TABLE_NAME = 'operations_fundingpayrollbudget' THEN
                root_id := NEW.id;
            ELSE
                root_id := NEW.payroll_budget_id;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM operations_fundingpayrollbudget budget
                JOIN operations_fundingpayrollbudgetrevision revision
                  ON revision.id = budget.current_revision_id
                WHERE budget.id = root_id
                  AND revision.payroll_budget_id = budget.id
                  AND revision.starts_on IS NOT DISTINCT FROM budget.starts_on
                  AND revision.ends_on IS NOT DISTINCT FROM budget.ends_on
                  AND revision.planned_amount IS NOT DISTINCT FROM budget.planned_amount
                  AND revision.enforcement_mode
                      IS NOT DISTINCT FROM budget.enforcement_mode
                  AND revision.lifecycle_status
                      IS NOT DISTINCT FROM budget.lifecycle_status
                  AND revision.note IS NOT DISTINCT FROM budget.note
                  AND NOT EXISTS (
                      SELECT 1
                      FROM operations_fundingpayrollbudgetrevision successor
                      WHERE successor.supersedes_id = revision.id
                  )
            ) THEN
                RAISE EXCEPTION
                    'payroll budget current revision must be terminal and match projection';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE CONSTRAINT TRIGGER operations_fundingpayrollbudget_terminal_guard
        AFTER INSERT OR UPDATE ON operations_fundingpayrollbudget
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_payroll_budget_terminal_state()
        """
    )
    schema_editor.execute(
        """
        CREATE CONSTRAINT TRIGGER operations_fundingpayrollbudgetrevision_terminal_guard
        AFTER INSERT ON operations_fundingpayrollbudgetrevision
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_payroll_budget_terminal_state()
        """
    )
    schema_editor.execute(
        """
        CREATE FUNCTION operations_validate_grant_fixed_terminal_state()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            root_id bigint;
        BEGIN
            IF TG_TABLE_NAME = 'operations_grantfixedcompensation' THEN
                root_id := NEW.id;
            ELSE
                root_id := NEW.fixed_compensation_id;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM operations_grantfixedcompensation fixed
                JOIN operations_grantfixedcompensationrevision revision
                  ON revision.id = fixed.current_revision_id
                WHERE fixed.id = root_id
                  AND revision.fixed_compensation_id = fixed.id
                  AND revision.compensation_scope
                      IS NOT DISTINCT FROM fixed.compensation_scope
                  AND revision.service_id IS NOT DISTINCT FROM fixed.service_id
                  AND revision.assignment_label
                      IS NOT DISTINCT FROM fixed.assignment_label
                  AND revision.assignment_key
                      IS NOT DISTINCT FROM fixed.assignment_key
                  AND revision.period_from IS NOT DISTINCT FROM fixed.period_from
                  AND revision.period_to IS NOT DISTINCT FROM fixed.period_to
                  AND revision.accrual_on IS NOT DISTINCT FROM fixed.accrual_on
                  AND revision.amount IS NOT DISTINCT FROM fixed.amount
                  AND revision.lifecycle_status
                      IS NOT DISTINCT FROM fixed.lifecycle_status
                  AND revision.note IS NOT DISTINCT FROM fixed.note
                  AND NOT EXISTS (
                      SELECT 1
                      FROM operations_grantfixedcompensationrevision successor
                      WHERE successor.supersedes_id = revision.id
                  )
            ) THEN
                RAISE EXCEPTION
                    'fixed compensation current revision must be terminal and match projection';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        CREATE CONSTRAINT TRIGGER operations_grantfixedcompensation_terminal_guard
        AFTER INSERT OR UPDATE ON operations_grantfixedcompensation
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_grant_fixed_terminal_state()
        """
    )
    schema_editor.execute(
        """
        CREATE CONSTRAINT TRIGGER operations_grantfixedcompensationrevision_terminal_guard
        AFTER INSERT ON operations_grantfixedcompensationrevision
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_grant_fixed_terminal_state()
        """
    )

def uninstall_postgresql_grant_compensation_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_grantfixedcompensationrevision_terminal_guard
        ON operations_grantfixedcompensationrevision;
        DROP TRIGGER IF EXISTS operations_grantfixedcompensation_terminal_guard
        ON operations_grantfixedcompensation;
        DROP FUNCTION IF EXISTS operations_validate_grant_fixed_terminal_state();

        DROP TRIGGER IF EXISTS operations_fundingpayrollbudgetrevision_terminal_guard
        ON operations_fundingpayrollbudgetrevision;
        DROP TRIGGER IF EXISTS operations_fundingpayrollbudget_terminal_guard
        ON operations_fundingpayrollbudget;
        DROP FUNCTION IF EXISTS operations_validate_payroll_budget_terminal_state();
        DROP TRIGGER IF EXISTS operations_grantfixedcompensationrevision_chain_guard
        ON operations_grantfixedcompensationrevision;
        DROP FUNCTION IF EXISTS operations_validate_grant_fixed_revision_insert();

        DROP TRIGGER IF EXISTS operations_fundingpayrollbudgetrevision_chain_guard
        ON operations_fundingpayrollbudgetrevision;
        DROP FUNCTION IF EXISTS operations_validate_payroll_budget_revision_insert();

        DROP TRIGGER IF EXISTS operations_grantfixedcompensation_root_update_guard
        ON operations_grantfixedcompensation;
        DROP FUNCTION IF EXISTS operations_validate_grant_fixed_root_update();

        DROP TRIGGER IF EXISTS operations_fundingpayrollbudget_root_update_guard
        ON operations_fundingpayrollbudget;
        DROP FUNCTION IF EXISTS operations_validate_payroll_budget_root_update();

        DROP TRIGGER IF EXISTS operations_fundingstaffallocation_fixed_guard
        ON operations_fundingstaffallocation;
        DROP FUNCTION IF EXISTS operations_validate_staff_allocation_vs_fixed();

        DROP TRIGGER IF EXISTS operations_grantfixedcompensation_staff_allocation_guard
        ON operations_grantfixedcompensation;
        DROP FUNCTION IF EXISTS operations_validate_fixed_vs_staff_allocation();

        DROP TRIGGER IF EXISTS operations_fundingpayrollbudget_period_guard
        ON operations_fundingpayrollbudget;
        DROP FUNCTION IF EXISTS operations_validate_payroll_budget_period();

        DROP TRIGGER IF EXISTS operations_grantfixedcompensation_budget_guard
        ON operations_grantfixedcompensation;
        DROP FUNCTION IF EXISTS operations_validate_fixed_compensation_budget();

        DROP TRIGGER IF EXISTS operations_fundingpayrollbudget_no_delete
        ON operations_fundingpayrollbudget;
        DROP TRIGGER IF EXISTS operations_grantfixedcompensation_no_delete
        ON operations_grantfixedcompensation;
        DROP FUNCTION IF EXISTS operations_block_grant_comp_root_delete();

        DROP TRIGGER IF EXISTS operations_fundingpayrollbudgetrevision_immutable
        ON operations_fundingpayrollbudgetrevision;
        DROP TRIGGER IF EXISTS operations_grantfixedcompensationrevision_immutable
        ON operations_grantfixedcompensationrevision;
        DROP FUNCTION IF EXISTS operations_block_grant_comp_revision_mutation();

        ALTER TABLE operations_grantfixedcompensation
            DROP CONSTRAINT IF EXISTS grant_fixed_role_period_exclusion;
        ALTER TABLE operations_grantfixedcompensation
            DROP CONSTRAINT IF EXISTS grant_fixed_service_period_exclusion;
        ALTER TABLE operations_fundingpayrollbudget
            DROP CONSTRAINT IF EXISTS payroll_budget_period_exclusion;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0048_fundingstaffallocationrevision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingPayrollBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('starts_on', models.DateField(verbose_name='действует с')),
                ('ends_on', models.DateField(verbose_name='действует по')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='бюджет оплаты труда')),
                ('enforcement_mode', models.CharField(choices=[('warning', 'Предупреждать о превышении'), ('hard', 'Запрещать превышение')], default='hard', max_length=20, verbose_name='контроль лимита')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=20, verbose_name='статус бюджета')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_budgets', to='operations.fundingsource', verbose_name='источник финансирования')),
            ],
            options={
                'verbose_name': 'бюджет оплаты труда по источнику',
                'verbose_name_plural': 'бюджеты оплаты труда по источникам',
                'ordering': ['funding_source__name', 'starts_on', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FundingPayrollBudgetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('revision_number', models.PositiveIntegerField(verbose_name='номер редакции')),
                ('event_type', models.CharField(choices=[('created', 'Создан'), ('revised', 'Изменен'), ('closed', 'Закрыт'), ('legacy_import', 'Перенесен из прежней модели')], max_length=20, verbose_name='действие')),
                ('starts_on', models.DateField(verbose_name='действует с')),
                ('ends_on', models.DateField(verbose_name='действует по')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='бюджет оплаты труда')),
                ('enforcement_mode', models.CharField(choices=[('warning', 'Предупреждать о превышении'), ('hard', 'Запрещать превышение')], max_length=20, verbose_name='контроль лимита')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], max_length=20, verbose_name='статус бюджета')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('legacy', 'Автор неизвестен')], max_length=20, verbose_name='роль на момент решения')),
                ('reason', models.TextField(verbose_name='основание')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='время решения')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_payroll_budget_revisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал')),
                ('payroll_budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='operations.fundingpayrollbudget', verbose_name='бюджет оплаты труда')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.fundingpayrollbudgetrevision', verbose_name='предыдущая редакция')),
            ],
            options={
                'verbose_name': 'редакция бюджета оплаты труда',
                'verbose_name_plural': 'редакции бюджетов оплаты труда',
                'ordering': ['payroll_budget_id', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='fundingpayrollbudget',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_payroll_budget', to='operations.fundingpayrollbudgetrevision', verbose_name='текущая редакция'),
        ),
        migrations.CreateModel(
            name='GrantFixedCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('compensation_scope', models.CharField(choices=[('service_delivery', 'Фиксировано за оказание услуги'), ('project_role', 'Дополнительная проектная роль')], max_length=30, verbose_name='вид фиксированной оплаты')),
                ('assignment_label', models.CharField(blank=True, max_length=200, verbose_name='проектная роль')),
                ('assignment_key', models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='ключ проектной роли')),
                ('period_from', models.DateField(verbose_name='период с')),
                ('period_to', models.DateField(verbose_name='период по')),
                ('accrual_on', models.DateField(verbose_name='дата начисления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='фиксированная сумма')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта')], default='active', max_length=20, verbose_name='статус позиции')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('payroll_budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_compensations', to='operations.fundingpayrollbudget', verbose_name='бюджет оплаты труда')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_fixed_compensations', to='operations.service', verbose_name='услуга')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_fixed_compensations', to='operations.staffmember', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'фиксированная оплата грантового проекта',
                'verbose_name_plural': 'фиксированные оплаты грантовых проектов',
                'ordering': ['payroll_budget__funding_source__name', 'staff_member__full_name', 'period_from', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GrantFixedCompensationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('revision_number', models.PositiveIntegerField(verbose_name='номер редакции')),
                ('event_type', models.CharField(choices=[('created', 'Создана'), ('revised', 'Изменена'), ('closed', 'Закрыта'), ('legacy_import', 'Перенесена из прежней модели')], max_length=20, verbose_name='действие')),
                ('compensation_scope', models.CharField(choices=[('service_delivery', 'Фиксировано за оказание услуги'), ('project_role', 'Дополнительная проектная роль')], max_length=30, verbose_name='вид фиксированной оплаты')),
                ('assignment_label', models.CharField(blank=True, max_length=200, verbose_name='проектная роль')),
                ('assignment_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='ключ проектной роли')),
                ('period_from', models.DateField(verbose_name='период с')),
                ('period_to', models.DateField(verbose_name='период по')),
                ('accrual_on', models.DateField(verbose_name='дата начисления')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='фиксированная сумма')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта')], max_length=20, verbose_name='статус позиции')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('legacy', 'Автор неизвестен')], max_length=20, verbose_name='роль на момент решения')),
                ('reason', models.TextField(verbose_name='основание')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='время решения')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_fixed_compensation_revisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал')),
                ('budget_revision_at_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_compensation_revisions', to='operations.fundingpayrollbudgetrevision', verbose_name='редакция бюджета на момент решения')),
                ('fixed_compensation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='operations.grantfixedcompensation', verbose_name='фиксированная оплата')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_fixed_compensation_revisions', to='operations.service', verbose_name='услуга')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.grantfixedcompensationrevision', verbose_name='предыдущая редакция')),
            ],
            options={
                'verbose_name': 'редакция фиксированной оплаты грантового проекта',
                'verbose_name_plural': 'редакции фиксированных оплат грантовых проектов',
                'ordering': ['fixed_compensation_id', '-revision_number'],
            },
        ),
        migrations.AddField(
            model_name='grantfixedcompensation',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_fixed_compensation', to='operations.grantfixedcompensationrevision', verbose_name='текущая редакция'),
        ),
        migrations.AddIndex(
            model_name='fundingpayrollbudgetrevision',
            index=models.Index(fields=['payroll_budget', '-revision_number'], name='operations__payroll_bbfac1_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingpayrollbudgetrevision',
            index=models.Index(fields=['actor', '-created_at'], name='operations__actor_i_834f04_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.UniqueConstraint(fields=('payroll_budget', 'revision_number'), name='unique_payroll_budget_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_payroll_budget_revision_successor'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='payroll_budget_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='payroll_budget_revision_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gt', 0)), name='payroll_budget_revision_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('actor_role_snapshot', 'legacy'), ('decided_at__isnull', True), ('event_type', 'legacy_import')), models.Q(models.Q(('event_type', 'legacy_import'), _negated=True), ('actor__isnull', False), ('actor_role_snapshot', 'director'), ('decided_at__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='payroll_budget_revision_actor_event'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['created', 'legacy_import']), ('supersedes__isnull', True)), models.Q(('event_type__in', ['revised', 'closed']), ('supersedes__isnull', False)), _connector='OR'), name='payroll_budget_revision_chain_event'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'closed'), _negated=True), ('lifecycle_status', 'closed'), _connector='OR'), name='payroll_budget_closed_event_status'),
        ),
        migrations.AddIndex(
            model_name='fundingpayrollbudget',
            index=models.Index(fields=['funding_source', 'starts_on', 'ends_on'], name='operations__funding_8180d1_idx'),
        ),
        migrations.AddIndex(
            model_name='fundingpayrollbudget',
            index=models.Index(fields=['lifecycle_status', 'starts_on', 'ends_on'], name='operations__lifecyc_a0378e_idx'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudget',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='payroll_budget_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='fundingpayrollbudget',
            constraint=models.CheckConstraint(condition=models.Q(('planned_amount__gt', 0)), name='payroll_budget_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='grantfixedcompensationrevision',
            index=models.Index(fields=['fixed_compensation', '-revision_number'], name='operations__fixed_c_c003e4_idx'),
        ),

        migrations.AddIndex(
            model_name='grantfixedcompensationrevision',
            index=models.Index(fields=['actor', '-created_at'], name='operations__actor_i_c5f76f_idx'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.UniqueConstraint(fields=('fixed_compensation', 'revision_number'), name='unique_grant_fixed_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_grant_fixed_revision_successor'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='grant_fixed_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('period_to__gte', models.F('period_from'))), name='grant_fixed_revision_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('accrual_on__gte', models.F('period_from')), ('accrual_on__lte', models.F('period_to'))), name='grant_fixed_revision_accrual_period'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='grant_fixed_revision_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignment_key__isnull', True), ('assignment_label', ''), ('compensation_scope', 'service_delivery'), ('service__isnull', False)), models.Q(('assignment_key__isnull', False), ('compensation_scope', 'project_role'), ('service__isnull', True), models.Q(('assignment_label', ''), _negated=True), models.Q(('assignment_key', ''), _negated=True)), _connector='OR'), name='grant_fixed_revision_scope_fields'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('actor_role_snapshot', 'legacy'), ('decided_at__isnull', True), ('event_type', 'legacy_import')), models.Q(models.Q(('event_type', 'legacy_import'), _negated=True), ('actor__isnull', False), ('actor_role_snapshot', 'director'), ('decided_at__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='grant_fixed_revision_actor_event'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['created', 'legacy_import']), ('supersedes__isnull', True)), models.Q(('event_type__in', ['revised', 'closed']), ('supersedes__isnull', False)), _connector='OR'), name='grant_fixed_revision_chain_event'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensationrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'closed'), _negated=True), ('lifecycle_status', 'closed'), _connector='OR'), name='grant_fixed_closed_event_status'),
        ),
        migrations.AddIndex(
            model_name='grantfixedcompensation',
            index=models.Index(fields=['payroll_budget', 'staff_member', 'compensation_scope', 'period_from', 'period_to'], name='operations__payroll_43e4f8_idx'),
        ),
        migrations.AddIndex(
            model_name='grantfixedcompensation',
            index=models.Index(fields=['service', 'staff_member', 'period_from', 'period_to'], name='operations__service_22b633_idx'),
        ),
        migrations.AddIndex(
            model_name='grantfixedcompensation',
            index=models.Index(fields=['assignment_key', 'staff_member', 'period_from', 'period_to'], name='operations__assignm_6fcf7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensation',
            constraint=models.CheckConstraint(condition=models.Q(('period_to__gte', models.F('period_from'))), name='grant_fixed_comp_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensation',
            constraint=models.CheckConstraint(condition=models.Q(('accrual_on__gte', models.F('period_from')), ('accrual_on__lte', models.F('period_to'))), name='grant_fixed_comp_accrual_in_period'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='grant_fixed_comp_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='grantfixedcompensation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('assignment_key__isnull', True), ('assignment_label', ''), ('compensation_scope', 'service_delivery'), ('service__isnull', False)), models.Q(('assignment_key__isnull', False), ('compensation_scope', 'project_role'), ('service__isnull', True), models.Q(('assignment_label', ''), _negated=True), models.Q(('assignment_key', ''), _negated=True)), _connector='OR'), name='grant_fixed_comp_scope_fields'),
        ),
        migrations.RunPython(
            install_postgresql_grant_compensation_guards,
            uninstall_postgresql_grant_compensation_guards,
        ),
    ]
