# Generated by Django 5.2.14 on 2026-07-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_donor_report_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_canonical_jsonb(value jsonb)
        RETURNS text
        LANGUAGE plpgsql
        IMMUTABLE
        STRICT
        AS $canonical$
        DECLARE
            result text;
        BEGIN
            CASE jsonb_typeof(value)
                WHEN 'object' THEN
                    SELECT
                        '{' || COALESCE(
                            string_agg(
                                to_json(item.key)::text || ':' ||
                                operations_canonical_jsonb(item.value),
                                ',' ORDER BY item.key COLLATE "C"
                            ),
                            ''
                        ) || '}'
                    INTO result
                    FROM jsonb_each(value) AS item(key, value);
                    RETURN result;
                WHEN 'array' THEN
                    SELECT
                        '[' || COALESCE(
                            string_agg(
                                operations_canonical_jsonb(item.value),
                                ',' ORDER BY item.position
                            ),
                            ''
                        ) || ']'
                    INTO result
                    FROM jsonb_array_elements(value)
                        WITH ORDINALITY AS item(value, position);
                    RETURN result;
                WHEN 'string' THEN
                    RETURN to_jsonb(value #>> '{}')::text;
                WHEN 'null' THEN
                    RETURN 'null';
                ELSE
                    RETURN value::text;
            END CASE;
        END;
        $canonical$;

        CREATE OR REPLACE FUNCTION operations_jsonb_keys_allowed(
            value jsonb,
            allowed_keys text[]
        )
        RETURNS boolean
        LANGUAGE plpgsql
        IMMUTABLE
        STRICT
        AS $allowlist$
        DECLARE
            item record;
        BEGIN
            IF jsonb_typeof(value) = 'object' THEN
                FOR item IN SELECT key, child FROM jsonb_each(value) AS entry(key, child)
                LOOP
                    IF NOT item.key = ANY(allowed_keys)
                       OR NOT operations_jsonb_keys_allowed(item.child, allowed_keys) THEN
                        RETURN false;
                    END IF;
                END LOOP;
            ELSIF jsonb_typeof(value) = 'array' THEN
                FOR item IN SELECT child FROM jsonb_array_elements(value) AS entry(child)
                LOOP
                    IF NOT operations_jsonb_keys_allowed(item.child, allowed_keys) THEN
                        RETURN false;
                    END IF;
                END LOOP;
            END IF;
            RETURN true;
        END;
        $allowlist$;

        CREATE OR REPLACE FUNCTION operations_donor_json_values_allowed(
            value jsonb,
            current_key text DEFAULT NULL
        )
        RETURNS boolean
        LANGUAGE plpgsql
        IMMUTABLE
        AS $values$
        DECLARE
            item record;
            value_type text;
            text_value text;
        BEGIN
            value_type := jsonb_typeof(value);
            IF value_type = 'object' THEN
                FOR item IN SELECT key, child FROM jsonb_each(value) AS entry(key, child)
                LOOP
                    IF NOT operations_donor_json_values_allowed(item.child, item.key) THEN
                        RETURN false;
                    END IF;
                END LOOP;
                RETURN true;
            ELSIF value_type = 'array' THEN
                FOR item IN SELECT child FROM jsonb_array_elements(value) AS entry(child)
                LOOP
                    IF NOT operations_donor_json_values_allowed(item.child, current_key) THEN
                        RETURN false;
                    END IF;
                END LOOP;
                RETURN true;
            ELSIF value_type = 'null' THEN
                RETURN current_key = ANY(ARRAY[
                    'donor', 'service', 'from', 'to', 'ends_on',
                    'session_pay_amount', 'object_ref', 'unit', 'revision_pk'
                ]::text[]);
            ELSIF value_type = 'boolean' THEN
                RETURN current_key = 'active';
            ELSIF value_type = 'number' THEN
                IF current_key = ANY(ARRAY[
                    'source_pk', 'revision_pk', 'payroll_period_accrual_ids',
                    'payroll_line_ids', 'payroll_sheet_ids', 'expense_category_ids'
                ]::text[]) THEN
                    RETURN value::text ~ '^[1-9][0-9]*$';
                END IF;
                IF current_key = 'remaining_sessions' THEN
                    RETURN value::text ~ '^-?(0|[1-9][0-9]*)$';
                END IF;
                RETURN current_key = ANY(ARRAY[
                    'appointment_count', 'planned_count', 'completed_count',
                    'planned_sessions', 'allocated_sessions', 'charged_sessions',
                    'count'
                ]::text[])
                AND value::text ~ '^(0|[1-9][0-9]*)$';
            ELSIF value_type <> 'string' THEN
                RETURN false;
            END IF;

            text_value := value #>> '{}';
            IF current_key = ANY(ARRAY[
                'ref', 'staff_ref', 'recipient_ref', 'budget_ref', 'fixed_ref',
                'object_ref'
            ]::text[]) THEN
                RETURN text_value ~
                    '^(SRC|DON|SVC|QTA|SAL|SPC|RCP|RAL|BUD|FIX)-[0-9]{3,}$';
            ELSIF current_key = ANY(ARRAY[
                'from', 'to', 'starts_on', 'ends_on', 'accrual_on'
            ]::text[]) THEN
                RETURN text_value ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$';
            ELSIF current_key = ANY(ARRAY[
                'opening', 'inflows', 'outflows', 'closing',
                'session_pay_amount', 'charged_sessions', 'remaining_sessions',
                'planned_amount', 'consumed_amount', 'draft_commitment_amount',
                'available_amount', 'forecast_available_amount', 'amount'
            ]::text[]) THEN
                RETURN text_value ~ '^-?(0|[1-9][0-9]*)[.][0-9]{2}$';
            ELSIF current_key = ANY(ARRAY[
                'payload_sha256', 'projection_sha256'
            ]::text[]) THEN
                RETURN text_value ~ '^[0-9a-f]{64}$';
            ELSIF current_key = 'schema_version' THEN
                RETURN text_value = ANY(ARRAY[
                    'internal_grant_reconciliation_v1',
                    'internal_grant_reconciliation_evidence_v1'
                ]::text[]);
            ELSIF current_key = 'report_kind' THEN
                RETURN text_value = 'internal_grant_reconciliation_v1';
            ELSIF current_key = 'canonicalizer_version' THEN
                RETURN text_value = 'canonical-json-v1';
            ELSIF current_key = 'type' THEN
                RETURN text_value = ANY(ARRAY[
                    'personal', 'grant', 'sponsor', 'charity_fund',
                    'maternity_capital', 'certificate', 'test', 'individual',
                    'organization', 'foundation', 'vendor', 'other'
                ]::text[]);
            ELSIF current_key = 'category' THEN
                RETURN text_value = ANY(ARRAY[
                    'consultation', 'speech', 'defectology', 'physical',
                    'massage', 'group', 'other'
                ]::text[]);
            ELSIF current_key = 'unit' THEN
                RETURN text_value = ANY(ARRAY['sessions', 'money']::text[]);
            ELSIF current_key = 'enforcement_mode' THEN
                RETURN text_value = ANY(ARRAY['warning', 'hard']::text[]);
            ELSIF current_key = 'lifecycle_status' THEN
                RETURN text_value = ANY(ARRAY['active', 'closed']::text[]);
            ELSIF current_key = 'compensation_scope' THEN
                RETURN text_value = ANY(
                    ARRAY['service_delivery', 'project_role']::text[]
                );
            ELSIF current_key = 'accrual_kind' THEN
                RETURN text_value = ANY(ARRAY['appointment', 'grant_fixed']::text[]);
            ELSIF current_key = 'status' THEN
                RETURN text_value = ANY(ARRAY[
                    'draft', 'approved', 'paid', 'cancelled', 'passed'
                ]::text[]);
            ELSIF current_key = 'expense_type' THEN
                RETURN text_value = ANY(ARRAY[
                    'household', 'utilities', 'equipment', 'inventory', 'rent',
                    'services', 'admin_payroll', 'other'
                ]::text[]);
            ELSIF current_key = 'severity' THEN
                RETURN text_value = ANY(ARRAY['error', 'warning', 'info']::text[]);
            ELSIF current_key = 'result' THEN
                RETURN text_value = ANY(
                    ARRAY['passed', 'warning', 'blocked']::text[]
                );
            ELSIF current_key = 'kind' THEN
                RETURN text_value = ANY(ARRAY[
                    'funding_source', 'counterparty', 'service', 'service_quota',
                    'direct_service_quota', 'staff_allocation', 'staff',
                    'recipient', 'recipient_allocation', 'payroll_budget',
                    'fixed_position', 'appointment', 'appointment_participant',
                    'appointment_staff_assignment', 'balance_account',
                    'center_expense', 'expense_category', 'expense_split',
                    'ledger_entry', 'payroll_accrual', 'payroll_sheet',
                    'payroll_sheet_line'
                ]::text[]);
            ELSIF current_key = 'code' THEN
                RETURN text_value = ANY(ARRAY[
                    'participant_charge_without_account',
                    'appointment_charge_without_account',
                    'missing_debit_ledger',
                    'stale_legacy_charge_with_participants',
                    'stale_debit_ledger_without_charge_fact',
                    'ledger_account_participant_mismatch',
                    'ledger_appointment_participant_mismatch',
                    'mixed_funding_group',
                    'financial_integrity',
                    'grant_charge_missing_debit',
                    'grant_plan_integrity',
                    'grant_compensation_integrity',
                    'grant_hard_payroll_budget_exceeded',
                    'grant_payroll_line_accrual_mismatch',
                    'grant_expense_funding_unbalanced',
                    'grant_balance_unit_integrity',
                    'grant_payroll_budget_forecast_overage',
                    'grant_negative_period_closing_balance',
                    'payroll_sheet_line_amount_mismatch',
                    'quota_current_revision_not_terminal',
                    'quota_current_revision_wrong_root',
                    'quota_missing_current_revision',
                    'quota_overallocated',
                    'quota_projection_mismatch',
                    'staff_allocation_period_overlap',
                    'staff_current_revision_not_terminal',
                    'staff_current_revision_wrong_root',
                    'staff_missing_current_revision',
                    'staff_projection_mismatch',
                    'grant_fixed_current_revision_not_terminal',
                    'grant_fixed_current_revision_wrong_root',
                    'grant_fixed_missing_current_revision',
                    'grant_fixed_outside_budget',
                    'grant_fixed_period_overlap',
                    'grant_fixed_projection_mismatch',
                    'grant_fixed_staff_allocation_overlap',
                    'grant_fixed_wrong_budget_revision',
                    'payroll_budget_current_revision_not_terminal',
                    'payroll_budget_current_revision_wrong_root',
                    'payroll_budget_missing_current_revision',
                    'payroll_budget_period_overlap',
                    'payroll_budget_projection_mismatch'
                ]::text[]);
            END IF;
            RETURN false;
        END;
        $values$;

        CREATE OR REPLACE FUNCTION operations_donor_snapshot_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            report_current_snapshot_id bigint;
            previous_report_id bigint;
            previous_snapshot_number integer;
            previous_payload_sha256 text;
        BEGIN
            IF TG_OP IN ('UPDATE', 'DELETE') THEN
                RAISE EXCEPTION 'Donor report snapshots are immutable.'
                    USING ERRCODE = '23514';
            END IF;

            IF NEW.snapshot_schema_version <> 'internal_grant_reconciliation_v1' THEN
                RAISE EXCEPTION 'Unsupported donor report snapshot schema version.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.canonicalizer_version <> 'canonical-json-v1' THEN
                RAISE EXCEPTION 'Unsupported donor report canonicalizer version.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.actor_role_snapshot <> 'director'
               OR char_length(btrim(NEW.reason)) < 5 THEN
                RAISE EXCEPTION 'Donor report snapshot requires a director and reason.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.payload_sha256 !~ '^[0-9a-f]{64}$'
               OR NEW.evidence_manifest_sha256 !~ '^[0-9a-f]{64}$' THEN
                RAISE EXCEPTION 'Donor report snapshot hashes must be SHA-256 hex.'
                    USING ERRCODE = '23514';
            END IF;
            IF encode(
                    sha256(convert_to(operations_canonical_jsonb(NEW.payload), 'UTF8')),
                    'hex'
               ) IS DISTINCT FROM NEW.payload_sha256
               OR encode(
                    sha256(
                        convert_to(
                            operations_canonical_jsonb(NEW.evidence_manifest),
                            'UTF8'
                        )
                    ),
                    'hex'
               ) IS DISTINCT FROM NEW.evidence_manifest_sha256 THEN
                RAISE EXCEPTION 'Donor report snapshot hash verification failed.'
                    USING ERRCODE = '23514';
            END IF;
            IF NOT operations_jsonb_keys_allowed(
                    NEW.payload,
                    ARRAY[
                        'schema_version', 'report', 'balances', 'quotas',
                        'recipient_allocations', 'payroll', 'expenses', 'integrity',
                        'report_kind', 'period', 'funding_source', 'donor', 'from',
                        'to', 'ref', 'type', 'unit', 'opening', 'inflows', 'outflows',
                        'closing', 'appointment_count', 'planned_count',
                        'completed_count', 'service', 'planned_sessions',
                        'allocated_sessions', 'charged_sessions', 'remaining_sessions',
                        'staff_allocations', 'category', 'staff_ref',
                        'session_pay_amount', 'recipient_ref', 'budgets',
                        'fixed_positions', 'accrual_totals', 'budget_ref', 'starts_on',
                        'ends_on', 'planned_amount', 'enforcement_mode',
                        'lifecycle_status', 'consumed_amount',
                        'draft_commitment_amount', 'available_amount',
                        'forecast_available_amount', 'fixed_ref',
                        'compensation_scope', 'accrual_on', 'amount', 'accrual_kind',
                        'status', 'count', 'expense_type', 'warnings', 'code',
                        'severity', 'object_ref'
                    ]::text[]
               )
               OR NOT operations_jsonb_keys_allowed(
                    NEW.evidence_manifest,
                    ARRAY[
                        'schema_version', 'canonicalizer_version', 'payload_sha256',
                        'aliases', 'sources', 'preflight', 'source_sets', 'kind',
                        'ref', 'source_pk', 'active', 'revision_pk',
                        'projection_sha256', 'code', 'severity', 'result', 'count',
                        'payroll_period_accrual_ids', 'payroll_line_ids',
                        'payroll_sheet_ids', 'expense_category_ids'
                    ]::text[]
               )
               OR NOT operations_donor_json_values_allowed(NEW.payload)
               OR NOT operations_donor_json_values_allowed(
                    NEW.evidence_manifest
               ) THEN
                RAISE EXCEPTION
                    'Donor report snapshot contains a forbidden JSON key or value.'
                    USING ERRCODE = '23514';
            END IF;
            IF jsonb_typeof(NEW.payload) <> 'object'
               OR jsonb_typeof(NEW.evidence_manifest) <> 'object'
               OR NEW.payload ->> 'schema_version'
                  IS DISTINCT FROM 'internal_grant_reconciliation_v1'
               OR NEW.payload -> 'report' ->> 'report_kind'
                  IS DISTINCT FROM 'internal_grant_reconciliation_v1'
               OR NEW.evidence_manifest ->> 'schema_version'
                  IS DISTINCT FROM 'internal_grant_reconciliation_evidence_v1'
               OR NEW.evidence_manifest ->> 'canonicalizer_version'
                  IS DISTINCT FROM 'canonical-json-v1'
               OR NEW.evidence_manifest ->> 'payload_sha256'
                  IS DISTINCT FROM NEW.payload_sha256 THEN
                RAISE EXCEPTION 'Donor report snapshot JSON envelope is invalid.'
                    USING ERRCODE = '23514';
            END IF;

            SELECT report.current_snapshot_id
            INTO report_current_snapshot_id
            FROM operations_donorreport AS report
            WHERE report.id = NEW.report_id;

            IF NOT FOUND THEN
                RAISE EXCEPTION 'Donor report root does not exist.'
                    USING ERRCODE = '23503';
            END IF;

            IF NEW.supersedes_id IS NULL THEN
                IF NEW.event_type <> 'closed'
                   OR NEW.snapshot_number <> 1
                   OR report_current_snapshot_id IS NOT NULL THEN
                    RAISE EXCEPTION 'Invalid first donor report snapshot.'
                        USING ERRCODE = '23514';
                END IF;
            ELSE
                SELECT
                    previous.report_id,
                    previous.snapshot_number,
                    previous.payload_sha256
                INTO
                    previous_report_id,
                    previous_snapshot_number,
                    previous_payload_sha256
                FROM operations_donorreportsnapshot AS previous
                WHERE previous.id = NEW.supersedes_id;

                IF NOT FOUND
                   OR previous_report_id <> NEW.report_id
                   OR NEW.event_type <> 'corrected'
                   OR NEW.snapshot_number <> previous_snapshot_number + 1
                   OR NEW.payload_sha256 = previous_payload_sha256
                   OR report_current_snapshot_id IS DISTINCT FROM NEW.supersedes_id THEN
                    RAISE EXCEPTION 'Invalid donor report snapshot successor.'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_donor_snapshot_guard_trigger
        BEFORE INSERT OR UPDATE OR DELETE
        ON operations_donorreportsnapshot
        FOR EACH ROW
        EXECUTE FUNCTION operations_donor_snapshot_guard();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_donor_report_root_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            next_report_id bigint;
            next_supersedes_id bigint;
            next_snapshot_number integer;
            previous_snapshot_number integer;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'Donor report roots cannot be deleted.'
                    USING ERRCODE = '23514';
            END IF;
            IF TG_OP = 'INSERT' THEN
                IF NEW.current_snapshot_id IS NOT NULL THEN
                    RAISE EXCEPTION 'A donor report root must start without a snapshot.'
                        USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END IF;

            IF NEW.funding_source_id IS DISTINCT FROM OLD.funding_source_id
               OR NEW.counterparty_id IS DISTINCT FROM OLD.counterparty_id
               OR NEW.date_from IS DISTINCT FROM OLD.date_from
               OR NEW.date_to IS DISTINCT FROM OLD.date_to
               OR NEW.report_kind IS DISTINCT FROM OLD.report_kind
               OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
                RAISE EXCEPTION 'Donor report identity is immutable.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.current_snapshot_id IS NOT DISTINCT FROM OLD.current_snapshot_id THEN
                RETURN NEW;
            END IF;
            IF NEW.current_snapshot_id IS NULL THEN
                RAISE EXCEPTION 'Donor report current snapshot cannot be cleared.'
                    USING ERRCODE = '23514';
            END IF;

            SELECT snapshot.report_id, snapshot.supersedes_id, snapshot.snapshot_number
            INTO next_report_id, next_supersedes_id, next_snapshot_number
            FROM operations_donorreportsnapshot AS snapshot
            WHERE snapshot.id = NEW.current_snapshot_id;

            IF NOT FOUND OR next_report_id <> OLD.id THEN
                RAISE EXCEPTION 'Current snapshot must belong to this donor report.'
                    USING ERRCODE = '23514';
            END IF;
            IF OLD.current_snapshot_id IS NULL THEN
                IF next_supersedes_id IS NOT NULL OR next_snapshot_number <> 1 THEN
                    RAISE EXCEPTION 'The first current snapshot must start the chain.'
                        USING ERRCODE = '23514';
                END IF;
            ELSE
                SELECT snapshot.snapshot_number
                INTO previous_snapshot_number
                FROM operations_donorreportsnapshot AS snapshot
                WHERE snapshot.id = OLD.current_snapshot_id;

                IF next_supersedes_id IS DISTINCT FROM OLD.current_snapshot_id
                   OR next_snapshot_number <> previous_snapshot_number + 1 THEN
                    RAISE EXCEPTION 'Current snapshot must advance to a direct successor.'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_donor_report_root_guard_trigger
        BEFORE INSERT OR UPDATE OR DELETE
        ON operations_donorreport
        FOR EACH ROW
        EXECUTE FUNCTION operations_donor_report_root_guard();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_donor_report_terminal_state()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            root_id bigint;
        BEGIN
            IF TG_TABLE_NAME = 'operations_donorreport' THEN
                root_id := NEW.id;
            ELSE
                root_id := NEW.report_id;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM operations_donorreport AS report
                JOIN operations_donorreportsnapshot AS snapshot
                  ON snapshot.id = report.current_snapshot_id
                WHERE report.id = root_id
                  AND snapshot.report_id = report.id
                  AND NOT EXISTS (
                      SELECT 1
                      FROM operations_donorreportsnapshot AS successor
                      WHERE successor.supersedes_id = snapshot.id
                  )
            ) THEN
                RAISE EXCEPTION
                    'Donor report current snapshot must be the terminal chain node.'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER operations_donor_report_terminal_guard
        AFTER INSERT OR UPDATE ON operations_donorreport
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_donor_report_terminal_state();

        CREATE CONSTRAINT TRIGGER operations_donor_snapshot_terminal_guard
        AFTER INSERT ON operations_donorreportsnapshot
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_donor_report_terminal_state();
        """
    )


def drop_donor_report_triggers(apps, schema_editor):
    DonorReport = apps.get_model('operations', 'DonorReport')
    DonorReportSnapshot = apps.get_model('operations', 'DonorReportSnapshot')
    if DonorReport.objects.exists() or DonorReportSnapshot.objects.exists():
        raise RuntimeError(
            'Cannot reverse donor report snapshot migration while immutable history exists.'
        )
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_donor_snapshot_terminal_guard
            ON operations_donorreportsnapshot;
        DROP TRIGGER IF EXISTS operations_donor_report_terminal_guard
            ON operations_donorreport;
        DROP FUNCTION IF EXISTS operations_validate_donor_report_terminal_state();
        DROP TRIGGER IF EXISTS operations_donor_report_root_guard_trigger
            ON operations_donorreport;
        DROP FUNCTION IF EXISTS operations_donor_report_root_guard();
        DROP TRIGGER IF EXISTS operations_donor_snapshot_guard_trigger
            ON operations_donorreportsnapshot;
        DROP FUNCTION IF EXISTS operations_donor_snapshot_guard();
        DROP FUNCTION IF EXISTS operations_donor_json_values_allowed(jsonb, text);
        DROP FUNCTION IF EXISTS operations_jsonb_keys_allowed(jsonb, text[]);
        DROP FUNCTION IF EXISTS operations_canonical_jsonb(jsonb);
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0052_grant_fixed_payroll_tighten'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('date_from', models.DateField(verbose_name='период с')),
                ('date_to', models.DateField(verbose_name='период по')),
                ('report_kind', models.CharField(choices=[('internal_grant_reconciliation_v1', 'Внутренняя сверка грантового проекта')], default='internal_grant_reconciliation_v1', max_length=50, verbose_name='вид отчета')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor_reports', to='operations.counterparty', verbose_name='донор / контрагент')),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_reports', to='operations.fundingsource', verbose_name='источник финансирования')),
            ],
            options={
                'verbose_name': 'закрытый отчет донору',
                'verbose_name_plural': 'закрытые отчеты донорам',
                'ordering': ['-date_to', '-date_from', 'funding_source__name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DonorReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('snapshot_number', models.PositiveIntegerField(verbose_name='номер снимка')),
                ('event_type', models.CharField(choices=[('closed', 'Закрыт'), ('corrected', 'Исправлен')], max_length=20, verbose_name='событие')),
                ('snapshot_schema_version', models.CharField(max_length=64, verbose_name='версия схемы')),
                ('canonicalizer_version', models.CharField(max_length=32, verbose_name='версия канонизации')),
                ('payload', models.JSONField(verbose_name='закрытый payload')),
                ('evidence_manifest', models.JSONField(verbose_name='закрытый манифест доказательств')),
                ('payload_sha256', models.CharField(max_length=64, verbose_name='SHA-256 payload')),
                ('evidence_manifest_sha256', models.CharField(max_length=64, verbose_name='SHA-256 манифеста')),
                ('data_as_of', models.DateTimeField(verbose_name='данные по состоянию на')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель')], max_length=20, verbose_name='роль на момент закрытия')),
                ('reason', models.TextField(verbose_name='основание')),
                ('closed_at', models.DateTimeField(verbose_name='время закрытия')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closed_donor_report_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='закрыл отчет')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='operations.donorreport', verbose_name='отчет')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.donorreportsnapshot', verbose_name='предыдущий снимок')),
            ],
            options={
                'verbose_name': 'неизменяемый снимок отчета донору',
                'verbose_name_plural': 'неизменяемые снимки отчетов донорам',
                'ordering': ['report_id', '-snapshot_number'],
            },
        ),
        migrations.AddField(
            model_name='donorreport',
            name='current_snapshot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_donor_report', to='operations.donorreportsnapshot', verbose_name='текущий снимок'),
        ),
        migrations.AddIndex(
            model_name='donorreportsnapshot',
            index=models.Index(fields=['report', '-closed_at'], name='donor_snapshot_report_closed'),
        ),
        migrations.AddIndex(
            model_name='donorreportsnapshot',
            index=models.Index(fields=['payload_sha256'], name='donor_snapshot_payload_hash'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.UniqueConstraint(fields=('report', 'snapshot_number'), name='unique_donor_report_snapshot_number'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_donor_report_snapshot_successor'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('snapshot_number__gte', 1)), name='donor_report_snapshot_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'closed'), ('snapshot_number', 1), ('supersedes__isnull', True)), models.Q(('event_type', 'corrected'), ('snapshot_number__gt', 1), ('supersedes__isnull', False)), _connector='OR'), name='donor_report_snapshot_chain_event'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('actor_role_snapshot', 'director')), name='donor_report_snapshot_director_actor'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='donor_report_snapshot_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__gte', models.F('data_as_of'))), name='donor_report_snapshot_time_order'),
        ),
        migrations.AddIndex(
            model_name='donorreport',
            index=models.Index(fields=['funding_source', 'date_from', 'date_to', 'report_kind'], name='donor_report_source_period'),
        ),
        migrations.AddIndex(
            model_name='donorreport',
            index=models.Index(fields=['counterparty', 'date_to'], name='donor_report_donor_period'),
        ),
        migrations.AddConstraint(
            model_name='donorreport',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='donor_report_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='donorreport',
            constraint=models.UniqueConstraint(fields=('funding_source', 'counterparty', 'date_from', 'date_to', 'report_kind'), name='unique_donor_report_identity', nulls_distinct=False),
        ),
        migrations.RunPython(
            create_donor_report_triggers,
            drop_donor_report_triggers,
        ),
    ]
