# Generated by Django 5.2.14 on 2026-08-01 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_donor_submission_triggers(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION public.operations_donor_submission_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            snapshot_closed_at timestamptz;
            previous_snapshot_id bigint;
            previous_submission_number integer;
            previous_file_sha256 text;
            previous_recorded_at timestamptz;
            expected_extension text;
            expected_storage_key text;
            database_clock timestamptz;
        BEGIN
            IF TG_OP IN ('UPDATE', 'DELETE') THEN
                RAISE EXCEPTION 'Donor report submissions are immutable.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.actor_role_snapshot <> 'director'
               OR NEW.reason IS DISTINCT FROM normalize(NEW.reason, NFKC)
               OR (
                    replace(NEW.reason, E'\\n', '') ~ '[[:cntrl:]]'
                  )
               OR NEW.reason ~ U&'[\\00AD\\0600-\\0605\\061C\\06DD\\070F\\0890-\\0891\\08E2\\180E]'
               OR NEW.reason ~ U&'[\\200B-\\200F\\202A-\\202E\\2060-\\2064\\2066-\\206F\\FEFF\\FFF9-\\FFFB]'
               OR NEW.reason ~ U&'[\\+0110BD\\+0110CD\\+013430-\\+01343F]'
               OR NEW.reason ~ U&'[\\+01BCA0-\\+01BCA3\\+01D173-\\+01D17A]'
               OR NEW.reason ~ U&'[\\+0E0001\\+0E0020-\\+0E007F]'
               OR char_length(
                    regexp_replace(
                        NEW.reason,
                        '^[[:space:]]+|[[:space:]]+$',
                        '',
                        'g'
                    )
                  ) < 5 THEN
                RAISE EXCEPTION 'Donor report submission requires a director and reason.'
                    USING ERRCODE = '23514';
            END IF;
            IF NOT EXISTS (
                SELECT 1
                FROM public.auth_user AS actor
                WHERE actor.id = NEW.actor_id
                  AND actor.is_active
                  AND (
                      actor.is_superuser
                      OR EXISTS (
                          SELECT 1
                          FROM public.auth_user_groups AS membership
                          JOIN public.auth_group AS role_group
                            ON role_group.id = membership.group_id
                          WHERE membership.user_id = actor.id
                            AND role_group.name IN ('Руководители', 'Руководитель')
                      )
                  )
            ) THEN
                RAISE EXCEPTION 'Donor report submission actor is not a director.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.file_sha256 !~ '^[0-9a-f]{64}$'
               OR NEW.file_size < 1
               OR NEW.file_size > 26214400 THEN
                RAISE EXCEPTION 'Donor report submission file metadata is invalid.'
                    USING ERRCODE = '23514';
            END IF;
            IF btrim(NEW.original_filename) = ''
               OR NEW.original_filename ~ '[[:cntrl:]/]'
               OR NEW.original_filename ~ U&'[\\00AD\\0600-\\0605\\061C\\06DD\\070F\\0890-\\0891\\08E2\\180E]'
               OR NEW.original_filename ~ U&'[\\200B-\\200F\\202A-\\202E\\2060-\\2064\\2066-\\206F\\FEFF\\FFF9-\\FFFB]'
               OR NEW.original_filename ~ U&'[\\+0110BD\\+0110CD\\+013430-\\+01343F]'
               OR NEW.original_filename ~ U&'[\\+01BCA0-\\+01BCA3\\+01D173-\\+01D17A]'
               OR NEW.original_filename ~ U&'[\\+0E0001\\+0E0020-\\+0E007F]'
               OR position(chr(92) in NEW.original_filename) > 0
               OR NEW.external_reference ~ E'[\\n\\r]' THEN
                RAISE EXCEPTION 'Donor report submission text metadata is invalid.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.submission_number < 1 OR NEW.submission_number > 999999 THEN
                RAISE EXCEPTION 'Donor report submission number is invalid.'
                    USING ERRCODE = '23514';
            END IF;

            expected_extension := CASE NEW.content_type
                WHEN 'application/pdf' THEN 'pdf'
                WHEN 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
                    THEN 'docx'
                WHEN 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
                    THEN 'xlsx'
                WHEN 'application/vnd.oasis.opendocument.text' THEN 'odt'
                WHEN 'application/vnd.oasis.opendocument.spreadsheet' THEN 'ods'
                ELSE NULL
            END;
            IF expected_extension IS NULL THEN
                RAISE EXCEPTION 'Donor report submission MIME is not allowed.'
                    USING ERRCODE = '23514';
            END IF;
            IF right(
                    lower(NEW.original_filename),
                    char_length(expected_extension) + 1
               ) <> '.' || expected_extension THEN
                RAISE EXCEPTION 'Donor report submission filename extension is invalid.'
                    USING ERRCODE = '23514';
            END IF;
            expected_storage_key :=
                'donor-report-submissions/snapshot-'
                || NEW.report_snapshot_id::text
                || '/submission-'
                || lpad(NEW.submission_number::text, 6, '0')
                || '/'
                || NEW.file_sha256
                || '.'
                || expected_extension;
            IF NEW.storage_key IS DISTINCT FROM expected_storage_key THEN
                RAISE EXCEPTION 'Donor report submission storage key is invalid.'
                    USING ERRCODE = '23514';
            END IF;

            SELECT snapshot.closed_at
            INTO snapshot_closed_at
            FROM public.operations_donorreportsnapshot AS snapshot
            JOIN public.operations_donorreport AS report
              ON report.id = snapshot.report_id
            WHERE snapshot.id = NEW.report_snapshot_id
            FOR UPDATE OF report;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Donor report snapshot does not exist.'
                    USING ERRCODE = '23503';
            END IF;
            database_clock := clock_timestamp();
            IF NEW.recorded_at < database_clock - interval '5 minutes'
               OR NEW.recorded_at > database_clock + interval '5 seconds'
               OR NEW.recorded_at < snapshot_closed_at
               OR NEW.submitted_on
                    < (snapshot_closed_at AT TIME ZONE 'Asia/Vladivostok')::date
               OR NEW.submitted_on
                    > (NEW.recorded_at AT TIME ZONE 'Asia/Vladivostok')::date THEN
                RAISE EXCEPTION 'Donor report submission predates its snapshot.'
                    USING ERRCODE = '23514';
            END IF;

            IF NEW.supersedes_id IS NULL THEN
                IF NEW.event_type <> 'submitted'
                   OR NEW.submission_number <> 1
                   OR EXISTS (
                       SELECT 1
                       FROM public.operations_donorreportsubmission AS existing
                       WHERE existing.report_snapshot_id = NEW.report_snapshot_id
                   ) THEN
                    RAISE EXCEPTION 'Invalid first donor report submission.'
                        USING ERRCODE = '23514';
                END IF;
            ELSE
                SELECT
                    previous.report_snapshot_id,
                    previous.submission_number,
                    previous.file_sha256,
                    previous.recorded_at
                INTO
                    previous_snapshot_id,
                    previous_submission_number,
                    previous_file_sha256,
                    previous_recorded_at
                FROM public.operations_donorreportsubmission AS previous
                WHERE previous.id = NEW.supersedes_id;
                IF NOT FOUND
                   OR previous_snapshot_id <> NEW.report_snapshot_id
                   OR NEW.event_type <> 'replaced'
                   OR NEW.submission_number <> previous_submission_number + 1
                   OR NEW.file_sha256 = previous_file_sha256
                   OR NEW.recorded_at < previous_recorded_at
                   OR EXISTS (
                       SELECT 1
                       FROM public.operations_donorreportsubmission AS successor
                       WHERE successor.supersedes_id = NEW.supersedes_id
                   ) THEN
                    RAISE EXCEPTION 'Invalid donor report submission successor.'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_donor_submission_guard_trigger
        BEFORE INSERT OR UPDATE OR DELETE
        ON public.operations_donorreportsubmission
        FOR EACH ROW
        EXECUTE FUNCTION public.operations_donor_submission_guard();

        CREATE OR REPLACE FUNCTION public.operations_donor_submission_access_guard()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            submission_hash text;
            submission_recorded_at timestamptz;
            database_clock timestamptz;
        BEGIN
            IF TG_OP IN ('UPDATE', 'DELETE') THEN
                RAISE EXCEPTION 'Donor report submission access events are immutable.'
                    USING ERRCODE = '23514';
            END IF;
            IF NOT (
                (
                    NEW.actor_role_snapshot = 'director'
                    AND NEW.permission_basis = 'director_role'
                )
                OR (
                    NEW.actor_role_snapshot = 'administrator'
                    AND NEW.permission_basis = 'explicit_permission'
                )
            ) THEN
                RAISE EXCEPTION 'Donor report submission access authority is invalid.'
                    USING ERRCODE = '23514';
            END IF;
            IF NEW.actor_role_snapshot = 'director' THEN
                IF NOT EXISTS (
                    SELECT 1
                    FROM public.auth_user AS actor
                    WHERE actor.id = NEW.actor_id
                      AND actor.is_active
                      AND (
                          actor.is_superuser
                          OR EXISTS (
                              SELECT 1
                              FROM public.auth_user_groups AS membership
                              JOIN public.auth_group AS role_group
                                ON role_group.id = membership.group_id
                              WHERE membership.user_id = actor.id
                                AND role_group.name IN ('Руководители', 'Руководитель')
                          )
                      )
                ) THEN
                    RAISE EXCEPTION 'Donor report access actor is not a director.'
                        USING ERRCODE = '23514';
                END IF;
            ELSE
                IF NOT EXISTS (
                    SELECT 1
                    FROM public.auth_user AS actor
                    WHERE actor.id = NEW.actor_id
                      AND actor.is_active
                      AND NOT actor.is_superuser
                      AND NOT EXISTS (
                          SELECT 1
                          FROM public.auth_user_groups AS membership
                          JOIN public.auth_group AS role_group
                            ON role_group.id = membership.group_id
                          WHERE membership.user_id = actor.id
                            AND role_group.name IN ('Руководители', 'Руководитель')
                      )
                      AND (
                          actor.is_staff
                          OR EXISTS (
                              SELECT 1
                              FROM public.auth_user_groups AS membership
                              JOIN public.auth_group AS role_group
                                ON role_group.id = membership.group_id
                              WHERE membership.user_id = actor.id
                                AND role_group.name IN ('Администраторы', 'Администратор')
                          )
                      )
                      AND NOT EXISTS (
                          SELECT 1
                          FROM public.operations_staffmember AS staff
                          WHERE staff.user_id = actor.id
                      )
                      AND EXISTS (
                          SELECT 1
                          FROM public.auth_permission AS permission
                          JOIN public.django_content_type AS content_type
                            ON content_type.id = permission.content_type_id
                          WHERE permission.codename = 'download_donorreportsubmission'
                            AND content_type.app_label = 'operations'
                            AND content_type.model = 'donorreportsubmission'
                            AND (
                                EXISTS (
                                    SELECT 1
                                    FROM public.auth_user_user_permissions AS direct_permission
                                    WHERE direct_permission.user_id = actor.id
                                      AND direct_permission.permission_id = permission.id
                                )
                                OR EXISTS (
                                    SELECT 1
                                    FROM public.auth_user_groups AS membership
                                    JOIN public.auth_group_permissions AS group_permission
                                      ON group_permission.group_id = membership.group_id
                                    WHERE membership.user_id = actor.id
                                      AND group_permission.permission_id = permission.id
                                )
                            )
                      )
                ) THEN
                    RAISE EXCEPTION 'Donor report access actor lacks permission.'
                        USING ERRCODE = '23514';
                END IF;
            END IF;
            SELECT submission.file_sha256, submission.recorded_at
            INTO submission_hash, submission_recorded_at
            FROM public.operations_donorreportsubmission AS submission
            WHERE submission.id = NEW.submission_id;
            IF NOT FOUND THEN
                RAISE EXCEPTION 'Donor report submission does not exist.'
                    USING ERRCODE = '23503';
            END IF;
            database_clock := clock_timestamp();
            IF NEW.accessed_at < database_clock - interval '5 minutes'
               OR NEW.accessed_at > database_clock + interval '5 seconds'
               OR NEW.verified_sha256 IS DISTINCT FROM submission_hash
               OR NEW.accessed_at < submission_recorded_at THEN
                RAISE EXCEPTION 'Donor report submission access proof is invalid.'
                    USING ERRCODE = '23514';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_donor_submission_access_guard_trigger
        BEFORE INSERT OR UPDATE OR DELETE
        ON public.operations_donorreportsubmissionaccess
        FOR EACH ROW
        EXECUTE FUNCTION public.operations_donor_submission_access_guard();
        """
    )


def drop_donor_submission_triggers(apps, schema_editor):
    DonorReportSubmission = apps.get_model('operations', 'DonorReportSubmission')
    DonorReportSubmissionAccess = apps.get_model(
        'operations',
        'DonorReportSubmissionAccess',
    )
    if DonorReportSubmission.objects.exists() or DonorReportSubmissionAccess.objects.exists():
        raise RuntimeError(
            'Cannot reverse donor report submission migration while immutable history exists.'
        )
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_donor_submission_access_guard_trigger
            ON public.operations_donorreportsubmissionaccess;
        DROP FUNCTION IF EXISTS public.operations_donor_submission_access_guard();
        DROP TRIGGER IF EXISTS operations_donor_submission_guard_trigger
            ON public.operations_donorreportsubmission;
        DROP FUNCTION IF EXISTS public.operations_donor_submission_guard();
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0053_donor_report_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorReportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('submission_number', models.PositiveIntegerField(verbose_name='номер сдачи')),
                ('event_type', models.CharField(choices=[('submitted', 'Сдан'), ('replaced', 'Заменен')], max_length=20, verbose_name='событие')),
                ('storage_key', models.CharField(max_length=320, unique=True, verbose_name='приватный storage key')),
                ('original_filename', models.CharField(max_length=255, verbose_name='исходное имя файла')),
                ('content_type', models.CharField(max_length=120, verbose_name='проверенный MIME')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='размер файла')),
                ('file_sha256', models.CharField(max_length=64, verbose_name='SHA-256 файла')),
                ('submitted_on', models.DateField(verbose_name='фактическая дата сдачи')),
                ('recorded_at', models.DateTimeField(verbose_name='техническое время записи')),
                ('external_reference', models.CharField(blank=True, max_length=500, verbose_name='внешний номер / ссылка')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель')], max_length=20, verbose_name='роль на момент сдачи')),
                ('reason', models.TextField(verbose_name='основание')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_report_submissions', to=settings.AUTH_USER_MODEL, verbose_name='зафиксировал сдачу')),
                ('report_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='operations.donorreportsnapshot', verbose_name='снимок отчета')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.donorreportsubmission', verbose_name='предыдущая сдача')),
            ],
            options={
                'verbose_name': 'неизменяемый факт сдачи отчета',
                'verbose_name_plural': 'неизменяемые факты сдачи отчетов',
                'ordering': ['report_snapshot_id', '-submission_number'],
                'permissions': [('download_donorreportsubmission', 'Может скачивать приватные файлы сдачи отчетов')],
                'default_permissions': ('view',),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DonorReportSubmissionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор')], max_length=20, verbose_name='роль на момент доступа')),
                ('permission_basis', models.CharField(choices=[('director_role', 'Роль руководителя'), ('explicit_permission', 'Отдельное разрешение')], max_length=30, verbose_name='основание доступа')),
                ('verified_sha256', models.CharField(max_length=64, verbose_name='проверенный SHA-256')),
                ('accessed_at', models.DateTimeField(verbose_name='время выдачи')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donor_report_submission_accesses', to=settings.AUTH_USER_MODEL, verbose_name='получил файл')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_events', to='operations.donorreportsubmission', verbose_name='сдача отчета')),
            ],
            options={
                'verbose_name': 'факт выдачи сдачи отчета',
                'verbose_name_plural': 'факты выдачи сдач отчетов',
                'ordering': ['-accessed_at', '-pk'],
                'default_permissions': ('view',),
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='donorreportsubmission',
            index=models.Index(fields=['report_snapshot', '-recorded_at'], name='donor_submission_snapshot_time'),
        ),
        migrations.AddIndex(
            model_name='donorreportsubmission',
            index=models.Index(fields=['file_sha256'], name='donor_submission_file_hash'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.UniqueConstraint(fields=('report_snapshot', 'submission_number'), name='unique_donor_submission_number'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_donor_submission_successor'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('submission_number__gte', 1)), name='donor_submission_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('submission_number__lte', 999999)), name='donor_submission_number_bounded'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 1)), name='donor_submission_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__lte', 26214400)), name='donor_submission_size_bounded'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'submitted'), ('submission_number', 1), ('supersedes__isnull', True)), models.Q(('event_type', 'replaced'), ('submission_number__gt', 1), ('supersedes__isnull', False)), _connector='OR'), name='donor_submission_chain_event'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('actor_role_snapshot', 'director')), name='donor_submission_director_actor'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['application/pdf', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.spreadsheet'])), name='donor_submission_mime_allowed'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmission',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='donor_submission_reason_required'),
        ),
        migrations.AddIndex(
            model_name='donorreportsubmissionaccess',
            index=models.Index(fields=['submission', '-accessed_at'], name='donor_access_submission_time'),
        ),
        migrations.AddIndex(
            model_name='donorreportsubmissionaccess',
            index=models.Index(fields=['actor', '-accessed_at'], name='donor_access_actor_time'),
        ),
        migrations.AddIndex(
            model_name='donorreportsubmissionaccess',
            index=models.Index(fields=['-accessed_at'], name='donor_access_time'),
        ),
        migrations.AddConstraint(
            model_name='donorreportsubmissionaccess',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot', 'director'), ('permission_basis', 'director_role')), models.Q(('actor_role_snapshot', 'administrator'), ('permission_basis', 'explicit_permission')), _connector='OR'), name='donor_submission_access_authority'),
        ),
        migrations.RunPython(
            create_donor_submission_triggers,
            drop_donor_submission_triggers,
        ),
    ]
