# Generated by Django 5.2.14 on 2026-08-28 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def populate_operation_keys(apps, schema_editor):
    AppointmentSeries = apps.get_model('operations', 'AppointmentSeries')
    for series_id in AppointmentSeries.objects.filter(operation_key__isnull=True).values_list(
        'pk', flat=True
    ).iterator():
        AppointmentSeries.objects.filter(pk=series_id).update(operation_key=uuid.uuid4())


def clear_operation_keys(apps, schema_editor):
    AppointmentSeries = apps.get_model('operations', 'AppointmentSeries')
    AppointmentSeries.objects.update(operation_key=None)


def assert_participant_sequences_unique(apps, schema_editor):
    AppointmentParticipant = apps.get_model('operations', 'AppointmentParticipant')
    duplicates = list(
        AppointmentParticipant.objects.filter(
            program_block__isnull=False,
            sequence_number__isnull=False,
        )
        .exclude(appointment_status__in=['cancelled', 'rescheduled'])
        .values('program_block_id', 'sequence_number')
        .annotate(row_count=Count('pk'))
        .filter(row_count__gt=1)
        .order_by('program_block_id', 'sequence_number')[:20]
    )
    if duplicates:
        sample = ', '.join(
            f"block={row['program_block_id']} number={row['sequence_number']} "
            f"rows={row['row_count']}"
            for row in duplicates
        )
        raise RuntimeError(
            'Duplicate program-block participant sequence numbers must be resolved '
            f'before migration 0055: {sample}'
        )


def assert_legacy_series_occurrences_unique(apps, schema_editor):
    Appointment = apps.get_model('operations', 'Appointment')
    duplicates = list(
        Appointment.objects.filter(series__isnull=False)
        .values('series_id', 'starts_at')
        .annotate(row_count=Count('pk'))
        .filter(row_count__gt=1)
        .order_by('series_id', 'starts_at')[:20]
    )
    if duplicates:
        sample = ', '.join(
            f"series={row['series_id']} starts_at={row['starts_at']} rows={row['row_count']}"
            for row in duplicates
        )
        raise RuntimeError(
            'Duplicate legacy series occurrence times must be resolved before migration 0055: '
            f'{sample}'
        )


def backfill_legacy_series(apps, schema_editor):
    AppointmentSeries = apps.get_model('operations', 'AppointmentSeries')
    AppointmentSeriesParticipant = apps.get_model(
        'operations', 'AppointmentSeriesParticipant'
    )
    AppointmentSeriesStaffAssignment = apps.get_model(
        'operations', 'AppointmentSeriesStaffAssignment'
    )
    AppointmentSeriesOccurrence = apps.get_model(
        'operations', 'AppointmentSeriesOccurrence'
    )
    Appointment = apps.get_model('operations', 'Appointment')
    ProgramBlock = apps.get_model('operations', 'ProgramBlock')

    AppointmentSeries.objects.update(default_appointment_status='confirmed')
    group_series_ids = Appointment.objects.filter(
        series__isnull=False,
        session_type='group',
    ).values_list('series_id', flat=True)
    AppointmentSeries.objects.filter(pk__in=group_series_ids).update(session_type='group')
    block_accounts = dict(ProgramBlock.objects.values_list('pk', 'balance_account_id'))
    for series in AppointmentSeries.objects.order_by('pk').iterator():
        AppointmentSeriesParticipant.objects.get_or_create(
            series_id=series.pk,
            child_id=series.child_id,
            defaults={
                'program_block_id': series.program_block_id,
                'billing_account_id': block_accounts.get(series.program_block_id),
                'position': 1,
            },
        )
        AppointmentSeriesStaffAssignment.objects.get_or_create(
            series_id=series.pk,
            staff_member_id=series.staff_member_id,
            defaults={'role': 'primary'},
        )

    occurrences = []
    for appointment in Appointment.objects.filter(series__isnull=False).order_by('pk').iterator():
        occurrences.append(
            AppointmentSeriesOccurrence(
                series_id=appointment.series_id,
                scheduled_starts_at=appointment.starts_at,
                appointment_id=appointment.pk,
                outcome='created',
                reason_code='legacy_backfill',
                reason='Создано до перехода на журнал дат серии.',
            )
        )
        if len(occurrences) >= 1000:
            AppointmentSeriesOccurrence.objects.bulk_create(occurrences)
            occurrences.clear()
    if occurrences:
        AppointmentSeriesOccurrence.objects.bulk_create(occurrences)


def remove_backfilled_legacy_series(apps, schema_editor):
    AppointmentSeriesOccurrence = apps.get_model(
        'operations', 'AppointmentSeriesOccurrence'
    )
    AppointmentSeriesParticipant = apps.get_model(
        'operations', 'AppointmentSeriesParticipant'
    )
    AppointmentSeriesStaffAssignment = apps.get_model(
        'operations', 'AppointmentSeriesStaffAssignment'
    )
    has_new_occurrences = AppointmentSeriesOccurrence.objects.exclude(
        reason_code='legacy_backfill'
    ).exists()
    has_new_group_composition = (
        AppointmentSeriesParticipant.objects.filter(series__session_type='group')
        .values('series_id')
        .annotate(row_count=Count('pk'))
        .filter(row_count__gt=1)
        .exists()
    )
    if has_new_occurrences or has_new_group_composition:
        raise RuntimeError(
            'Cannot reverse group program series migration while new series history exists.'
        )
    AppointmentSeriesOccurrence.objects.filter(reason_code='legacy_backfill').delete()
    AppointmentSeriesParticipant.objects.all().delete()
    AppointmentSeriesStaffAssignment.objects.all().delete()


def create_series_occurrence_guard(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_prevent_series_occurrence_change()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'Appointment series occurrences are immutable.';
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_series_occurrence_immutable
        ON operations_appointmentseriesoccurrence
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_series_occurrence_immutable
        BEFORE UPDATE OR DELETE ON operations_appointmentseriesoccurrence
        FOR EACH ROW
        EXECUTE FUNCTION operations_prevent_series_occurrence_change()
        """
    )


def drop_series_occurrence_guard(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_series_occurrence_immutable
        ON operations_appointmentseriesoccurrence
        """
    )
    schema_editor.execute(
        "DROP FUNCTION IF EXISTS operations_prevent_series_occurrence_change()"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0054_donor_report_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSeriesOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('scheduled_starts_at', models.DateTimeField(verbose_name='плановое начало')),
                ('outcome', models.CharField(choices=[('created', 'Создано'), ('joined', 'Присоединено'), ('skipped', 'Пропущено'), ('unchanged', 'Без изменений')], max_length=20, verbose_name='результат')),
                ('reason_code', models.CharField(blank=True, max_length=50, verbose_name='код причины')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
            ],
            options={
                'verbose_name': 'результат даты серии',
                'verbose_name_plural': 'результаты дат серии',
                'ordering': ['series', 'scheduled_starts_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeriesParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='порядок')),
            ],
            options={
                'verbose_name': 'участник серии',
                'verbose_name_plural': 'участники серий',
                'ordering': ['series', 'position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeriesStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('role', models.CharField(choices=[('primary', 'Основной'), ('assistant', 'Ассистент'), ('substitute', 'Замена'), ('observer', 'Наблюдатель')], default='primary', max_length=30, verbose_name='роль')),
                ('override_availability', models.BooleanField(default=False, verbose_name='назначать вне графика')),
                ('override_reason', models.TextField(blank=True, verbose_name='основание выхода вне графика')),
            ],
            options={
                'verbose_name': 'назначение специалиста серии',
                'verbose_name_plural': 'назначения специалистов серий',
                'ordering': ['series', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='operation_key',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='ключ операции'),
        ),
        migrations.RunPython(populate_operation_keys, clear_operation_keys),
        migrations.AlterField(
            model_name='appointmentseries',
            name='operation_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ключ операции'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='session_type',
            field=models.CharField(choices=[('individual', 'Индивидуальное'), ('group', 'Групповое')], default='individual', max_length=20, verbose_name='тип занятия'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='default_appointment_status',
            field=models.CharField(choices=[('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('reserved', 'Бронь')], default='proposed', max_length=30, verbose_name='статус создаваемых занятий'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='allow_unpaid_reserve',
            field=models.BooleanField(default=False, verbose_name='разрешена бронь сверх оплаты'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='allow_outside_availability',
            field=models.BooleanField(default=False, verbose_name='разрешено назначение вне графика'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='override_reason',
            field=models.TextField(blank=True, verbose_name='основание исключений'),
        ),
        migrations.RunPython(assert_participant_sequences_unique, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='appointmentparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('program_block__isnull', False), ('sequence_number__isnull', False), models.Q(('appointment_status__in', ['cancelled', 'rescheduled']), _negated=True)), fields=('program_block', 'sequence_number'), name='unique_program_block_participant_sequence'),
        ),
        migrations.AddField(
            model_name='appointmentseriesoccurrence',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_occurrences', to='operations.appointment', verbose_name='занятие'),
        ),
        migrations.AddField(
            model_name='appointmentseriesoccurrence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_occurrences', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AddField(
            model_name='appointmentseriesoccurrence',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='operations.appointmentseries', verbose_name='серия'),
        ),
        migrations.AddField(
            model_name='appointmentseriesparticipant',
            name='billing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_memberships', to='operations.balanceaccount', verbose_name='счет оплаты'),
        ),
        migrations.AddField(
            model_name='appointmentseriesparticipant',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_memberships', to='operations.child', verbose_name='получатель'),
        ),
        migrations.AddField(
            model_name='appointmentseriesparticipant',
            name='program_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_memberships', to='operations.programblock', verbose_name='каскад'),
        ),
        migrations.AddField(
            model_name='appointmentseriesparticipant',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_participants', to='operations.appointmentseries', verbose_name='серия'),
        ),
        migrations.AddField(
            model_name='appointmentseriesstaffassignment',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_staff_assignments', to='operations.appointmentseries', verbose_name='серия'),
        ),
        migrations.AddField(
            model_name='appointmentseriesstaffassignment',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_assignments', to='operations.staffmember', verbose_name='специалист'),
        ),
        migrations.RunPython(
            assert_legacy_series_occurrences_unique,
            migrations.RunPython.noop,
        ),
        migrations.RunPython(backfill_legacy_series, remove_backfilled_legacy_series),
        migrations.RunPython(
            create_series_occurrence_guard,
            drop_series_occurrence_guard,
        ),
        migrations.AddIndex(
            model_name='appointmentseriesoccurrence',
            index=models.Index(fields=['appointment', 'series'], name='operations__appoint_f59676_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesoccurrence',
            constraint=models.UniqueConstraint(fields=('series', 'scheduled_starts_at'), name='unique_appointment_series_occurrence'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesparticipant',
            index=models.Index(fields=['series', 'position'], name='operations__series__03711a_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesparticipant',
            constraint=models.UniqueConstraint(fields=('series', 'child'), name='unique_appointment_series_child'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesstaffassignment',
            constraint=models.UniqueConstraint(fields=('series', 'staff_member'), name='unique_appointment_series_staff'),
        ),
    ]
