# Generated by Django 5.2.14 on 2026-08-28 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_reverse_with_join_history(apps, schema_editor):
    AppointmentSeries = apps.get_model("operations", "AppointmentSeries")
    AppointmentSeriesOccurrence = apps.get_model(
        "operations", "AppointmentSeriesOccurrence"
    )
    if (
        AppointmentSeries.objects.filter(materialization_mode="join_existing").exists()
        or AppointmentSeriesOccurrence.objects.filter(outcome="joined").exists()
    ):
        raise RuntimeError(
            "Cannot reverse group-series join mode while joined history exists."
        )


def create_join_occurrence_participant_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_join_occurrence_participant()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF NEW.outcome = 'joined' AND NOT EXISTS (
                SELECT 1
                FROM operations_appointmentparticipant participant
                WHERE participant.id = NEW.appointment_participant_id
                  AND participant.appointment_id = NEW.appointment_id
            ) THEN
                RAISE EXCEPTION
                    'Joined series occurrence participant must belong to its appointment.';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_join_occurrence_participant_guard
        ON operations_appointmentseriesoccurrence
        """
    )
    schema_editor.execute(
        """
        CREATE TRIGGER operations_join_occurrence_participant_guard
        BEFORE INSERT ON operations_appointmentseriesoccurrence
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_join_occurrence_participant()
        """
    )


def drop_join_occurrence_participant_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        """
        DROP TRIGGER IF EXISTS operations_join_occurrence_participant_guard
        ON operations_appointmentseriesoccurrence
        """
    )
    schema_editor.execute(
        "DROP FUNCTION IF EXISTS operations_validate_join_occurrence_participant()"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0055_group_program_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentseries',
            name='materialization_mode',
            field=models.CharField(choices=[('create_appointments', 'Создавать занятия'), ('join_existing', 'Присоединять к существующим')], default='create_appointments', max_length=30, verbose_name='режим серии'),
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='operation_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='отпечаток операции'),
        ),
        migrations.AddField(
            model_name='appointmentseriesoccurrence',
            name='appointment_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_join_occurrences', to='operations.appointmentparticipant', verbose_name='участник занятия'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseries',
            constraint=models.CheckConstraint(condition=models.Q(('materialization_mode', 'create_appointments'), ('session_type', 'group'), _connector='OR'), name='join_existing_requires_group_series'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesoccurrence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('appointment__isnull', False), ('appointment_participant__isnull', False), ('outcome', 'joined')), models.Q(models.Q(('outcome', 'joined'), _negated=True), ('appointment_participant__isnull', True)), _connector='OR'), name='joined_occurrence_requires_participant'),
        ),
        migrations.RunPython(
            create_join_occurrence_participant_guard,
            drop_join_occurrence_participant_guard,
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            refuse_reverse_with_join_history,
        ),
    ]
