# Generated by Django 5.2.14 on 2026-08-28 12:49

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0056_group_series_join_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentseriesoccurrence',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_occurrences', to='operations.appointment', verbose_name='занятие'),
        ),
        migrations.CreateModel(
            name='AppointmentSeriesRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('revision_number', models.PositiveIntegerField(verbose_name='номер редакции')),
                ('event_type', models.CharField(choices=[('created', 'Создана'), ('future_composition', 'Изменен будущий состав'), ('legacy_import', 'Перенесена из прежней модели')], max_length=30, verbose_name='действие')),
                ('provenance_kind', models.CharField(choices=[('native', 'Зафиксировано системой'), ('legacy_reconstructed', 'Восстановлено из прежней модели'), ('legacy_unknown', 'Историческая точность неизвестна')], default='native', max_length=30, verbose_name='происхождение данных')),
                ('effective_from', models.DateField(verbose_name='применяется с')),
                ('title', models.CharField(max_length=200, verbose_name='название серии')),
                ('start_date', models.DateField(verbose_name='дата начала')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('days_of_week', models.CharField(max_length=80, verbose_name='дни недели')),
                ('time', models.TimeField(verbose_name='время')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='длительность, мин')),
                ('session_type', models.CharField(choices=[('individual', 'Индивидуальное'), ('group', 'Групповое')], max_length=20, verbose_name='тип занятия')),
                ('materialization_mode', models.CharField(choices=[('create_appointments', 'Создавать занятия'), ('join_existing', 'Присоединять к существующим')], max_length=30, verbose_name='режим серии')),
                ('default_appointment_status', models.CharField(choices=[('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('reserved', 'Бронь')], max_length=30, verbose_name='статус создаваемых занятий')),
                ('allow_unpaid_reserve', models.BooleanField(default=False, verbose_name='разрешена бронь сверх оплаты')),
                ('allow_outside_availability', models.BooleanField(default=False, verbose_name='разрешено назначение вне графика')),
                ('override_reason', models.TextField(blank=True, verbose_name='основание исключений')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='отпечаток редакции')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор'), ('legacy', 'Автор неизвестен')], max_length=20, verbose_name='роль на момент решения')),
                ('reason', models.TextField(verbose_name='основание')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='время решения')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_revisions', to=settings.AUTH_USER_MODEL, verbose_name='решение зафиксировал')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_revisions', to='operations.room', verbose_name='помещение')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='operations.appointmentseries', verbose_name='серия')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_revisions', to='operations.service', verbose_name='услуга')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.appointmentseriesrevision', verbose_name='предыдущая редакция')),
            ],
            options={
                'verbose_name': 'редакция серии занятий',
                'verbose_name_plural': 'редакции серий занятий',
                'ordering': ['series_id', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeriesMaterializationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ключ операции')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='отпечаток запуска')),
                ('mode', models.CharField(choices=[('initial', 'Первый запуск'), ('missing_only', 'Только даты без истории'), ('retry_skipped', 'Повторить пропущенные даты'), ('legacy_import', 'Перенесено из прежней модели')], max_length=30, verbose_name='режим запуска')),
                ('date_from', models.DateField(verbose_name='дата с')),
                ('date_to', models.DateField(verbose_name='дата по')),
                ('expected_result_count', models.PositiveIntegerField(default=0, verbose_name='ожидается результатов')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор'), ('legacy', 'Автор неизвестен')], max_length=20, verbose_name='роль на момент запуска')),
                ('reason', models.TextField(blank=True, verbose_name='основание')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время запуска')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_materialization_runs', to=settings.AUTH_USER_MODEL, verbose_name='запустил')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialization_runs', to='operations.appointmentseries', verbose_name='серия')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialization_runs', to='operations.appointmentseriesrevision', verbose_name='редакция')),
            ],
            options={
                'verbose_name': 'запуск материализации серии',
                'verbose_name_plural': 'запуски материализации серий',
                'ordering': ['series_id', '-started_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeriesMaterializationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('scheduled_starts_at', models.DateTimeField(verbose_name='плановое начало')),
                ('scheduled_date', models.DateField(verbose_name='локальная дата занятия')),
                ('attempt_number', models.PositiveIntegerField(verbose_name='номер попытки')),
                ('provenance_kind', models.CharField(choices=[('native', 'Зафиксировано системой'), ('legacy_reconstructed', 'Восстановлено и сверено'), ('legacy_unknown', 'Историческая точность неизвестна')], default='native', max_length=30, verbose_name='происхождение данных')),
                ('outcome', models.CharField(choices=[('created', 'Создано'), ('joined', 'Присоединено'), ('skipped', 'Пропущено'), ('unchanged', 'Без изменений')], max_length=20, verbose_name='результат')),
                ('reason_code', models.CharField(blank=True, max_length=50, verbose_name='код причины')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_materialization_results', to='operations.appointment', verbose_name='занятие')),
                ('appointment_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_materialization_results', to='operations.appointmentparticipant', verbose_name='участник занятия')),
                ('compatibility_occurrence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='materialization_result', to='operations.appointmentseriesoccurrence', verbose_name='совместимый результат первой попытки')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialization_results', to='operations.appointmentseries', verbose_name='серия')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='superseded_by', to='operations.appointmentseriesmaterializationresult', verbose_name='предыдущая попытка')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='operations.appointmentseriesmaterializationrun', verbose_name='запуск')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materialization_results', to='operations.appointmentseriesrevision', verbose_name='редакция')),
            ],
            options={
                'verbose_name': 'результат запуска серии',
                'verbose_name_plural': 'результаты запусков серий',
                'ordering': ['series', 'scheduled_starts_at', 'attempt_number'],
            },
        ),
        migrations.AddField(
            model_name='appointmentseries',
            name='current_revision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_series', to='operations.appointmentseriesrevision', verbose_name='текущая редакция'),
        ),
        migrations.CreateModel(
            name='AppointmentSeriesRevisionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='порядок')),
                ('billing_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_revision_memberships', to='operations.balanceaccount', verbose_name='счет оплаты')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_revision_memberships', to='operations.child', verbose_name='получатель')),
                ('program_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series_revision_memberships', to='operations.programblock', verbose_name='каскад')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='operations.appointmentseriesrevision', verbose_name='редакция серии')),
            ],
            options={
                'verbose_name': 'участник редакции серии',
                'verbose_name_plural': 'участники редакций серий',
                'ordering': ['revision', 'position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeriesRevisionStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('role', models.CharField(choices=[('primary', 'Основной'), ('assistant', 'Ассистент'), ('substitute', 'Замена'), ('observer', 'Наблюдатель')], default='primary', max_length=30, verbose_name='роль')),
                ('override_availability', models.BooleanField(default=False, verbose_name='назначать вне графика')),
                ('override_reason', models.TextField(blank=True, verbose_name='основание выхода вне графика')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='operations.appointmentseriesrevision', verbose_name='редакция серии')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_revision_assignments', to='operations.staffmember', verbose_name='специалист')),
            ],
            options={
                'verbose_name': 'назначение специалиста редакции серии',
                'verbose_name_plural': 'назначения специалистов редакций серий',
                'ordering': ['revision', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSeriesMaterializationRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('event_number', models.PositiveIntegerField(verbose_name='номер события')),
                ('event_type', models.CharField(choices=[('resumed', 'Продолжен'), ('interrupted', 'Прерван'), ('completed', 'Завершен')], max_length=20, verbose_name='событие')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='результатов всего')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='создано')),
                ('joined_count', models.PositiveIntegerField(default=0, verbose_name='присоединено')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='пропущено')),
                ('unchanged_count', models.PositiveIntegerField(default=0, verbose_name='без изменений')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время события')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='operations.appointmentseriesmaterializationrun', verbose_name='запуск')),
            ],
            options={
                'verbose_name': 'событие запуска серии',
                'verbose_name_plural': 'события запусков серий',
                'ordering': ['run_id', 'occurred_at', 'pk'],
                'indexes': [models.Index(fields=['run', '-occurred_at'], name='operations__run_id_56f153_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'event_number'), name='unique_series_run_event_number'), models.UniqueConstraint(condition=models.Q(('event_type', 'completed')), fields=('run',), name='unique_series_run_completed_event'), models.CheckConstraint(condition=models.Q(('event_number__gte', 1)), name='series_run_event_number_positive'), models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'interrupted'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='series_run_interrupted_reason_required'), models.CheckConstraint(condition=models.Q(('result_count', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('created_count'), '+', models.F('joined_count')), '+', models.F('skipped_count')), '+', models.F('unchanged_count')))), name='series_run_event_counts_match_total')],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentseriesrevision',
            index=models.Index(fields=['series', '-revision_number'], name='operations__series__925841_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesrevision',
            index=models.Index(fields=['series', 'effective_from', '-revision_number'], name='operations__series__fc82ba_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesrevision',
            index=models.Index(fields=['actor', '-created_at'], name='operations__actor_i_7574fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.UniqueConstraint(fields=('series', 'revision_number'), name='unique_appointment_series_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_appointment_series_revision_successor'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision_number__gte', 1)), name='appointment_series_revision_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='appointment_series_revision_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(('effective_from__gte', models.F('start_date')), ('effective_from__lte', models.F('end_date'))), name='appointment_series_revision_effective_range'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('actor_role_snapshot', 'legacy'), ('decided_at__isnull', True), ('event_type', 'legacy_import')), models.Q(models.Q(('event_type', 'legacy_import'), _negated=True), ('actor__isnull', False), ('actor_role_snapshot__in', ['director', 'administrator']), ('decided_at__isnull', False), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='appointment_series_revision_actor_event'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ['created', 'legacy_import']), ('revision_number', 1), ('supersedes__isnull', True)), models.Q(('event_type', 'future_composition'), ('revision_number__gte', 2), ('supersedes__isnull', False)), _connector='OR'), name='appointment_series_revision_chain_event'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'legacy_import'), ('provenance_kind__in', ['legacy_reconstructed', 'legacy_unknown'])), models.Q(models.Q(('event_type', 'legacy_import'), _negated=True), ('provenance_kind', 'native')), _connector='OR'), name='appointment_series_revision_provenance'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(('materialization_mode', 'create_appointments'), ('session_type', 'group'), _connector='OR'), name='series_revision_join_requires_group'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(('allow_unpaid_reserve', False), ('default_appointment_status', 'reserved'), _connector='OR'), name='series_revision_unpaid_requires_reserved'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(('materialization_mode', 'create_appointments'), ('allow_unpaid_reserve', False), _connector='OR'), name='series_revision_join_requires_funding'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allow_outside_availability', False), ('allow_unpaid_reserve', False)), models.Q(('override_reason', ''), _negated=True), _connector='OR'), name='series_revision_override_reason_required'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesmaterializationrun',
            index=models.Index(fields=['series', '-started_at'], name='operations__series__2f381a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesmaterializationrun',
            index=models.Index(fields=['revision', '-started_at'], name='operations__revisio_dfd9a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('mode__in', ['initial', 'legacy_import'])), fields=('revision',), name='unique_series_revision_initial_run'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationrun',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='series_materialization_run_dates_order'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('actor_role_snapshot', 'legacy'), ('mode', 'legacy_import')), models.Q(models.Q(('mode', 'legacy_import'), _negated=True), ('actor__isnull', False), ('actor_role_snapshot__in', ['director', 'administrator'])), _connector='OR'), name='series_materialization_run_actor_mode'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'retry_skipped'), _negated=True), models.Q(('reason', ''), _negated=True), _connector='OR'), name='series_retry_run_reason_required'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesmaterializationresult',
            index=models.Index(fields=['series', 'scheduled_starts_at', '-attempt_number'], name='operations__series__a3d0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesmaterializationresult',
            index=models.Index(fields=['appointment', 'series'], name='operations__appoint_fad741_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesmaterializationresult',
            index=models.Index(fields=['run', 'outcome'], name='operations__run_id_7016b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.UniqueConstraint(fields=('series', 'scheduled_starts_at', 'attempt_number'), name='unique_series_materialization_attempt'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.UniqueConstraint(fields=('run', 'scheduled_starts_at'), name='unique_series_run_scheduled_result'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_series_result_successor'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='series_materialization_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attempt_number', 1), ('supersedes__isnull', True), models.Q(('outcome', 'unchanged'), _negated=True)), models.Q(('attempt_number__gte', 2), ('supersedes__isnull', False)), _connector='OR'), name='series_result_attempt_chain'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('appointment__isnull', False), ('appointment_participant__isnull', False), ('outcome', 'joined')), models.Q(('appointment__isnull', False), ('appointment_participant__isnull', True), ('outcome', 'created')), models.Q(('appointment__isnull', True), ('appointment_participant__isnull', True), ('outcome', 'created'), ('provenance_kind__in', ['legacy_reconstructed', 'legacy_unknown'])), models.Q(('appointment__isnull', True), ('appointment_participant__isnull', True), ('outcome__in', ['skipped', 'unchanged'])), _connector='OR'), name='series_result_outcome_references'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.CheckConstraint(condition=models.Q(('compatibility_occurrence__isnull', True), ('attempt_number', 1), _connector='OR'), name='series_result_compatibility_is_first'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationresult',
            constraint=models.CheckConstraint(condition=models.Q(('provenance_kind', 'native'), models.Q(('compatibility_occurrence__isnull', False), ('provenance_kind__in', ['legacy_reconstructed', 'legacy_unknown'])), _connector='OR'), name='series_result_provenance_has_source'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesrevisionparticipant',
            index=models.Index(fields=['revision', 'position'], name='operations__revisio_99698f_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevisionparticipant',
            constraint=models.UniqueConstraint(fields=('revision', 'child'), name='unique_series_revision_child'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevisionparticipant',
            constraint=models.UniqueConstraint(fields=('revision', 'position'), name='unique_series_revision_participant_position'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevisionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='series_revision_participant_position_positive'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesrevisionstaffassignment',
            index=models.Index(fields=['revision', 'role'], name='operations__revisio_37c6f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevisionstaffassignment',
            constraint=models.UniqueConstraint(fields=('revision', 'staff_member'), name='unique_series_revision_staff'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevisionstaffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary')), fields=('revision',), name='unique_series_revision_primary_staff'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesrevisionstaffassignment',
            constraint=models.CheckConstraint(condition=models.Q(('override_availability', False), models.Q(('override_reason', ''), _negated=True), _connector='OR'), name='series_revision_staff_override_reason'),
        ),
    ]
