# Generated by Django 5.2.14 on 2026-08-28 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preflight_series_retry_targets(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE operations_appointmentseriesmaterializationrun "
            "IN ACCESS EXCLUSIVE MODE"
        )
    Run = apps.get_model("operations", "AppointmentSeriesMaterializationRun")
    if Run.objects.filter(mode="retry_skipped").exists():
        raise RuntimeError(
            "Cannot install frozen retry targets while legacy retry_skipped runs exist."
        )


def install_series_retry_target_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE TRIGGER operations_appointmentseriesretrytarget_immutable
        BEFORE UPDATE OR DELETE ON operations_appointmentseriesretrytarget
        FOR EACH ROW
        EXECUTE FUNCTION operations_block_series_history_mutation();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_series_retry_target()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            run_mode varchar;
            run_series_id bigint;
            run_revision_number integer;
            run_materialization_mode varchar;
            run_date_from date;
            run_date_to date;
            run_expected_count integer;
            current_target_count integer;
            head_series_id bigint;
            head_revision_number integer;
            head_start timestamptz;
            head_date date;
            effective_series_id bigint;
            effective_start timestamptz;
            effective_date date;
            effective_outcome varchar;
            resolved_effective_id bigint;
        BEGIN
            SELECT run.mode, run.series_id, revision.revision_number,
                   revision.materialization_mode, run.date_from, run.date_to,
                   run.expected_result_count
            INTO run_mode, run_series_id, run_revision_number,
                 run_materialization_mode, run_date_from, run_date_to,
                 run_expected_count
            FROM operations_appointmentseriesmaterializationrun AS run
            JOIN operations_appointmentseriesrevision AS revision
              ON revision.id = run.revision_id
            WHERE run.id = NEW.run_id
            FOR UPDATE OF run;
            IF NOT FOUND
               OR run_mode <> 'retry_skipped'
               OR run_materialization_mode <> 'create_appointments' THEN
                RAISE EXCEPTION 'invalid series retry target run';
            END IF;
            IF NEW.scheduled_date IS DISTINCT FROM (
                NEW.scheduled_starts_at AT TIME ZONE 'Asia/Vladivostok'
            )::date
               OR NEW.scheduled_date < run_date_from
               OR NEW.scheduled_date > run_date_to THEN
                RAISE EXCEPTION 'series retry target date is outside run range';
            END IF;

            SELECT result.series_id, revision.revision_number,
                   result.scheduled_starts_at, result.scheduled_date
            INTO head_series_id, head_revision_number, head_start, head_date
            FROM operations_appointmentseriesmaterializationresult AS result
            JOIN operations_appointmentseriesrevision AS revision
              ON revision.id = result.revision_id
            WHERE result.id = NEW.chain_head_result_id
            FOR UPDATE OF result;
            IF NOT FOUND
               OR head_series_id IS DISTINCT FROM run_series_id
               OR head_revision_number > run_revision_number
               OR head_start IS DISTINCT FROM NEW.scheduled_starts_at
               OR head_date IS DISTINCT FROM NEW.scheduled_date
               OR EXISTS (
                   SELECT 1
                   FROM operations_appointmentseriesmaterializationresult
                   WHERE supersedes_id = NEW.chain_head_result_id
               ) THEN
                RAISE EXCEPTION 'invalid series retry target chain head';
            END IF;

            SELECT series_id, scheduled_starts_at, scheduled_date, outcome
            INTO effective_series_id, effective_start, effective_date,
                 effective_outcome
            FROM operations_appointmentseriesmaterializationresult
            WHERE id = NEW.effective_skipped_result_id;
            IF NOT FOUND
               OR effective_series_id IS DISTINCT FROM run_series_id
               OR effective_start IS DISTINCT FROM NEW.scheduled_starts_at
               OR effective_date IS DISTINCT FROM NEW.scheduled_date
               OR effective_outcome <> 'skipped' THEN
                RAISE EXCEPTION 'invalid series retry effective skipped result';
            END IF;

            WITH RECURSIVE result_chain AS (
                SELECT id, supersedes_id, outcome, 0 AS depth
                FROM operations_appointmentseriesmaterializationresult
                WHERE id = NEW.chain_head_result_id
                UNION ALL
                SELECT previous.id, previous.supersedes_id, previous.outcome,
                       chain.depth + 1
                FROM operations_appointmentseriesmaterializationresult AS previous
                JOIN result_chain AS chain ON previous.id = chain.supersedes_id
                WHERE chain.outcome = 'unchanged' AND chain.depth < 10000
            )
            SELECT id
            INTO resolved_effective_id
            FROM result_chain
            WHERE outcome <> 'unchanged'
            ORDER BY depth
            LIMIT 1;
            IF resolved_effective_id IS DISTINCT FROM NEW.effective_skipped_result_id THEN
                RAISE EXCEPTION 'series retry target does not resolve to skipped';
            END IF;

            SELECT COUNT(*)
            INTO current_target_count
            FROM operations_appointmentseriesretrytarget
            WHERE run_id = NEW.run_id;
            IF current_target_count >= run_expected_count THEN
                RAISE EXCEPTION 'series retry target count exceeds expected count';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_series_retry_target_guard
        BEFORE INSERT ON operations_appointmentseriesretrytarget
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_retry_target();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_series_retry_result_target()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            run_mode varchar;
            target_chain_head_id bigint;
        BEGIN
            SELECT mode
            INTO run_mode
            FROM operations_appointmentseriesmaterializationrun
            WHERE id = NEW.run_id;
            IF NEW.supersedes_id IS NOT NULL THEN
                PERFORM 1
                FROM operations_appointmentseriesmaterializationresult
                WHERE id = NEW.supersedes_id
                FOR UPDATE;
            END IF;
            IF run_mode = 'retry_skipped' THEN
                SELECT chain_head_result_id
                INTO target_chain_head_id
                FROM operations_appointmentseriesretrytarget
                WHERE run_id = NEW.run_id
                  AND scheduled_starts_at = NEW.scheduled_starts_at;
                IF NOT FOUND
                   OR NEW.supersedes_id IS DISTINCT FROM target_chain_head_id
                   OR NEW.outcome NOT IN ('created', 'skipped') THEN
                    RAISE EXCEPTION 'series retry result does not match frozen target';
                END IF;
            ELSIF NEW.supersedes_id IS NOT NULL AND EXISTS (
                SELECT 1
                FROM operations_appointmentseriesretrytarget
                WHERE chain_head_result_id = NEW.supersedes_id
            ) THEN
                RAISE EXCEPTION 'series result chain head is reserved for retry';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_series_retry_result_target_guard
        BEFORE INSERT ON operations_appointmentseriesmaterializationresult
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_retry_result_target();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_series_retry_target_count()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            target_run_id bigint;
            run_mode varchar;
            expected_count integer;
            actual_count integer;
        BEGIN
            IF TG_TABLE_NAME = 'operations_appointmentseriesmaterializationrun' THEN
                target_run_id := NEW.id;
            ELSE
                target_run_id := NEW.run_id;
            END IF;
            SELECT mode, expected_result_count
            INTO run_mode, expected_count
            FROM operations_appointmentseriesmaterializationrun
            WHERE id = target_run_id;
            IF run_mode = 'retry_skipped' THEN
                SELECT COUNT(*)
                INTO actual_count
                FROM operations_appointmentseriesretrytarget
                WHERE run_id = target_run_id;
                IF actual_count <> expected_count THEN
                    RAISE EXCEPTION 'series retry target count does not match run';
                END IF;
            END IF;
            RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER operations_series_retry_run_target_count
        AFTER INSERT ON operations_appointmentseriesmaterializationrun
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_retry_target_count();

        CREATE CONSTRAINT TRIGGER operations_series_retry_target_count
        AFTER INSERT ON operations_appointmentseriesretrytarget
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_retry_target_count();
        """
    )


def remove_series_retry_target_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "LOCK TABLE operations_appointmentseriesretrytarget IN ACCESS EXCLUSIVE MODE"
    )
    RetryTarget = apps.get_model("operations", "AppointmentSeriesRetryTarget")
    if RetryTarget.objects.exists():
        raise RuntimeError(
            "Cannot remove series retry target schema while frozen targets exist."
        )

    trigger_tables = (
        (
            "operations_series_retry_target_count",
            "operations_appointmentseriesretrytarget",
        ),
        (
            "operations_series_retry_run_target_count",
            "operations_appointmentseriesmaterializationrun",
        ),
        (
            "operations_series_retry_result_target_guard",
            "operations_appointmentseriesmaterializationresult",
        ),
        (
            "operations_series_retry_target_guard",
            "operations_appointmentseriesretrytarget",
        ),
        (
            "operations_appointmentseriesretrytarget_immutable",
            "operations_appointmentseriesretrytarget",
        ),
    )
    for trigger_name, table_name in trigger_tables:
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {schema_editor.quote_name(trigger_name)} "
            f"ON {schema_editor.quote_name(table_name)}"
        )
    for function_name in (
        "operations_validate_series_retry_target_count",
        "operations_validate_series_retry_result_target",
        "operations_validate_series_retry_target",
    ):
        schema_editor.execute(f"DROP FUNCTION IF EXISTS {function_name}()")


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0060_series_cross_revision_attempt_guards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            preflight_series_retry_targets,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AppointmentSeriesRetryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('scheduled_starts_at', models.DateTimeField(verbose_name='плановое начало')),
                ('scheduled_date', models.DateField(verbose_name='локальная дата занятия')),
            ],
            options={
                'verbose_name': 'зафиксированная цель повторного запуска серии',
                'verbose_name_plural': 'зафиксированные цели повторных запусков серий',
                'ordering': ['run_id', 'scheduled_starts_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesmaterializationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mode', 'retry_skipped'), _negated=True), ('expected_result_count__gte', 1), _connector='OR'), name='series_retry_run_has_targets'),
        ),
        migrations.AddField(
            model_name='appointmentseriesretrytarget',
            name='chain_head_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retry_chain_head_targets', to='operations.appointmentseriesmaterializationresult', verbose_name='вершина цепочки при принятии запуска'),
        ),
        migrations.AddField(
            model_name='appointmentseriesretrytarget',
            name='effective_skipped_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retry_effective_targets', to='operations.appointmentseriesmaterializationresult', verbose_name='эффективный пропущенный результат'),
        ),
        migrations.AddField(
            model_name='appointmentseriesretrytarget',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retry_targets', to='operations.appointmentseriesmaterializationrun', verbose_name='повторный запуск'),
        ),
        migrations.AddIndex(
            model_name='appointmentseriesretrytarget',
            index=models.Index(fields=['run', 'scheduled_date'], name='operations__run_id_5f821c_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesretrytarget',
            constraint=models.UniqueConstraint(fields=('run', 'scheduled_starts_at'), name='unique_series_retry_run_target'),
        ),
        migrations.AddConstraint(
            model_name='appointmentseriesretrytarget',
            constraint=models.UniqueConstraint(fields=('chain_head_result',), name='unique_series_retry_chain_head'),
        ),
        migrations.RunPython(
            install_series_retry_target_guards,
            remove_series_retry_target_guards,
        ),
    ]
