# Generated by Django 5.2.14 on 2026-08-28 18:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def install_series_lifecycle_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        """
        CREATE TRIGGER operations_appointmentserieslifecycleevent_immutable
        BEFORE UPDATE OR DELETE ON operations_appointmentserieslifecycleevent
        FOR EACH ROW
        EXECUTE FUNCTION operations_block_series_history_mutation();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_series_lifecycle_event()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            series_status varchar;
            latest_event_id bigint;
            latest_event_number integer;
            latest_occurred_at timestamptz;
            latest_actor_role varchar;
            previous_series_id bigint;
            previous_event_type varchar;
            previous_status_to varchar;
        BEGIN
            SELECT status
            INTO series_status
            FROM operations_appointmentseries
            WHERE id = NEW.series_id
            FOR UPDATE;
            IF NOT FOUND OR series_status IS DISTINCT FROM NEW.status_from THEN
                RAISE EXCEPTION 'series lifecycle event starts from stale status';
            END IF;

            SELECT id, event_number, occurred_at, actor_role_snapshot
            INTO latest_event_id, latest_event_number, latest_occurred_at, latest_actor_role
            FROM operations_appointmentserieslifecycleevent
            WHERE series_id = NEW.series_id
            ORDER BY event_number DESC, id DESC
            LIMIT 1;
            IF NEW.event_number IS DISTINCT FROM COALESCE(latest_event_number, 0) + 1 THEN
                RAISE EXCEPTION 'series lifecycle event number is not monotonic';
            END IF;
            IF latest_occurred_at IS NOT NULL
               AND NEW.occurred_at < latest_occurred_at THEN
                RAISE EXCEPTION 'series lifecycle event order is not monotonic';
            END IF;
            IF NEW.event_type <> 'resume_materialization'
               AND NEW.actor_role_snapshot = 'administrator'
               AND latest_actor_role = 'director' THEN
                RAISE EXCEPTION 'administrator cannot override director lifecycle decision';
            END IF;

            IF NEW.event_type = 'resume_materialization' THEN
                SELECT series_id, event_type, status_to
                INTO previous_series_id, previous_event_type, previous_status_to
                FROM operations_appointmentserieslifecycleevent
                WHERE id = NEW.supersedes_id;
                IF NOT FOUND
                   OR previous_series_id IS DISTINCT FROM NEW.series_id
                   OR previous_event_type = 'resume_materialization'
                   OR previous_status_to <> 'cancelled'
                   OR latest_event_id IS DISTINCT FROM NEW.supersedes_id THEN
                    RAISE EXCEPTION 'invalid series lifecycle supersedes chain';
                END IF;
            END IF;

            IF char_length(NEW.fingerprint) <> 64 THEN
                RAISE EXCEPTION 'invalid series lifecycle fingerprint';
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_series_lifecycle_insert_guard
        BEFORE INSERT ON operations_appointmentserieslifecycleevent
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_lifecycle_event();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_series_lifecycle_root_status()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            latest_status_to varchar;
        BEGIN
            IF NEW.status = 'active' AND OLD.status IS DISTINCT FROM NEW.status THEN
                SELECT status_to
                INTO latest_status_to
                FROM operations_appointmentserieslifecycleevent
                WHERE series_id = NEW.id
                ORDER BY event_number DESC, id DESC
                LIMIT 1;
                IF latest_status_to = 'cancelled' THEN
                    RAISE EXCEPTION 'series lifecycle stop requires an explicit resume event';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$;

        CREATE TRIGGER operations_series_lifecycle_root_status_guard
        BEFORE UPDATE OF status ON operations_appointmentseries
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_lifecycle_root_status();
        """
    )
    schema_editor.execute(
        """
        CREATE OR REPLACE FUNCTION operations_validate_series_lifecycle_projection()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            latest_event_id bigint;
            latest_status_to varchar;
            series_status varchar;
        BEGIN
            SELECT id, status_to
            INTO latest_event_id, latest_status_to
            FROM operations_appointmentserieslifecycleevent
            WHERE series_id = NEW.series_id
            ORDER BY event_number DESC, id DESC
            LIMIT 1;
            IF latest_event_id IS DISTINCT FROM NEW.id THEN
                RETURN NULL;
            END IF;

            SELECT status
            INTO series_status
            FROM operations_appointmentseries
            WHERE id = NEW.series_id;
            IF series_status IS DISTINCT FROM latest_status_to THEN
                RAISE EXCEPTION 'series lifecycle projection does not match latest event';
            END IF;
            RETURN NULL;
        END;
        $$;

        CREATE CONSTRAINT TRIGGER operations_series_lifecycle_projection_guard
        AFTER INSERT ON operations_appointmentserieslifecycleevent
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION operations_validate_series_lifecycle_projection();
        """
    )


def remove_series_lifecycle_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE operations_appointmentserieslifecycleevent IN ACCESS EXCLUSIVE MODE"
        )
    LifecycleEvent = apps.get_model("operations", "AppointmentSeriesLifecycleEvent")
    if LifecycleEvent.objects.exists():
        raise RuntimeError(
            "Cannot remove series lifecycle schema while lifecycle history exists."
        )
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute(
        "DROP TRIGGER IF EXISTS operations_series_lifecycle_root_status_guard "
        "ON operations_appointmentseries"
    )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS operations_series_lifecycle_projection_guard "
        "ON operations_appointmentserieslifecycleevent"
    )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS operations_series_lifecycle_insert_guard "
        "ON operations_appointmentserieslifecycleevent"
    )
    schema_editor.execute(
        "DROP TRIGGER IF EXISTS operations_appointmentserieslifecycleevent_immutable "
        "ON operations_appointmentserieslifecycleevent"
    )
    schema_editor.execute(
        "DROP FUNCTION IF EXISTS operations_validate_series_lifecycle_root_status()"
    )
    schema_editor.execute(
        "DROP FUNCTION IF EXISTS operations_validate_series_lifecycle_projection()"
    )
    schema_editor.execute(
        "DROP FUNCTION IF EXISTS operations_validate_series_lifecycle_event()"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0061_series_retry_target_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSeriesLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ключ операции')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='отпечаток операции')),
                ('event_type', models.CharField(choices=[('stop_materialization', 'Остановить новые запуски'), ('resume_materialization', 'Возобновить новые запуски'), ('cancel_future_unstarted', 'Отменить будущие неначавшиеся занятия'), ('withdraw_future_joined_participations', 'Снять будущие присоединенные участия')], max_length=50, verbose_name='событие')),
                ('event_number', models.PositiveIntegerField(verbose_name='номер события')),
                ('status_from', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], max_length=30, verbose_name='статус был')),
                ('status_to', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], max_length=30, verbose_name='статус стал')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор')], max_length=20, verbose_name='роль на момент действия')),
                ('reason', models.TextField(verbose_name='основание')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время события')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_series_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='действие выполнил')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='operations.appointmentseries', verbose_name='серия')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='operations.appointmentserieslifecycleevent', verbose_name='переопределяет событие')),
            ],
            options={
                'verbose_name': 'событие жизненного цикла серии',
                'verbose_name_plural': 'события жизненного цикла серий',
                'ordering': ['series_id', 'event_number', 'pk'],
                'indexes': [models.Index(fields=['series', '-occurred_at'], name='operations__series__baeafe_idx'), models.Index(fields=['event_type', '-occurred_at'], name='operations__event_t_aed24a_idx')],
                'constraints': [models.UniqueConstraint(fields=('series', 'event_number'), name='unique_series_lifecycle_event_number'), models.CheckConstraint(condition=models.Q(('event_number__gte', 1)), name='series_lifecycle_event_number_positive'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='series_lifecycle_reason_required'), models.CheckConstraint(condition=models.Q(('actor_role_snapshot__in', ['director', 'administrator'])), name='series_lifecycle_operator_role'), models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot', 'director'), ('event_type', 'resume_materialization'), ('status_from', 'cancelled'), ('status_to', 'active'), ('supersedes__isnull', False)), models.Q(('event_type__in', ['stop_materialization', 'cancel_future_unstarted', 'withdraw_future_joined_participations']), ('status_from', 'active'), ('status_to', 'cancelled'), ('supersedes__isnull', True)), _connector='OR'), name='series_lifecycle_valid_transition')],
            },
        ),
        migrations.RunPython(
            install_series_lifecycle_guards,
            remove_series_lifecycle_guards,
        ),
    ]
