# Generated by Django 5.2.14 on 2026-09-07 13:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
    -- Insert-time attribution invariant; historical snapshots survive later role changes.
    -- Mirrors authority.py at 0065. Changes to role policy require a forward migration.
    CREATE FUNCTION operations_operator_actor_role(actor_id bigint) RETURNS text AS $$
      SELECT CASE
        WHEN u.is_superuser OR EXISTS (
          SELECT 1 FROM auth_user_groups ug JOIN auth_group g ON g.id = ug.group_id
          WHERE ug.user_id = u.id AND g.name IN ('Руководители', 'Руководитель')
        ) THEN 'director'
        WHEN u.is_staff OR EXISTS (
          SELECT 1 FROM auth_user_groups ug JOIN auth_group g ON g.id = ug.group_id
          WHERE ug.user_id = u.id AND g.name IN ('Администраторы', 'Администратор')
        ) THEN 'administrator'
        WHEN EXISTS (SELECT 1 FROM operations_staffmember s WHERE s.user_id = u.id)
          THEN 'specialist'
        ELSE 'authenticated' END
      FROM auth_user u WHERE u.id = actor_id;
    $$ LANGUAGE sql STABLE;

    CREATE FUNCTION operations_attendance_decision_guard() RETURNS trigger AS $$
    DECLARE previous operations_appointmentattendancedecision%ROWTYPE;
            appointment_row operations_appointment%ROWTYPE;
    BEGIN
      IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Attendance history is immutable' USING ERRCODE = '23514';
      END IF;
      IF NEW.actor_role_snapshot IS DISTINCT FROM operations_operator_actor_role(NEW.actor_id) THEN
        RAISE EXCEPTION 'Attendance actor role snapshot does not match actor' USING ERRCODE = '23514';
      END IF;
      SELECT * INTO appointment_row FROM operations_appointment
        WHERE id = NEW.appointment_id FOR UPDATE;
      SELECT * INTO previous FROM operations_appointmentattendancedecision
        WHERE appointment_id = NEW.appointment_id ORDER BY decision_number DESC LIMIT 1;
      IF NEW.decision_number <> COALESCE(previous.decision_number, 0) + 1
         OR NEW.supersedes_id IS DISTINCT FROM previous.id THEN
        RAISE EXCEPTION 'Attendance decision must continue its chain' USING ERRCODE = '23514';
      END IF;
      IF NEW.actor_role_snapshot NOT IN ('specialist', 'administrator', 'director')
         OR (NEW.actor_role_snapshot <> 'specialist' AND length(btrim(NEW.reason)) < 5)
         OR (previous.id IS NOT NULL AND NEW.actor_role_snapshot = 'specialist')
         OR (previous.actor_role_snapshot = 'director' AND NEW.actor_role_snapshot <> 'director') THEN
        RAISE EXCEPTION 'Attendance decision authority violation' USING ERRCODE = '23514';
      END IF;
      IF NEW.status_before <> appointment_row.status
         OR NEW.starts_at_snapshot <> appointment_row.starts_at
         OR NEW.ends_at_snapshot <> appointment_row.ends_at THEN
        RAISE EXCEPTION 'Attendance decision snapshot is stale' USING ERRCODE = '23514';
      END IF;
      IF NEW.action = 'not_completed' AND (
        NEW.attendance_after = 'attended'
        OR EXISTS (SELECT 1 FROM jsonb_each_text(NEW.participants_after) WHERE value = 'attended')
      ) THEN
        RAISE EXCEPTION 'Not completed attendance cannot include attended participants' USING ERRCODE = '23514';
      END IF;
      IF appointment_row.status IN ('completed', 'no_show') AND (
        appointment_row.billing_decision <> 'undecided'
        OR EXISTS (SELECT 1 FROM operations_appointmentparticipant WHERE appointment_id = NEW.appointment_id AND billing_decision <> 'undecided')
        OR EXISTS (SELECT 1 FROM operations_ledgerentry WHERE appointment_id = NEW.appointment_id)
        OR EXISTS (SELECT 1 FROM operations_payrollaccrual WHERE appointment_id = NEW.appointment_id)
      ) THEN
        RAISE EXCEPTION 'Financial correction is required before attendance correction' USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql;
    CREATE TRIGGER appointment_attendance_history_guard BEFORE INSERT OR UPDATE OR DELETE
      ON operations_appointmentattendancedecision FOR EACH ROW
      EXECUTE FUNCTION operations_attendance_decision_guard();

    CREATE FUNCTION operations_schedule_decision_guard() RETURNS trigger AS $$
    DECLARE previous operations_appointmentscheduledecision%ROWTYPE;
            appointment_row operations_appointment%ROWTYPE;
    BEGIN
      IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Schedule decision history is immutable' USING ERRCODE = '23514';
      END IF;
      IF NEW.actor_role_snapshot IS DISTINCT FROM operations_operator_actor_role(NEW.actor_id) THEN
        RAISE EXCEPTION 'Schedule actor role snapshot does not match actor' USING ERRCODE = '23514';
      END IF;
      SELECT * INTO appointment_row FROM operations_appointment
        WHERE id = NEW.appointment_id FOR UPDATE;
      IF NOT EXISTS (
        SELECT 1 FROM operations_appointmentstaffassignment
        WHERE appointment_id = NEW.appointment_id AND staff_member_id = NEW.staff_member_id
      ) AND (
        EXISTS (SELECT 1 FROM operations_appointmentstaffassignment WHERE appointment_id = NEW.appointment_id)
        OR NEW.staff_member_id IS DISTINCT FROM appointment_row.staff_member_id
      ) THEN
        RAISE EXCEPTION 'Schedule staff member is not assigned to appointment' USING ERRCODE = '23514';
      END IF;
      SELECT * INTO previous FROM operations_appointmentscheduledecision
        WHERE appointment_id = NEW.appointment_id AND staff_member_id = NEW.staff_member_id
        ORDER BY decision_number DESC LIMIT 1;
      IF NEW.decision_number <> COALESCE(previous.decision_number, 0) + 1
         OR NEW.supersedes_id IS DISTINCT FROM previous.id THEN
        RAISE EXCEPTION 'Schedule decision must continue its chain' USING ERRCODE = '23514';
      END IF;
      IF NEW.actor_role_snapshot NOT IN ('administrator', 'director')
         OR length(btrim(NEW.reason)) < 5
         OR (previous.actor_role_snapshot = 'director' AND NEW.actor_role_snapshot <> 'director'
             AND previous.starts_at_snapshot = NEW.starts_at_snapshot
             AND previous.ends_at_snapshot = NEW.ends_at_snapshot) THEN
        RAISE EXCEPTION 'Schedule decision authority violation' USING ERRCODE = '23514';
      END IF;
      IF NEW.starts_at_snapshot <> appointment_row.starts_at
         OR NEW.ends_at_snapshot <> appointment_row.ends_at
         OR appointment_row.status NOT IN ('draft','proposed','confirmed','reserved') THEN
        RAISE EXCEPTION 'Schedule decision snapshot is stale' USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql;
    CREATE TRIGGER appointment_schedule_history_guard BEFORE INSERT OR UPDATE OR DELETE
      ON operations_appointmentscheduledecision FOR EACH ROW
      EXECUTE FUNCTION operations_schedule_decision_guard();

    CREATE FUNCTION operations_attendance_projection_guard() RETURNS trigger AS $$
    DECLARE latest operations_appointmentattendancedecision%ROWTYPE;
    BEGIN
      SELECT * INTO latest FROM operations_appointmentattendancedecision
        WHERE appointment_id = NEW.id ORDER BY decision_number DESC LIMIT 1;
      IF latest.id IS NOT NULL AND (
        NEW.status <> latest.status_after OR NEW.attendance_status <> latest.attendance_after
        OR NEW.starts_at <> latest.starts_at_snapshot OR NEW.ends_at <> latest.ends_at_snapshot
      ) THEN
        RAISE EXCEPTION 'Attendance projection requires a new authorized decision' USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql;
    CREATE TRIGGER appointment_attendance_projection_guard
      BEFORE UPDATE OF status, attendance_status, starts_at, ends_at
      ON operations_appointment FOR EACH ROW EXECUTE FUNCTION operations_attendance_projection_guard();

    CREATE FUNCTION operations_attendance_participant_guard() RETURNS trigger AS $$
    DECLARE latest operations_appointmentattendancedecision%ROWTYPE;
    BEGIN
      SELECT * INTO latest FROM operations_appointmentattendancedecision
        WHERE appointment_id = OLD.appointment_id ORDER BY decision_number DESC LIMIT 1;
      IF latest.id IS NOT NULL AND latest.participants_after ? OLD.id::text AND (
        NEW.appointment_id <> OLD.appointment_id OR NEW.appointment_status <> latest.status_after
        OR NEW.attendance_status <> latest.participants_after ->> OLD.id::text
      ) THEN
        RAISE EXCEPTION 'Participant attendance requires a new authorized decision' USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END; $$ LANGUAGE plpgsql;
    CREATE TRIGGER participant_attendance_projection_guard
      BEFORE UPDATE OF appointment_id, appointment_status, attendance_status
      ON operations_appointmentparticipant FOR EACH ROW EXECUTE FUNCTION operations_attendance_participant_guard();

    CREATE FUNCTION operations_attendance_consistency_guard() RETURNS trigger AS $$
    DECLARE latest operations_appointmentattendancedecision%ROWTYPE;
            appointment_row operations_appointment%ROWTYPE;
    BEGIN
      SELECT * INTO latest FROM operations_appointmentattendancedecision
        WHERE appointment_id = NEW.appointment_id ORDER BY decision_number DESC LIMIT 1;
      SELECT * INTO appointment_row FROM operations_appointment WHERE id = NEW.appointment_id;
      IF appointment_row.status <> latest.status_after OR appointment_row.attendance_status <> latest.attendance_after
        OR EXISTS (
          SELECT 1 FROM jsonb_each_text(latest.participants_after) expected
          LEFT JOIN operations_appointmentparticipant participant ON participant.id::text = expected.key
          WHERE participant.id IS NULL OR participant.appointment_id <> latest.appointment_id
            OR participant.attendance_status <> expected.value OR participant.appointment_status <> latest.status_after
        ) THEN
        RAISE EXCEPTION 'Attendance decision and projections must commit together' USING ERRCODE = '23514';
      END IF;
      RETURN NULL;
    END; $$ LANGUAGE plpgsql;
    CREATE CONSTRAINT TRIGGER appointment_attendance_consistency_guard AFTER INSERT
      ON operations_appointmentattendancedecision DEFERRABLE INITIALLY DEFERRED
      FOR EACH ROW EXECUTE FUNCTION operations_attendance_consistency_guard();
    """, params=None)


def remove_guards(apps, schema_editor):
    for name in ("AppointmentAttendanceDecision", "AppointmentScheduleDecision"):
        if apps.get_model("operations", name).objects.exists():
            raise RuntimeError("Cannot reverse 0065 after operator decisions exist; preserve the audit history.")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
        DROP TRIGGER appointment_attendance_consistency_guard ON operations_appointmentattendancedecision;
        DROP TRIGGER participant_attendance_projection_guard ON operations_appointmentparticipant;
        DROP TRIGGER appointment_attendance_projection_guard ON operations_appointment;
        DROP TRIGGER appointment_schedule_history_guard ON operations_appointmentscheduledecision;
        DROP TRIGGER appointment_attendance_history_guard ON operations_appointmentattendancedecision;
        DROP FUNCTION operations_attendance_consistency_guard();
        DROP FUNCTION operations_attendance_participant_guard();
        DROP FUNCTION operations_attendance_projection_guard();
        DROP FUNCTION operations_schedule_decision_guard();
        DROP FUNCTION operations_attendance_decision_guard();
        DROP FUNCTION operations_operator_actor_role(bigint);
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0064_series_withdraw_results_expand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAttendanceDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('actor_role_snapshot', models.CharField(choices=[('specialist', 'Специалист'), ('administrator', 'Администратор'), ('director', 'Руководитель')], max_length=30)),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('decision_number', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('completed', 'Проведено'), ('not_completed', 'Не проведено')], max_length=30)),
                ('reason', models.TextField(blank=True, max_length=2000, verbose_name='основание')),
                ('note', models.TextField(blank=True, max_length=2000, verbose_name='заметка')),
                ('status_before', models.CharField(choices=[('draft', 'Черновик'), ('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Неявка'), ('rescheduled', 'Перенесено'), ('reserved', 'Бронь')], max_length=30)),
                ('status_after', models.CharField(choices=[('draft', 'Черновик'), ('proposed', 'Предложено'), ('confirmed', 'Согласовано'), ('completed', 'Проведено'), ('cancelled', 'Отменено'), ('no_show', 'Неявка'), ('rescheduled', 'Перенесено'), ('reserved', 'Бронь')], max_length=30)),
                ('attendance_after', models.CharField(choices=[('unknown', 'Не отмечено'), ('attended', 'Пришел'), ('missed', 'Не пришел'), ('excused', 'Уважительная причина')], max_length=30)),
                ('starts_at_snapshot', models.DateTimeField()),
                ('ends_at_snapshot', models.DateTimeField()),
                ('participants_before', models.JSONField(blank=True, default=dict)),
                ('participants_after', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_decisions', to='operations.appointment')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='operations.appointmentattendancedecision')),
            ],
            options={
                'ordering': ['-decision_number'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'decision_number'), name='attendance_decision_sequence'), models.CheckConstraint(condition=models.Q(('decision_number__gte', 1)), name='attendance_decision_positive'), models.CheckConstraint(condition=models.Q(('actor_role_snapshot', 'specialist'), models.Q(('reason', ''), _negated=True), _connector='OR'), name='attendance_manual_reason_required'), models.CheckConstraint(condition=models.Q(models.Q(('action', 'completed'), ('status_after', 'completed')), models.Q(('action', 'not_completed'), ('status_after', 'no_show')), _connector='OR'), name='attendance_action_status_match')],
            },
        ),
        migrations.CreateModel(
            name='AppointmentScheduleDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('actor_role_snapshot', models.CharField(choices=[('administrator', 'Администратор'), ('director', 'Руководитель')], max_length=30)),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(editable=False, max_length=64)),
                ('decision_number', models.PositiveIntegerField()),
                ('decision', models.CharField(choices=[('confirmed', 'Принято'), ('declined', 'Отклонено')], max_length=30)),
                ('reason', models.TextField(max_length=2000, verbose_name='основание')),
                ('starts_at_snapshot', models.DateTimeField()),
                ('ends_at_snapshot', models.DateTimeField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_decisions', to='operations.appointment')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.staffmember')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successor', to='operations.appointmentscheduledecision')),
            ],
            options={
                'ordering': ['-decision_number', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'staff_member', 'decision_number'), name='schedule_decision_sequence'), models.CheckConstraint(condition=models.Q(('decision_number__gte', 1)), name='schedule_decision_positive'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='schedule_decision_reason_required')],
            },
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
