# Generated by Django 5.2.14 on 2026-09-09 05:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def preflight(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE operations_treatmentprogram IN SHARE ROW EXCLUSIVE MODE"
        )
    program = apps.get_model("operations", "TreatmentProgram")
    invalid_ids = list(
        program.objects.using(connection.alias)
        .exclude(status__in=["draft", "active", "paused", "completed", "cancelled"])
        .order_by("pk").values_list("pk", flat=True)[:10]
    )
    if invalid_ids:
        raise RuntimeError(
            f"Unknown treatment program statuses (IDs {invalid_ids}); "
            "review existing data before migration. No records were changed."
        )


GUARD_SQL = """
CREATE FUNCTION operations_program_lifecycle_guard() RETURNS trigger AS $$
DECLARE previous operations_treatmentprogramlifecycleevent%ROWTYPE;
        current_status varchar;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Program lifecycle history is immutable' USING ERRCODE = '23514';
    END IF;
    IF NEW.actor_role_snapshot IS DISTINCT FROM operations_operator_actor_role(NEW.actor_id)
       OR NOT EXISTS (SELECT 1 FROM auth_user WHERE id = NEW.actor_id AND is_active) THEN
        RAISE EXCEPTION 'Program lifecycle actor role mismatch' USING ERRCODE = '23514';
    END IF;
    IF length(btrim(NEW.reason)) < 5 OR NEW.fingerprint !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Invalid program lifecycle reason or fingerprint' USING ERRCODE = '23514';
    END IF;
    SELECT status INTO current_status FROM operations_treatmentprogram
        WHERE id = NEW.program_id FOR UPDATE;
    IF NOT FOUND OR current_status IS DISTINCT FROM NEW.status_from THEN
        RAISE EXCEPTION 'Program lifecycle status is stale' USING ERRCODE = '23514';
    END IF;
    SELECT * INTO previous FROM operations_treatmentprogramlifecycleevent
        WHERE program_id = NEW.program_id ORDER BY event_number DESC LIMIT 1;
    IF NEW.event_number <> COALESCE(previous.event_number, 0) + 1
       OR NEW.supersedes_id IS DISTINCT FROM previous.id
       OR (previous.id IS NOT NULL AND previous.status_to IS DISTINCT FROM NEW.status_from)
       OR NEW.occurred_at < previous.occurred_at THEN
        RAISE EXCEPTION 'Program lifecycle must continue its chain' USING ERRCODE = '23514';
    END IF;
    IF previous.actor_role_snapshot = 'director' AND NEW.actor_role_snapshot <> 'director' THEN
        RAISE EXCEPTION 'Administrator cannot override director program decision' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER program_lifecycle_history_guard BEFORE INSERT OR UPDATE OR DELETE
    ON operations_treatmentprogramlifecycleevent FOR EACH ROW
    EXECUTE FUNCTION operations_program_lifecycle_guard();

CREATE FUNCTION operations_program_status_guard() RETURNS trigger AS $$
DECLARE latest operations_treatmentprogramlifecycleevent%ROWTYPE;
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        SELECT * INTO latest FROM operations_treatmentprogramlifecycleevent
            WHERE program_id = NEW.id ORDER BY event_number DESC LIMIT 1;
        IF (OLD.status = 'paused' OR NEW.status = 'paused' OR latest.id IS NOT NULL)
           AND (latest.id IS NULL OR latest.status_from IS DISTINCT FROM OLD.status
                OR latest.status_to IS DISTINCT FROM NEW.status) THEN
            RAISE EXCEPTION 'Program status requires a new lifecycle decision' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER program_status_guard BEFORE UPDATE OF status
    ON operations_treatmentprogram FOR EACH ROW
    EXECUTE FUNCTION operations_program_status_guard();

CREATE FUNCTION operations_program_projection_guard() RETURNS trigger AS $$
DECLARE latest operations_treatmentprogramlifecycleevent%ROWTYPE;
        current_status varchar;
BEGIN
    SELECT * INTO latest FROM operations_treatmentprogramlifecycleevent
        WHERE program_id = NEW.program_id ORDER BY event_number DESC LIMIT 1;
    SELECT status INTO current_status FROM operations_treatmentprogram WHERE id = NEW.program_id;
    IF current_status IS DISTINCT FROM latest.status_to THEN
        RAISE EXCEPTION 'Program projection does not match lifecycle history' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER program_projection_guard AFTER INSERT
    ON operations_treatmentprogramlifecycleevent DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION operations_program_projection_guard();
"""


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(GUARD_SQL, params=None)


def remove_guards(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE operations_treatmentprogram, operations_treatmentprogramlifecycleevent "
            "IN SHARE ROW EXCLUSIVE MODE"
        )
    event = apps.get_model("operations", "TreatmentProgramLifecycleEvent")
    if event.objects.using(connection.alias).exists():
        raise RuntimeError("Cannot reverse program lifecycle migration: immutable history exists.")
    if connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER program_projection_guard ON operations_treatmentprogramlifecycleevent;
            DROP TRIGGER program_status_guard ON operations_treatmentprogram;
            DROP TRIGGER program_lifecycle_history_guard ON operations_treatmentprogramlifecycleevent;
            DROP FUNCTION operations_program_projection_guard();
            DROP FUNCTION operations_program_status_guard();
            DROP FUNCTION operations_program_lifecycle_guard();
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0066_series_resume_stop_guard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.CreateModel(
            name='TreatmentProgramLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64, verbose_name='отпечаток операции')),
                ('event_type', models.CharField(choices=[('paused', 'Приостановить программу'), ('resumed', 'Возобновить программу')], max_length=20, verbose_name='решение')),
                ('event_number', models.PositiveIntegerField(verbose_name='номер решения')),
                ('status_from', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], max_length=30, verbose_name='статус был')),
                ('status_to', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('paused', 'Пауза'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], max_length=30, verbose_name='статус стал')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор')], max_length=20, verbose_name='роль')),
                ('reason', models.TextField(verbose_name='основание')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время решения')),
            ],
            options={
                'verbose_name': 'решение по программе',
                'verbose_name_plural': 'решения по программам',
                'ordering': ['program_id', '-event_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='treatmentprogram',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'active', 'paused', 'completed', 'cancelled'])), name='treatment_program_known_status'),
        ),
        migrations.AddField(
            model_name='treatmentprogramlifecycleevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='решение принял'),
        ),
        migrations.AddField(
            model_name='treatmentprogramlifecycleevent',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='operations.treatmentprogram', verbose_name='программа'),
        ),
        migrations.AddField(
            model_name='treatmentprogramlifecycleevent',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='operations.treatmentprogramlifecycleevent', verbose_name='предыдущее решение'),
        ),
        migrations.AddConstraint(
            model_name='treatmentprogramlifecycleevent',
            constraint=models.UniqueConstraint(fields=('program', 'event_number'), name='unique_program_event_number'),
        ),
        migrations.AddConstraint(
            model_name='treatmentprogramlifecycleevent',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_program_event_successor'),
        ),
        migrations.AddConstraint(
            model_name='treatmentprogramlifecycleevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_number__gte', 1)), name='program_event_number_positive'),
        ),
        migrations.AddConstraint(
            model_name='treatmentprogramlifecycleevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot__in', ['administrator', 'director']), ('event_type', 'paused'), ('status_from', 'active'), ('status_to', 'paused')), models.Q(('actor_role_snapshot', 'director'), ('event_type', 'resumed'), ('status_from', 'paused'), ('status_to', 'active')), _connector='OR'), name='program_event_transition_role'),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
