# Generated by Django 5.2.14 on 2026-09-12 11:50

from django.conf import settings
from django.db import migrations, models


STATUS_SQL = """
CREATE OR REPLACE FUNCTION operations_program_status_guard() RETURNS trigger AS $$
DECLARE latest operations_treatmentprogramlifecycleevent%ROWTYPE;
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        SELECT * INTO latest FROM operations_treatmentprogramlifecycleevent
            WHERE program_id = NEW.id ORDER BY event_number DESC LIMIT 1;
        IF (latest.id IS NULL OR latest.status_from IS DISTINCT FROM OLD.status
            OR latest.status_to IS DISTINCT FROM NEW.status) THEN
            RAISE EXCEPTION 'Program status requires a new lifecycle decision' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
"""

REVIEW_SQL = """
CREATE FUNCTION operations_program_review_guard() RETURNS trigger AS $$
DECLARE current_program operations_treatmentprogram%ROWTYPE;
        block_snapshot jsonb;
        expected_snapshot jsonb;
        fingerprint_payload jsonb;
BEGIN
    fingerprint_payload := jsonb_build_object(
        'program_id', NEW.program_id, 'event_type', NEW.event_type,
        'event_number', NEW.event_number, 'status_from', NEW.status_from,
        'status_to', NEW.status_to, 'actor_id', NEW.actor_id,
        'actor_role_snapshot', NEW.actor_role_snapshot, 'reason', NEW.reason,
        'supersedes_id', NEW.supersedes_id);
    IF NEW.context_snapshot <> '{}'::jsonb THEN
        fingerprint_payload := fingerprint_payload || jsonb_build_object('context_snapshot', NEW.context_snapshot);
    END IF;
    IF NEW.fingerprint IS DISTINCT FROM encode(
        sha256(convert_to(operations_canonical_jsonb(fingerprint_payload), 'UTF8')), 'hex'
    ) THEN
        RAISE EXCEPTION 'Program lifecycle fingerprint mismatch' USING ERRCODE = '23514';
    END IF;
    IF NEW.event_type IN ('activated', 'completed', 'cancelled') THEN
        -- The alphabetically earlier history guard already holds this root.
        SELECT * INTO current_program FROM operations_treatmentprogram WHERE id = NEW.program_id FOR UPDATE;
        SELECT COALESCE(jsonb_agg(jsonb_build_object(
            'id', id, 'number', number, 'title', title, 'status', status,
            'planned_sessions', planned_sessions, 'service_id', service_id,
            'balance_account_id', balance_account_id) ORDER BY id), '[]'::jsonb)
        INTO block_snapshot FROM operations_programblock WHERE program_id = NEW.program_id;
        expected_snapshot := jsonb_build_object(
            'program_id', current_program.id, 'child_id', current_program.child_id,
            'status', current_program.status, 'starts_on', current_program.starts_on,
            'ends_on', current_program.ends_on, 'blocks', block_snapshot);
        IF NEW.context_snapshot IS DISTINCT FROM expected_snapshot THEN
            RAISE EXCEPTION 'Program review is stale' USING ERRCODE = '23514';
        END IF;
        IF NEW.event_type = 'activated' AND (
            current_program.ends_on < current_program.starts_on OR NOT EXISTS (
                SELECT 1 FROM operations_programblock b JOIN operations_balanceaccount a ON a.id = b.balance_account_id
                WHERE b.program_id = NEW.program_id AND b.status IN ('planned', 'scheduled', 'in_progress')
                AND b.planned_sessions > 0 AND a.child_id = current_program.child_id
                AND (a.service_scope = 'any' OR a.service_id = b.service_id)
            )
        ) THEN
            RAISE EXCEPTION 'Activation requires a valid cascade and date range' USING ERRCODE = '23514';
        END IF;
        IF NEW.event_type = 'completed' AND NEW.actor_role_snapshot <> 'director' AND EXISTS (
            SELECT 1 FROM operations_programblock WHERE program_id = NEW.program_id
            AND status NOT IN ('completed', 'cancelled')
        ) THEN
            RAISE EXCEPTION 'Early program completion requires a director' USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.context_snapshot IS DISTINCT FROM '{}'::jsonb THEN
        RAISE EXCEPTION 'Pause and resume do not carry a cascade review' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER program_review_guard BEFORE INSERT ON operations_treatmentprogramlifecycleevent
    FOR EACH ROW EXECUTE FUNCTION operations_program_review_guard();

CREATE FUNCTION operations_program_block_root_guard() RETURNS trigger AS $$
DECLARE old_root bigint; new_root bigint; root record;
BEGIN
    IF TG_OP <> 'INSERT' THEN old_root := OLD.program_id; END IF;
    IF TG_OP <> 'DELETE' THEN new_root := NEW.program_id; END IF;
    -- Writers lock a block before its roots; lifecycle commands never lock blocks after roots.
    FOR root IN SELECT id, status FROM operations_treatmentprogram
        WHERE id IN (old_root, new_root) ORDER BY id FOR UPDATE
    LOOP
        IF root.id = new_root AND old_root IS DISTINCT FROM new_root
           AND root.status IN ('completed', 'cancelled') THEN
            RAISE EXCEPTION 'Cannot add cascades to a terminal program' USING ERRCODE = '23514';
        END IF;
    END LOOP;
    IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER program_block_root_guard BEFORE INSERT OR UPDATE OR DELETE ON operations_programblock
    FOR EACH ROW EXECUTE FUNCTION operations_program_block_root_guard();
"""


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(STATUS_SQL + REVIEW_SQL, params=None)


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "LOCK TABLE operations_programblock, operations_treatmentprogram, "
            "operations_treatmentprogramlifecycleevent IN SHARE ROW EXCLUSIVE MODE"
        )
    event = apps.get_model("operations", "TreatmentProgramLifecycleEvent")
    if event.objects.using(schema_editor.connection.alias).exclude(event_type__in=["paused", "resumed"]).exists():
        raise RuntimeError("Cannot reverse program completion migration: immutable review history exists.")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER program_review_guard ON operations_treatmentprogramlifecycleevent;
            DROP TRIGGER program_block_root_guard ON operations_programblock;
            DROP FUNCTION operations_program_review_guard();
            DROP FUNCTION operations_program_block_root_guard();
        """)
        legacy_status_sql = STATUS_SQL.replace(
            "IF (latest.id IS NULL OR latest.status_from",
            "IF (OLD.status = 'paused' OR NEW.status = 'paused' OR latest.id IS NOT NULL) "
            "AND (latest.id IS NULL OR latest.status_from",
        )
        schema_editor.execute(legacy_status_sql, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0067_program_pause_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treatmentprogramlifecycleevent',
            name='program_event_transition_role',
        ),
        migrations.AddField(
            model_name='treatmentprogramlifecycleevent',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='состояние перед решением'),
        ),
        migrations.AlterField(
            model_name='treatmentprogramlifecycleevent',
            name='event_type',
            field=models.CharField(choices=[('activated', 'Активировать программу'), ('paused', 'Приостановить программу'), ('resumed', 'Возобновить программу'), ('completed', 'Завершить программу'), ('cancelled', 'Отменить программу')], max_length=20, verbose_name='решение'),
        ),
        migrations.AddConstraint(
            model_name='treatmentprogramlifecycleevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_role_snapshot__in', ['administrator', 'director']), ('event_type', 'paused'), ('status_from', 'active'), ('status_to', 'paused')), models.Q(('actor_role_snapshot', 'director'), ('event_type', 'resumed'), ('status_from', 'paused'), ('status_to', 'active')), models.Q(('actor_role_snapshot__in', ['administrator', 'director']), ('event_type', 'activated'), ('status_from', 'draft'), ('status_to', 'active')), models.Q(('actor_role_snapshot__in', ['administrator', 'director']), ('event_type', 'completed'), ('status_from__in', ['active', 'paused']), ('status_to', 'completed')), models.Q(('actor_role_snapshot__in', ['administrator', 'director']), ('event_type', 'cancelled'), ('status_from__in', ['draft', 'active', 'paused']), ('status_to', 'cancelled')), _connector='OR'), name='program_event_transition_role'),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
