# Generated by Django 5.2.14 on 2026-09-12 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


GUARD_SQL = """
CREATE FUNCTION operations_block_lifecycle_guard() RETURNS trigger AS $$
DECLARE current_block operations_programblock%ROWTYPE;
        reviewed jsonb; payload jsonb; completed_count bigint;
BEGIN
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION 'Block lifecycle history is immutable' USING ERRCODE = '23514';
    END IF;
    SELECT * INTO current_block FROM operations_programblock WHERE id = NEW.block_id FOR UPDATE;
    IF NOT FOUND OR current_block.status IS DISTINCT FROM NEW.status_from THEN
        RAISE EXCEPTION 'Block status is stale' USING ERRCODE = '23514', CONSTRAINT = 'program_block_review_stale';
    END IF;
    PERFORM id FROM operations_treatmentprogram WHERE id = current_block.program_id FOR UPDATE;
    IF NEW.actor_role_snapshot IS DISTINCT FROM operations_operator_actor_role(NEW.actor_id)
       OR NEW.actor_role_snapshot NOT IN ('administrator', 'director')
       OR NOT EXISTS (SELECT 1 FROM auth_user WHERE id = NEW.actor_id AND is_active) THEN
        RAISE EXCEPTION 'Block lifecycle actor role mismatch' USING ERRCODE = '23514';
    END IF;
    IF length(btrim(NEW.reason)) < 5 OR NEW.fingerprint !~ '^[0-9a-f]{64}$' THEN
        RAISE EXCEPTION 'Invalid block lifecycle reason or fingerprint' USING ERRCODE = '23514';
    END IF;
    -- A new SELECT after acquiring locks gets one consistent view of all facts.
    SELECT operations_program_block_review_snapshot(NEW.block_id) INTO reviewed;
    IF NEW.context_snapshot IS DISTINCT FROM reviewed THEN
        RAISE EXCEPTION 'Block review is stale' USING ERRCODE = '23514', CONSTRAINT = 'program_block_review_stale';
    END IF;
    SELECT count(*) INTO completed_count FROM jsonb_array_elements(reviewed -> 'facts') fact
        WHERE fact ->> 'appointment_status' = 'completed'
        AND fact ->> 'participant_status' = 'completed'
        AND fact ->> 'attendance_status' = 'attended'
        AND fact ->> 'withdrawn' = 'false';
    IF NEW.event_type = 'completed' AND NEW.actor_role_snapshot <> 'director'
       AND completed_count < current_block.planned_sessions THEN
        RAISE EXCEPTION 'Early block completion requires director' USING ERRCODE = '23514';
    END IF;
    payload := jsonb_build_object(
        'block_id', NEW.block_id, 'event_type', NEW.event_type,
        'status_from', NEW.status_from, 'status_to', NEW.status_to,
        'actor_id', NEW.actor_id, 'actor_role_snapshot', NEW.actor_role_snapshot,
        'reason', NEW.reason, 'context_snapshot', NEW.context_snapshot);
    IF NEW.fingerprint IS DISTINCT FROM encode(
        sha256(convert_to(operations_canonical_jsonb(payload), 'UTF8')), 'hex'
    ) THEN
        RAISE EXCEPTION 'Block lifecycle fingerprint mismatch' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER block_lifecycle_history_guard BEFORE INSERT OR UPDATE OR DELETE
    ON operations_programblocklifecycleevent FOR EACH ROW EXECUTE FUNCTION operations_block_lifecycle_guard();

CREATE FUNCTION operations_block_status_guard() RETURNS trigger AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        IF OLD.status IN ('completed', 'cancelled') THEN
            RAISE EXCEPTION 'Terminal block cannot be reopened' USING ERRCODE = '23514';
        END IF;
        IF NEW.status IN ('completed', 'cancelled') AND NOT EXISTS (
            SELECT 1 FROM operations_programblocklifecycleevent
            WHERE block_id = NEW.id AND status_from = OLD.status AND status_to = NEW.status
        ) THEN
            RAISE EXCEPTION 'Block closure requires a lifecycle decision' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER block_status_guard BEFORE UPDATE OF status ON operations_programblock
    FOR EACH ROW EXECUTE FUNCTION operations_block_status_guard();

CREATE FUNCTION operations_block_projection_guard() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM operations_programblock WHERE id = NEW.block_id AND status = NEW.status_to) THEN
        RAISE EXCEPTION 'Block projection does not match lifecycle decision' USING ERRCODE = '23514';
    END IF;
    RETURN NEW;
END; $$ LANGUAGE plpgsql;
CREATE CONSTRAINT TRIGGER block_projection_guard AFTER INSERT ON operations_programblocklifecycleevent
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION operations_block_projection_guard();

CREATE FUNCTION operations_block_allocation_guard() RETURNS trigger AS $$
DECLARE current_block operations_programblock%ROWTYPE;
        root_status varchar; old_block_id bigint;
        legacy operations_appointment%ROWTYPE;
BEGIN
    IF NEW.program_block_id IS NULL THEN RETURN NEW; END IF;
    IF TG_OP = 'UPDATE' THEN
        old_block_id := OLD.program_block_id;
        IF OLD.program_block_id IS NOT DISTINCT FROM NEW.program_block_id THEN
            IF TG_TABLE_NAME = 'operations_appointmentparticipant' THEN
                IF OLD.appointment_id IS NOT DISTINCT FROM NEW.appointment_id
                   AND OLD.child_id IS NOT DISTINCT FROM NEW.child_id THEN RETURN NEW; END IF;
            ELSE
                RETURN NEW;
            END IF;
        END IF;
    END IF;
    SELECT * INTO current_block FROM operations_programblock WHERE id = NEW.program_block_id FOR UPDATE;
    SELECT status INTO root_status FROM operations_treatmentprogram WHERE id = current_block.program_id FOR UPDATE;
    IF current_block.status NOT IN ('completed', 'cancelled') AND root_status NOT IN ('paused', 'completed', 'cancelled') THEN
        RETURN NEW;
    END IF;
    -- A first matching legacy projection preserves an existing allocation. It
    -- may be needed when attendance is recorded after the cascade was closed.
    IF TG_TABLE_NAME = 'operations_appointmentparticipant' AND old_block_id IS NULL THEN
        SELECT * INTO legacy FROM operations_appointment WHERE id = NEW.appointment_id;
        IF legacy.program_block_id = NEW.program_block_id AND legacy.child_id = NEW.child_id
           AND NEW.appointment_status = legacy.status AND NEW.attendance_status = legacy.attendance_status
           AND NEW.billing_decision = legacy.billing_decision
           AND NEW.billing_account_id IS NOT DISTINCT FROM legacy.billing_account_id
           AND (legacy.sequence_number IS NULL OR NEW.sequence_number IS NOT DISTINCT FROM legacy.sequence_number)
           AND NEW.starts_at_snapshot = legacy.starts_at AND NEW.ends_at_snapshot = legacy.ends_at
           AND NOT EXISTS (SELECT 1 FROM operations_appointmentparticipant
               WHERE appointment_id = NEW.appointment_id AND id IS DISTINCT FROM NEW.id) THEN
            RETURN NEW;
        END IF;
    END IF;
    RAISE EXCEPTION 'New allocation to a closed or paused program block is forbidden'
        USING ERRCODE = '23514', CONSTRAINT = 'program_block_allocation_closed';
END; $$ LANGUAGE plpgsql;
CREATE TRIGGER block_allocation_guard BEFORE INSERT OR UPDATE OF program_block_id ON operations_appointment
    FOR EACH ROW EXECUTE FUNCTION operations_block_allocation_guard();
CREATE TRIGGER block_allocation_guard BEFORE INSERT OR UPDATE OF program_block_id, appointment_id, child_id ON operations_appointmentparticipant
    FOR EACH ROW EXECUTE FUNCTION operations_block_allocation_guard();
"""


def preflight(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("LOCK TABLE operations_programblock IN SHARE ROW EXCLUSIVE MODE")
    block = apps.get_model("operations", "ProgramBlock")
    invalid = list(block.objects.using(schema_editor.connection.alias)
                   .exclude(status__in=["planned", "scheduled", "in_progress", "completed", "cancelled"])
                   .order_by("pk").values_list("pk", flat=True)[:10])
    if invalid:
        raise RuntimeError(f"Unknown program block statuses (IDs {invalid}); no records were changed.")


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(REVIEW_SNAPSHOT_SQL + GUARD_SQL, params=None)


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("LOCK TABLE operations_programblock, operations_programblocklifecycleevent IN SHARE ROW EXCLUSIVE MODE")
    event = apps.get_model("operations", "ProgramBlockLifecycleEvent")
    if event.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Cannot reverse block lifecycle migration: immutable review history exists.")
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("""
            DROP TRIGGER block_allocation_guard ON operations_appointmentparticipant;
            DROP TRIGGER block_allocation_guard ON operations_appointment;
            DROP TRIGGER block_projection_guard ON operations_programblocklifecycleevent;
            DROP TRIGGER block_status_guard ON operations_programblock;
            DROP TRIGGER block_lifecycle_history_guard ON operations_programblocklifecycleevent;
            DROP FUNCTION operations_block_allocation_guard();
            DROP FUNCTION operations_block_projection_guard();
            DROP FUNCTION operations_block_status_guard();
            DROP FUNCTION operations_block_lifecycle_guard();
            DROP FUNCTION operations_program_block_review_snapshot(bigint);
        """)


REVIEW_SNAPSHOT_SQL = """
CREATE OR REPLACE FUNCTION operations_program_block_review_snapshot(requested_block_id bigint)
RETURNS jsonb
LANGUAGE sql
STABLE
STRICT
AS $$
WITH block AS (
    SELECT
        block.id,
        block.program_id,
        program.child_id,
        program.status AS program_status,
        block.number,
        block.title,
        block.status,
        block.planned_sessions,
        block.service_id,
        block.balance_account_id
    FROM operations_programblock AS block
    JOIN operations_treatmentprogram AS program ON program.id = block.program_id
    WHERE block.id = requested_block_id
), facts AS (
    SELECT
        'participant'::text AS kind,
        appointment.id AS appointment_id,
        participant.id AS participant_id,
        appointment.status AS appointment_status,
        participant.appointment_status AS participant_status,
        participant.attendance_status AS attendance_status,
        EXISTS (
            SELECT 1
            FROM operations_appointmentseriescancellationresult AS cancellation
            WHERE cancellation.appointment_participant_id = participant.id
              AND cancellation.outcome = 'cancelled'
        ) AS withdrawn,
        participant.billing_decision AS billing_decision,
        participant.billing_account_id AS billing_account_id
    FROM operations_appointmentparticipant AS participant
    JOIN operations_appointment AS appointment ON appointment.id = participant.appointment_id
    WHERE participant.program_block_id = requested_block_id

    UNION ALL

    SELECT
        'legacy'::text AS kind,
        appointment.id AS appointment_id,
        NULL::bigint AS participant_id,
        appointment.status AS appointment_status,
        appointment.status AS participant_status,
        appointment.attendance_status AS attendance_status,
        false AS withdrawn,
        appointment.billing_decision AS billing_decision,
        appointment.billing_account_id AS billing_account_id
    FROM operations_appointment AS appointment
    WHERE appointment.program_block_id = requested_block_id
      AND NOT EXISTS (
          SELECT 1
          FROM operations_appointmentparticipant AS participant
          WHERE participant.appointment_id = appointment.id
      )
)
SELECT jsonb_build_object(
    'block', jsonb_build_object(
        'id', block.id,
        'program_id', block.program_id,
        'child_id', block.child_id,
        'program_status', block.program_status,
        'number', block.number,
        'title', block.title,
        'status', block.status,
        'planned_sessions', block.planned_sessions,
        'service_id', block.service_id,
        'balance_account_id', block.balance_account_id
    ),
    'facts', COALESCE(
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'kind', facts.kind,
                    'appointment_id', facts.appointment_id,
                    'participant_id', facts.participant_id,
                    'appointment_status', facts.appointment_status,
                    'participant_status', facts.participant_status,
                    'attendance_status', facts.attendance_status,
                    'withdrawn', facts.withdrawn,
                    'billing_decision', facts.billing_decision,
                    'billing_account_id', facts.billing_account_id
                )
                ORDER BY facts.kind, facts.appointment_id, facts.participant_id
            )
            FROM facts
        ),
        '[]'::jsonb
    )
)
FROM block;
$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0068_program_activation_completion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(preflight, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProgramBlockLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64, verbose_name='отпечаток операции')),
                ('event_type', models.CharField(choices=[('completed', 'Завершить каскад'), ('cancelled', 'Отменить каскад')], max_length=20, verbose_name='решение')),
                ('status_from', models.CharField(choices=[('planned', 'Запланирован'), ('scheduled', 'Расписан'), ('in_progress', 'Идёт'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=30, verbose_name='статус был')),
                ('status_to', models.CharField(choices=[('planned', 'Запланирован'), ('scheduled', 'Расписан'), ('in_progress', 'Идёт'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], max_length=30, verbose_name='статус стал')),
                ('actor_role_snapshot', models.CharField(choices=[('director', 'Руководитель'), ('administrator', 'Администратор')], max_length=20, verbose_name='роль')),
                ('reason', models.TextField(verbose_name='основание')),
                ('context_snapshot', models.JSONField(default=dict, verbose_name='факты перед решением')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='время решения')),
            ],
            options={
                'verbose_name': 'решение по каскаду',
                'verbose_name_plural': 'решения по каскадам',
                'ordering': ['block_id', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='programblock',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planned', 'scheduled', 'in_progress', 'completed', 'cancelled'])), name='program_block_known_status'),
        ),
        migrations.AddField(
            model_name='programblocklifecycleevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_block_lifecycle_events', to=settings.AUTH_USER_MODEL, verbose_name='решение принял'),
        ),
        migrations.AddField(
            model_name='programblocklifecycleevent',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lifecycle_events', to='operations.programblock', verbose_name='каскад'),
        ),
        migrations.AddConstraint(
            model_name='programblocklifecycleevent',
            constraint=models.UniqueConstraint(fields=('block',), name='unique_block_terminal_decision'),
        ),
        migrations.AddConstraint(
            model_name='programblocklifecycleevent',
            constraint=models.CheckConstraint(condition=models.Q(('actor_role_snapshot__in', ['administrator', 'director']), ('status_from__in', ['planned', 'scheduled', 'in_progress']), models.Q(models.Q(('event_type', 'completed'), ('status_to', 'completed')), models.Q(('event_type', 'cancelled'), ('status_to', 'cancelled')), _connector='OR')), name='block_event_transition_role'),
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
