# Generated by Django 5.2.14 on 2026-09-15 17:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0069_program_block_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationEmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес доставки')),
                ('subject', models.CharField(max_length=200, verbose_name='тема')),
                ('body', models.TextField(verbose_name='снимок письма')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='снимок согласования')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('processing', 'Отправляется'), ('retry', 'Ожидает повторной попытки'), ('sent', 'Отправлено'), ('failed', 'Не удалось отправить'), ('cancelled', 'Отправка больше не требуется')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=80)),
                ('confirmation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_delivery', to='operations.appointmentconfirmation')),
            ],
            options={
                'verbose_name': 'доставка письма согласования',
                'verbose_name_plural': 'доставка писем согласований',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='confirmation_email_due_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'retry', 'sent', 'failed', 'cancelled'])), name='confirmation_email_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('claim_token__isnull', False), ('locked_until__isnull', False), ('status', 'processing')), models.Q(models.Q(('status', 'processing'), _negated=True), ('claim_token__isnull', True), ('locked_until__isnull', True)), _connector='OR'), name='confirmation_email_claim_state'), models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', False), ('status', 'sent')), models.Q(models.Q(('status', 'sent'), _negated=True), ('sent_at__isnull', True)), _connector='OR'), name='confirmation_email_sent_state')],
            },
        ),
    ]
