# Generated by Django 5.2.14 on 2026-09-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0070_confirmation_email_outbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffScheduleChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                ("effective_from", models.DateField(verbose_name="действует с")),
                ("week", models.JSONField(default=list, verbose_name="недельный график")),
                ("reason", models.TextField(verbose_name="основание")),
                ("created_by_role", models.CharField(choices=[("specialist", "Специалист"), ("administrator", "Администратор"), ("director", "Руководитель")], max_length=20, verbose_name="роль автора на момент заявки")),
                ("request_key", models.UUIDField(editable=False, unique=True, verbose_name="ключ повтора")),
                ("fingerprint", models.CharField(max_length=64, verbose_name="отпечаток запроса")),
                ("status", models.CharField(choices=[("pending", "Ожидает решения"), ("approved", "Согласовано"), ("rejected", "Отклонено")], default="pending", max_length=20, verbose_name="статус")),
                ("director_priority", models.BooleanField(default=True, verbose_name="приоритет руководителя")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_staff_schedule_requests", to=settings.AUTH_USER_MODEL, verbose_name="заявку создал")),
                ("staff_member", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="schedule_change_requests", to="operations.staffmember", verbose_name="специалист")),
            ],
            options={
                "verbose_name": "заявка на изменение постоянного графика",
                "verbose_name_plural": "заявки на изменение постоянного графика",
                "ordering": ["effective_from", "-created_at"],
                "indexes": [models.Index(fields=["staff_member", "effective_from", "status"], name="operations__staff_m_ca71b9_idx")],
            },
        ),
        migrations.CreateModel(
            name="StaffScheduleChangeDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                ("actor_role", models.CharField(choices=[("administrator", "Администратор"), ("director", "Руководитель")], max_length=20, verbose_name="роль на момент решения")),
                ("action", models.CharField(choices=[("approve", "Согласовать"), ("reject", "Отклонить"), ("confirm", "Подтвердить")], max_length=20, verbose_name="действие")),
                ("reason", models.TextField(verbose_name="основание решения")),
                ("request_key", models.UUIDField(editable=False, unique=True, verbose_name="ключ повтора")),
                ("fingerprint", models.CharField(max_length=64, verbose_name="отпечаток решения")),
                ("is_current", models.BooleanField(default=True, verbose_name="текущее решение")),
                ("requires_director_review", models.BooleanField(default=False, verbose_name="требует контроля руководителя")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="staff_schedule_decisions", to=settings.AUTH_USER_MODEL, verbose_name="решение зафиксировал")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="decisions", to="operations.staffschedulechangerequest", verbose_name="заявка")),
                ("supersedes", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name="superseded_by", to="operations.staffschedulechangedecision", verbose_name="переопределяет решение")),
            ],
            options={
                "verbose_name": "решение по постоянному графику",
                "verbose_name_plural": "решения по постоянному графику",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["request", "is_current", "created_at"], name="operations__request_c93280_idx")],
                "constraints": [
                    models.UniqueConstraint(condition=models.Q(("is_current", True)), fields=("request",), name="unique_current_staff_schedule_decision"),
                    models.CheckConstraint(condition=~models.Q(("reason", "")), name="staff_schedule_decision_reason_required"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffScheduleRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="обновлено")),
                ("effective_from", models.DateField(verbose_name="действует с")),
                ("week", models.JSONField(default=list, verbose_name="снимок недельного графика")),
                ("uses_legacy", models.BooleanField(default=False, verbose_name="использовать прежний график")),
                ("is_current", models.BooleanField(default=True, verbose_name="действующая версия")),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_revisions", to="operations.staffschedulechangedecision", verbose_name="решение")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="operations.staffschedulechangerequest", verbose_name="заявка")),
                ("staff_member", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="schedule_revisions", to="operations.staffmember", verbose_name="специалист")),
            ],
            options={
                "verbose_name": "версия постоянного графика",
                "verbose_name_plural": "версии постоянного графика",
                "ordering": ["-effective_from", "-pk"],
                "indexes": [models.Index(fields=["staff_member", "effective_from", "is_current"], name="operations__staff_m_a92d4e_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("is_current", True)), fields=("staff_member", "effective_from"), name="unique_current_staff_schedule_effective_date")],
            },
        ),
    ]
