# Generated by Django 5.2.14 on 2026-09-20 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0071_staff_schedule_revisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationemaildelivery',
            name='manual_retry_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='confirmationemaildelivery',
            name='manual_retry_used',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ConfirmationEmailManualRetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('actor_role_snapshot', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('request_key', models.UUIDField(editable=False, unique=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('queued', 'Поставлено в очередь'), ('obsolete', 'Согласование больше не актуально'), ('stale', 'Данные доставки устарели'), ('budget_exhausted', 'Ручная попытка уже использована')], max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_email_manual_retries', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_retry_history', to='operations.confirmationemaildelivery')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['delivery', 'created_at'], name='operations__deliver_85878f_idx')],
            },
        ),
    ]
